<?= $this->Html->script('app/components/alert/alert.svc', ['block' => true]); ?>
<?= $this->Html->script('Institution.angular/students/institutions.students.svc', ['block' => true]); ?>
<?= $this->Html->script('Institution.angular/students/institutions.students.ctrl', ['block' => true]); ?>

<script data-require="jquery@1.11.3" data-semver="1.11.3" src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<link data-require="bootstrap@3.3.2" data-semver="3.3.2" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
<script data-require="bootstrap@3.3.2" data-semver="3.3.2" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script data-require="angularjs@1.4.9" data-semver="1.4.9" src="https://code.angularjs.org/1.4.9/angular.min.js"></script>
<script data-require="ui-bootstrap@*" data-semver="1.3.2" src="https://cdn.rawgit.com/angular-ui/bootstrap/gh-pages/ui-bootstrap-tpls-1.3.2.js"></script>

<?php
$this->extend('OpenEmis./Layout/Panel');
$this->start('panelBody');
$session = $this->request->session();
$institutionId = $session->read('Institution.Institutions.id');


$tooltipMessage = __('The password is automatically generated by the system');

?>
<script>
    if(localStorage.getItem('institution_id')){
        localStorage.removeItem("institution_id");
    }
    localStorage.setItem('institution_id', '<?php echo $institutionId;?>');
</script>
<div class="pd-10">
    <div class="stepper-content-wrapper">
        <div class="steps-container">
            <ul class="steps" style="margin-left: 0">
                <li ng-class="{'active': InstitutionStudentController.step === 'user_details'}">
                    <div class="stepper-steps-wrapper">
                        User Details
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': InstitutionStudentController.step === 'internal_search'}">
                    <div class="stepper-steps-wrapper">
                        Internal Search
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': InstitutionStudentController.step === 'external_search'}">
                    <div class="stepper-steps-wrapper">
                        External Search
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': InstitutionStudentController.step === 'confirmation'}">
                    <div class="stepper-steps-wrapper">
                        Confirmation
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': InstitutionStudentController.step === 'add_student'}">
                    <div class="stepper-steps-wrapper">
                        Add Student
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': InstitutionStudentController.step === 'summary'}">
                    <div class="stepper-steps-wrapper">
                        Summary
                        <span class="chevron"></span>
                    </div>
                </li>
            </ul>
        </div>
        <div class="actions top">
            <button
                ng-if="(InstitutionStudentController.step=='user_details')"
                type="button" class="btn close-btn" ng-click="InstitutionStudentController.cancelProcess()">Cancel</button>
            <button
                ng-if="(InstitutionStudentController.step!=='user_details' && InstitutionStudentController.step!=='summary')"
                type="button" class="btn btn-prev close-btn" ng-click="InstitutionStudentController.goToPrevStep()">Back</button>
            <button
                ng-if="(InstitutionStudentController.step=='add_student' && InstitutionStudentController.step!=='summary')"
                type="button" class="btn btn-default" ng-click="InstitutionStudentController.confirmUser()">Confirm</button>
            <button
                ng-if="(InstitutionStudentController.step=='summary')"
                type="button" class="btn close-btn" ng-click="InstitutionStudentController.goToFirstStep()">Close</button>
            <button type="button" class="btn btn-default btn-next"
                ng-if="InstitutionStudentController.step!=='add_student' && InstitutionStudentController.step!=='summary'" ng-click="InstitutionStudentController.goToNextStep()">Next</button>
            <button type="button" class="btn btn-default btn-next"
                ng-if="InstitutionStudentController.step==='summary' && InstitutionStudentController.redirectToGuardian" ng-click="InstitutionStudentController.addGuardian()">Add Guardian</button>
        </div>
        <div class="step-content">
            <div class="alert {{InstitutionStudentController.messageClass}}" ng-if="InstitutionStudentController.message">
                <a class="close" aria-hidden="true" href="#" data-dismiss="alert">×</a>{{InstitutionStudentController.message}}
            </div>
            <div class="step-pane sample-pane" ng-if="InstitutionStudentController.step === 'user_details'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <div class="input string">
                        <label><?= __('OpenEMIS ID') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.openemis_no" type="string" ng-disabled="true">
                        <div ng-if="InstitutionStudentController.postResponse.error.openemis_no" class="error-message">
                            <p ng-repeat="error in InstitutionStudentController.postResponse.error.openemis_no">{{ error }}</p>
                        </div>
                    </div>
                    <div class="input string required">
                        <label><?= __('First Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.first_name" ng-change="InstitutionStudentController.setStudentName()" type="string" ng-focus="InstitutionStudentController.error.first_name = ''">
                        <div ng-if="InstitutionStudentController.error.first_name" class="error-message">
                            <p>{{ InstitutionStudentController.error.first_name }}</p>
                        </div>
                    </div>
                    <div class="input string">
                        <label><?= __('Middle Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.middle_name" ng-change="InstitutionStudentController.setStudentName()" type="string">
                    </div>
                    <div class="input string">
                        <label><?= __('Third Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.third_name" ng-change="InstitutionStudentController.setStudentName()" type="string">
                    </div>
                    <div class="input string required">
                        <label><?= __('Last Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.last_name" ng-change="InstitutionStudentController.setStudentName()" type="string"ng-focus="InstitutionStudentController.error.last_name = ''">
                        <div ng-if="InstitutionStudentController.error.last_name" class="error-message">
                            <p>{{ InstitutionStudentController.error.last_name }}</p>
                        </div>
                    </div>
                    <div class="input string">
                        <label><?= __('Preferred Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.preferred_name" type="string">
                    </div>
                    <div class="input select required error">
                        <label><?= __('Gender') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[gender_id]" id="staff-gender_id"
                                ng-options="option.id as option.name for option in InstitutionStudentController.genderOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.gender_id"
                                ng-change="InstitutionStudentController.changeGender()"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="InstitutionStudentController.error.gender_id" class="error-message">
                            <p >{{ InstitutionStudentController.error.gender_id }}</p>
                        </div>
                    </div>
                    <div class="input date required">
                        <label for="Staff_date_of_birth"><?= __('Date Of Birth') ?></label>
                        <div class="input-group date" id="Student_date_of_birth" style="" datepicker="" ng-model="InstitutionStudentController.selectedStudentData.date_of_birth" ng-click="[isDatepickerOpen = !isDatepickerOpen, InstitutionStudentController.error.date_of_birth = '']">
                            <input type="text" class="form-control " ng-model="InstitutionStudentController.selectedStudentData.date_of_birth" uib-datepicker-popup="dd/MM/yyyy" is-open="isDatepickerOpen" datepicker-options="InstitutionStudentController.datepickerOptions" close-text="Close" alt-input-formats="altInputFormats" style="width: calc(100% - 52px) !important" />
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                        </div>
                        <div ng-if="InstitutionStudentController.error.date_of_birth" class="error-message">
                            <p>{{ InstitutionStudentController.error.date_of_birth }}</p>
                        </div>
                    </div>
                    <div ng-class="nationality_class">
                        <label><?= __('Nationality') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[nationality_id]" id="staff-nationality_id"
                                ng-options="option.id as option.name for option in InstitutionStudentController.nationalitiesOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.nationality_id"
                                ng-change="InstitutionStudentController.changeNationality()"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="InstitutionStudentController.postResponse.error.nationalities[0].nationality_id" class="error-message">
                            <p ng-repeat="error in InstitutionStudentController.postResponse.error.nationalities[0].nationality_id">{{ error }}</p>
                        </div>
                    </div>
                    <div ng-class="InstitutionStudentController.Staff.identity_type_class">
                        <label><?= __('Identity Type') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[identities_type_id]" id="staff-identities_type_id"
                                ng-options="option.id as option.name for option in InstitutionStudentController.identityTypeOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.identity_type_id"
                                ng-change="InstitutionStudentController.changeIdentityType()"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="InstitutionStudentController.postResponse.error.identities[0].identity_type_id" class="error-message">
                            <p ng-repeat="error in InstitutionStudentController.postResponse.error.identities[0].identity_type_id">{{ error }}</p>
                        </div>
                    </div>
                    <div ng-class="InstitutionStudentController.identity_class" ng-if="InstitutionStudentController.selectedStudentData.identity_type_id">
                        <label>{{InstitutionStudentController.selectedStudentData.identity_type_name}}</label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.identity_number" type="string">
                        <div ng-if="InstitutionStudentController.postResponse.error.identities[0].number" class="error-message">
                            <p ng-repeat="error in InstitutionStudentController.postResponse.error.identities[0].number">{{ error }}</p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="step-pane sample-pane" ng-if="InstitutionStudentController.step === 'internal_search'">
                <div class="table-wrapper">
                    <div>
                        <div class="scrolltabs">
                            <div id="institution-student-table" class="table-wrapper">
                                <div ng-if="InstitutionStudentController.internalGridOptions" kd-ag-grid="InstitutionStudentController.internalGridOptions" ag-selection-type="radio" class="ag-height-fixed"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="step-pane sample-pane" ng-if="InstitutionStudentController.step === 'external_search'">
                <div class="table-wrapper">
                    <div>
                        <div class="scrolltabs sticky-content">
                            <div id="institution-student-table" class="table-wrapper">
                                <div ng-if="InstitutionStudentController.externalGridOptions" kd-ag-grid="InstitutionStudentController.externalGridOptions" ag-selection-type="radio" class="ag-height-fixed"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="step-pane sample-pane" ng-if="InstitutionStudentController.step === 'confirmation'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <div class="row section-header header-space-lg">Information</div>
                    <div class="input string row-content">
                        <label><?= __('Photo Content') ?></label>
                        <div>
                            <div class="table-thumb mb-16">
                                <div class="profile-image-thumbnail">
                                    <i class="kd-staff"></i>
                                </div>
                            </div>
                            <p class="font-italic mb-0">* Advisable photo dimension 90 by 115</p>
                            <p class="font-italic">* Format Supported: .jpg, .jpeg, .png, .gif</p>
                            <div class="d-flex">
                                <div class="position-relative">
                                    <button class="btn btn-xs btn-default fontSize-16">
                                        <i class="fa fa-folder"></i>
                                        <span>Select File</span>
                                    </button>
                                    <input type="file" class="input-hidden">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="input string required">
                        <label><?= __('OpenEMIS ID') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.openemis_no" type="string" ng-disabled="true">
                    </div>
                    <div class="input string required">
                        <label><?= __('First Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.first_name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Middle Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.middle_name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Third Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.third_name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string required">
                        <label><?= __('Last Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.last_name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Preferred Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.preferred_name" type="string" ng-disabled="true">
                    </div>
                    <div class="input select required">
                        <label><?= __('Gender') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.gender.name" ng-disabled="true" />
                    </div>
                    <div class="input date required">
                        <label for="Student_date_of_birth"><?= __('Date Of Birth') ?></label>
                        <div class="input-group date " id="Student_date_of_birth" style="">
                            <input type="text" class="form-control " name="Student[date_of_birth]" ng-model="InstitutionStudentController.selectedStudentData.date_of_birth" ng-disabled="true">
                        </div>
                    </div>
                    <div class="row section-header header-space-lg">Location</div>
                    <div class="input string">
                        <label><?= __('Address') ?></label>
                        <textarea ng-model="InstitutionStudentController.selectedStudentData.address" type="string"></textarea>
                    </div>
                    <div class="input string">
                        <label><?= __('Postal Code') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.postalCode" type="string">
                    </div>
                    <div class="row section-header header-space-lg">Address Area</div>
                    <div class="input string">
                        <label><?= __('Address Area') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[gender_id]" id="staff-gender_id"
                                ng-options="option.id as option.name for option in genderOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.addressArea"
                                ng-init="InstitutionStudentController.selectedStudentData.addressArea='';"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                    </div>
                    <div class="row section-header header-space-lg">Birthplace Area</div>
                    <div class="input string">
                        <label><?= __('Birthplace Area') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[gender_id]" id="staff-gender_id"
                                ng-options="option.id as option.name for option in genderOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.birthplaceArea"
                                ng-init="InstitutionStudentController.selectedStudentData.birthplaceArea='';"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                    </div>
                    <div class="row section-header header-space-lg">Identities / Nationalities</div>
                    <div class="input string">
                        <label><?= __('Nationalities') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.nationality_name" type="string" ng-disabled="true" />
                    </div>
                    <div class="input string">
                        <label><?= __('Identity Type') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.identity_type_name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Identity Number') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.identity_number" type="string" ng-disabled="true">
                    </div>
                </form>
            </div>
            <div class="step-pane sample-pane" ng-if="InstitutionStudentController.step === 'add_student'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <div class="row section-header header-space-lg">Informations</div>
                    <div class="input string">
                        <label><?= __('OpenEMIS ID') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.openemis_no" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Student') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Identity Number') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.identity_number" type="string" ng-disabled="true">
                    </div>
                    <div class="input date">
                        <label for="Student_date_of_birth"><?= __('Date Of Birth') ?></label>
                        <div class="input-group date " id="Student_date_of_birth" style="">
                            <input type="text" class="form-control " name="Student[date_of_birth]" ng-model="InstitutionStudentController.selectedStudentData.date_of_birth" ng-disabled="true">
                        </div>
                    </div>
                    <div class="input select">
                        <label><?= __('Gender') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.gender.name" ng-disabled="true" />
                    </div>
                    <div class="input string required">
                        <label><?= __('User Name') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.username" ng-focus="InstitutionStudentController.error.username = ''" />
                        <div ng-if="InstitutionStudentController.error.username" class="error-message">
                            <p>{{ InstitutionStudentController.error.username }}</p>
                        </div>
                    </div>
                    <div class="input string required">
                        <label><?= __('Password') ?></label>
                        <input ng-model="InstitutionStudentController.selectedStudentData.password" ng-focus="InstitutionStudentController.error.password = ''" />
                        <div ng-if="InstitutionStudentController.error.password" class="error-message">
                            <p>{{ InstitutionStudentController.error.password }}</p>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Academic Period') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Student[academic_period_id]" id="student-academic_period_id"
                                ng-options="option.id as option.name for option in InstitutionStudentController.academicPeriodOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.academic_period_id"
                                ng-change="InstitutionStudentController.changeAcademicPeriod()"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="InstitutionStudentController.error.academic_period_id" class="error-message">
                            <p>{{ InstitutionStudentController.error.academic_period_id }}</p>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Education Grade') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Student[education_grade_id]" id="student-education_grade_id"
                                ng-options="option.id as option.name for option in InstitutionStudentController.educationGradeOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.education_grade_id"
                                ng-change="InstitutionStudentController.changeEducationGrade()"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="InstitutionStudentController.error.education_grade_id" class="error-message">
                            <p>{{ InstitutionStudentController.error.education_grade_id }}</p>
                        </div>
                    </div>
                    <div class="input select">
                        <label><?= __('Class') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Student[class_id]" id="student-class_id"
                                ng-options="option.id as option.name for option in InstitutionStudentController.classOptions"
                                ng-model="InstitutionStudentController.selectedStudentData.class_id"
                                ng-change="InstitutionStudentController.changeClass()"
                                >
                                <option value="" >-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="InstitutionStudentController.postResponse.error.class_id" class="error-message">
                            <p ng-repeat="error in InstitutionStudentController.postResponse.error.class_id">{{ error }}</p>
                        </div>
                    </div>
                    <div class="input date required">
                        <label for="Students_start_date"><?= __('Start Date') ?></label>
                        <div class="input-group date" id="Student_start_date" style="" datepicker="" ng-model="InstitutionStudentController.selectedStudentData.startDate" ng-click="[isDatepickerOpen = !isDatepickerOpen, InstitutionStudentController.error.startDate = '']">
                            <input type="text" class="form-control " ng-model="InstitutionStudentController.selectedStudentData.startDate" uib-datepicker-popup="dd/MM/yyyy" is-open="isDatepickerOpen" datepicker-options="InstitutionStudentController.datepickerOptions" close-text="Close" alt-input-formats="altInputFormats" style="width: calc(100% - 52px) !important" />
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                        </div>
                        <div ng-if="InstitutionStudentController.error.startDate" class="error-message">
                            <p>{{ InstitutionStudentController.error.startDate }}</p>
                        </div>
                    </div>
                    <div class="input date required">
                        <label for="Students_end_date"><?= __('End Date') ?></label>
                        <div class="input-group date " id="Students_end_date" style="">
                            <input type="text" class="form-control " name="Student[endDate]" ng-model="InstitutionStudentController.selectedStudentData.endDate" ng-disabled="true">
                        </div>
                    </div>
                    <div ng-repeat="customField in InstitutionStudentController.customFieldsArray">
                        <div class="row section-header header-space-lg">{{customField.sectionName}}</div>
                        <div ng-repeat="field in customField.data">
                            <div class="input string" ng-if="field.field_type === 'TEXT' || field.field_type === 'TEXTAREA' || field.field_type === 'NOTE'">
                                <label>{{field.name}}</label>
                                <input ng-if="field.field_type === 'TEXT'" ng-model="field.answer" type="string" />
                                <textarea ng-if="field.field_type === 'TEXTAREA' || field.field_type === 'NOTE'" ng-model="field.answer" type="string"></textarea>
                            </div>
                            <div class="input select" ng-if="field.field_type === 'DROPDOWN'">
                                <label>{{field.name}}</label>
                                <div class="input-select-wrapper">
                                    <select name="Student[option_id]" id="staff-gender_id"
                                        ng-options="option.option_id as option.option_name for option in field.option"
                                        ng-model="field.selectedOptionId"
                                        ng-change="InstitutionStudentController.changeOption(field,field.selectedOptionId)"
                                        >
                                        <option value="" >-- <?= __('Select') ?> --</option>
                                    </select>
                                </div>
                            </div>
                            <div class="input date" ng-if="field.field_type === 'DATE'">
                                <label for={{field.student_custom_field_id}}>{{field.name}}</label>
                                <div class="input-group date" id={{field.student_custom_field_id} style="" datepicker="" ng-model="field.answer" ng-click="[field.isDatepickerOpen = !field.isDatepickerOpen]" ng-init="field.isDatepickerOpen = false">
                                    <input type="text" class="form-control " ng-model="field.answer" uib-datepicker-popup="dd/MM/yyyy" is-open="field.isDatepickerOpen" datepicker-options="InstitutionStudentController.datepickerOptions" close-text="Close" alt-input-formats="altInputFormats" style="width: calc(100% - 52px) !important" ng-change="field.isDatepickerOpen = false" />
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                </div>
                            </div>
                            <div class="input date" ng-if="field.field_type === 'TIME'">
                                <label for={{field.student_custom_field_id}}>{{field.name}}</label>
                                <div class="input-group time" uib-timepicker ng-model="field.answer" ng-change="InstitutionStudentController.changed(field.answer)" hour-step="1" minute-step="5" show-meridian="true" min="field.min" max="field.max" show-seconds="false"></div>

                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="step-pane sample-pane active" ng-if="InstitutionStudentController.step === 'summary'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post" >
                    <div class="wrapper">
                        <div class="wrapper-child">
                            <div class="panel">
                                <div class="panel-body">
                                    <div class="row section-header">Information</div>
                                    <div class="row hidden"></div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Photo Content</div>
                                        <div class="form-input">
                                            <div class="table-thumb">
                                                <div class="profile-image-thumbnail">
                                                    <i class="kd-staff"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">OpenEMIS ID</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.openemis_no}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">First Name</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.first_name}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Middle Name</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.middle_name}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Third Name</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.third_name}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Last Name</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.last_name}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Preferred Name</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.preferred_name}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Gender</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.gender.name}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Date of Birth</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.dateOfBirth}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Email</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.email}}</div>
                                    </div>
                                    <div class="row section-header">Identities / Nationalities</div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Nationality</div>
                                        <div class="form-input">
                                            <div class="form-input table-full-width">
                                                <div class="table-wrapper">
                                                    <div class="table-in-view">
                                                        <table class="table">
                                                            <thead>
                                                                <tr>
                                                                    <th>Identity Type</th>
                                                                    <th>Identity Number</th>
                                                                    <th>Nationality</th>
                                                                    <th>Preferred</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr>
                                                                    <td class="vertical-align-top">Birth Certificate</td>
                                                                    <td class="vertical-align-top">1234567890</td>
                                                                    <td class="vertical-align-top">American</td>
                                                                    <td class="vertical-align-top">No</td>
                                                                </tr>
                                                            </tbody>				
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row section-header">Location</div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Address</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.address}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Postal Code</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.postalCode}}</div>
                                    </div>
                                    <div class="row section-header">Address Area</div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Address Area</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.addressArea}}</div>
                                    </div>
                                    <div class="row section-header">Birthplace Area</div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Birthplace Area</div>
                                        <div class="form-input">{{InstitutionStudentController.selectedStudentData.birthplaceArea}}</div>
                                    </div>
                                    <div class="row section-header">Other Information</div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Modified By</div>
                                        <div class="form-input">System Administrator</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Modified On</div>
                                        <div class="form-input">August 12, 2021 - 04:48:48</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Created By</div>
                                        <div class="form-input">System Administrator</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6 col-md-3 form-label">Created On</div>
                                        <div class="form-input">SApril 05, 2018 - 18:20:27</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="actions bottom">
        </div>
    </div>
</div>

<script>
$(function () {
var datepicker0 = $('#Students_start_date').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'});
var datepicker1 = $('#Students_date_of_birth').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'});
var datepicker2 = $('#Student_date_of_birth').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'});
var datepicker3 = $('#Students_end_date').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'});
$( document ).on('DOMMouseScroll mousewheel scroll', function(){
    window.clearTimeout( t );
    t = window.setTimeout( function(){
        datepicker0.datepicker('place');
        datepicker1.datepicker('place');
        datepicker2.datepicker('place');
        datepicker3.datepicker('place');
    });
});
});

//]]>
</script>

<style>
    .pd-10 {
        padding: 10px;
    }
    .close-btn {
        border: 1px solid #000;
    }
    .header-space-lg{
        margin-bottom: 20px !important
    }
    .mb-16{
        margin-bottom: 16px;
    }
    .font-italic{
        font-style: italic;
    }
    .mb-0{
        margin-bottom: 0;
    }
    .d-flex{
        display: flex;
    }
    .position-relative{
        position: relative;
    }
    .fontSize-16{
        font-size: 16px !important;
    }
    .input-hidden{
        opacity: 0; 
        position: absolute; 
        width: 100% !important; 
        height: 100% !important;
        left: 0; 
        top: 0;
    }
    .row-content{
        margin-bottom: 16px;
    }
    .vertical-align-top {
        vertical-align: top !important;
    }
    /* stepper container wrapper */
    .stepper-content-wrapper {
        border: 1px solid #d4d4d4;
        border-radius: 4px;
        box-shadow: 0 1px 4px rgb(0 0 0 / 7%);
        background-color: #f9f9f9;
        position: relative;
        min-height: 48px;
    }
    .stepper-content-wrapper{
        -webkit-box-shadow: none!important;
        box-shadow: none!important;
        border: 0;
        background-color: #FFF;
        margin-bottom: 10px;
    }
    .stepper-content-wrapper:before,
    .stepper-content-wrapper:after {
        display: table;
        content: "";
        line-height: 0;
    }
    /* steps container */
    .stepper-content-wrapper .steps-container {
        border-radius: 4px 4px 0 0;
        overflow: hidden;
        border: 1px solid #DDD;
        height: 48px;
        border-bottom: none;
    }
    /* steps */
    
    .stepper-content-wrapper > ul.steps li,
    .stepper-content-wrapper > .steps-container > ul.steps li {
        float: left;
        margin: 0;
        padding: 0 20px 0 30px;
        height: 46px;
        line-height: 46px;
        position: relative;
        background: #ededed;
        color: #999999;
        font-size: 16px;
        cursor: not-allowed;
    }
    .stepper-content-wrapper > ul.steps li,
    .stepper-content-wrapper > .steps-container > ul.steps li {
        float: left;
        margin: 0;
        padding: 8px 20px 0 30px;
        height: 48px;
        line-height: 32px;
        position: relative;
        background: #ededed;
        color: #999;
        font-size: 12px;
        cursor: not-allowed;
        border-bottom: none;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background: #f1f6fc;
        color: #3a87ad;
        cursor: default;
    }
    .stepper-content-wrapper > ul.steps li:first-child,
    .stepper-content-wrapper > .steps-container > ul.steps li:first-child {
        border-radius: 4px 0 0 4px;
        padding-left: 20px;
    }
    .stepper-content-wrapper > ul.steps li:first-child,
    .stepper-content-wrapper > .steps-container > ul.steps li:first-child {
        -webkit-border-radius: 4px 0 0 0;
        border-radius: 4px 0 0 0;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        line-height: 30px;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background-color: #999;
        color: #FFF;
        cursor: default;
        border-bottom: none;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background-color: #69C;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background-color: #6699CC;
    }
    .stepper-content-wrapper .steps {
        margin-left: 0!important;
    }
    .stepper-content-wrapper > ul.steps,
    .stepper-content-wrapper > .steps-container > ul.steps {
        list-style: none outside none;
        padding: 0;
        margin: 0;
        width: 999999px;
    }
    /* step wrapper */
    .stepper-steps-wrapper {
        overflow: hidden;
        width: 100%;
        text-overflow: ellipsis;
        white-space: nowrap;
        text-align: center;
    }
    /* chevron */
    .stepper-content-wrapper > ul.steps li .chevron,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron {
        border: 24px solid transparent;
        border-left: 14px solid #d4d4d4;
        border-right: 0;
        display: block;
        position: absolute;
        right: -14px;
        top: 0;
        z-index: 1;
    }
    .stepper-content-wrapper > ul.steps li .chevron,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron {
        border: 24px solid transparent;
        border-left: 14px solid #d4d4d4;
        border-right: 0;
        display: block;
        position: absolute;
        right: -15px;
        top: -5px;
        z-index: 1;
        margin-top: 5px;
        transform: scale(1.1,1.1);
        -ms-transform: scale(1.1,1.1);
        -webkit-transform: scale(1.1,1.1);
    }
    /* chevron before */
    .stepper-content-wrapper > ul.steps li .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron:before {
        border: 24px solid transparent;
        border-left: 14px solid #ededed;
        border-right: 0;
        content: "";
        display: block;
        position: absolute;
        right: 1px;
        top: -24px;
    }
    .stepper-content-wrapper > ul.steps li .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron:before {
        border: 24px solid transparent;
        border-left: 14px solid #ededed;
        border-right: 0;
        content: "";
        display: block;
        position: absolute;
        right: 1px;
        top: -24px;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron:before {
        border-left: 14px solid #f1f6fc;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron:before {
        border-left: 14px solid #999;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron::before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron::before {
        border-left-color: #69C;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron::before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron::before {
        border-left-color: #6699CC;
    }
    /* action buttons */
    .stepper-content-wrapper > .actions {
        z-index: 1000;
        position: absolute;
        right: 0;
        top: 0;
        line-height: 46px;
        float: right;
        padding-left: 15px;
        padding-right: 15px;
        vertical-align: middle;
        background-color: #e5e5e5;
        border-left: 1px solid #d4d4d4;
        border-radius: 0 4px 0 0;
    }
    .stepper-content-wrapper > .actions {
        background-color: #f9f9f9;
        border-left: 1px solid #d4d4d4;
        border-radius: 0 4px 0 0;
        float: right;
        line-height: 47px;
        padding-left: 15px;
        padding-right: 15px;
        position: absolute;
        right: 1px;
        top: 1px;
        vertical-align: middle;
        z-index: 500;
    }
    /* step content */
    .stepper-content-wrapper .step-content {
        border-top: 1px solid #D4D4D4;
        padding: 10px;
        float: left;
        width: 100%;
    }
    .stepper-content-wrapper .step-content {
        border-top: 1px solid #DDD;
        border-right: 1px solid #DDD;
        border-left: 1px solid #DDD;
        float: left;
        width: 100%;
    }
    @media (min-width: 800px) {
        .row-content{
            display: flex; 
            align-items: flex-start;
        }
    }
    @media only screen and (max-width: 800px){
        .stepper-content-wrapper .actions.top {
        position: fixed!important;
        bottom: 35px!important;
        top: auto!important;
        height: 50px;
        left: 0!important;
        right: 0!important;
        border-top: 1px solid #DDD;
        border-left-color: transparent;
        -webkit-border-radius: 0!important;
        border-radius: 0!important;
        }
        .stepper-content-wrapper .btn-prev,
        .stepper-content-wrapper .btn-next {
            position: relative;
        }
        .stepper-content-wrapper .btn-next {
            text-align: left;
            padding-right: 20px;
        }
        .stepper-content-wrapper .actions.top .btn-next,
        .stepper-content-wrapper .actions.top .btn-prev {
            position: absolute;
            top: 10px;
        }
        .stepper-content-wrapper .actions.top .btn-next {
            right: 10px;
        }
    }

    .uib-title {
        background-color: #fff !important;
        color: #333 !important;
        margin-top: -22px;
        border-color: #ccc !important;
    }

    .uib-left, .uib-right {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #ccc !important;
    }

    .uib-day .btn-sm {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #ccc !important;
    }

    .uib-month .btn-default {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #ccc !important;
    }

    .uib-years .btn-default {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #ccc !important;
    }

    .uib-datepicker-popup {
        padding: 5px 10px;
    }

    .time {
        margin-top: -25px !important;
        margin-bottom: 5px !important;
    }

    .hours {
        vertical-align: middle !important;
    }

    .minutes {
        vertical-align: middle !important;
    }

</style>


<?php
$this->end();
?>