services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.Main
    container_name: openemis-core
    restart: always
    ports:
    - "3000:80"
    # - "25:25"
    depends_on: 
    - db                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    environment:
    - DB_HOST=db
    - DB_NAME=prd_cor_dmo
    - DB_USER=admin
    - DB_PASSWORD=demo
    volumes:
      - ./docker-config/config/.env:/var/www/html/api/.env
    networks:
      - openemis-network
  db:
    image: mysql:8.1
    container_name: openemis-db
    restart: always
    environment:
      - MYSQL_DATABASE=prd_cor_dmo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=demo
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker-config/sql/core-4.24.0.sql:/docker-entrypoint-initdb.d/prd_cor_dmo.sql
      - ./docker-config/sql/my.cnf:/etc/my.cnf
    networks:
      - openemis-network
    # ports:
      # - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: openemis-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
    - db
    environment:
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=demo
    networks:
      - openemis-network
volumes:
  db_data:
networks:
  openemis-network:
    driver: bridge