CREATE INDEX male ON census_students (male);

CREATE INDEX female ON census_students (female);

-- CREATE INDEX age ON census_students (age);

CREATE INDEX male ON census_staff (male);

CREATE INDEX female ON census_staff (female);

-- INSERT INTO `navigations` (`id`, `module`, `plugin`, `controller`, `header`, `title`, `action`, `pattern`, `attributes`, `parent`, `is_wizard`, `order`, `visible`, `modified_user_id`, `modified`, `created_user_id`, `created`) VALUES
-- (146, 'Report', 'OlapCube', 'OlapCube', 'REPORTS', 'Olap Reports', 'olapReport', '^olapReport', NULL, 123, 0, 146, 1, NULL, NULL, 1, '0000-00-00 00:00:00');

TRUNCATE table `olap_cubes`;

INSERT INTO `olap_cubes` (`id`, `cube`, `operation`, `visible`, `order`, `modified_user_id`, `modified`, `created_user_id`, `created`) VALUES
(1, 'Students', 'Count', 1, 1, NULL, NULL, 1, '2014-03-28 00:00:00'),
(2, 'Staff', 'Count', 1, 2, NULL, NULL, 1, '2014-03-28 00:00:00'),
(3, 'Classes', 'Count', 1, 3, NULL, NULL, 1, '2014-03-28 00:00:00'),
(4, 'Textbooks', 'Count', 1, 4, NULL, NULL, 1, '2014-03-28 00:00:00'),
(5, 'Buildings', 'Count', 1, 5, NULL, NULL, 1, '2014-03-28 00:00:00'),
(6, 'Equipment', 'Count', 1, 6, NULL, NULL, 1, '2014-03-28 00:00:00'),
(7, 'Finances', 'Count', 1, 7, NULL, NULL, 1, '2014-03-28 00:00:00');


DROP TABLE IF EXISTS `olap_cube_dimensions`;
CREATE TABLE IF NOT EXISTS `olap_cube_dimensions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dimension` varchar(100) NOT NULL,
  `table_name` varchar(255) NOT NULL,
  `table_parent` varchar(255) NOT NULL,
  `table_join` text,
  `table_field` text,
  `table_compute` varchar(255) DEFAULT NULL,
  `table_aggregate` tinyint(1) NOT NULL DEFAULT '0',
  `table_group` text,
  `olap_cube_id` int(11) NOT NULL,
  `visible` int(1) NOT NULL DEFAULT '1',
  `order` int(3) NOT NULL DEFAULT '0',
  `modified_user_id` int(11) DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created_user_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `olap_cube_id` (`olap_cube_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

--
-- Dumping data for table `olap_cube_dimensions`
--

INSERT INTO `olap_cube_dimensions` (`id`, `dimension`, `table_name`, `table_parent`, `table_join`, `table_field`, `table_compute`, `table_aggregate`, `table_group`, `olap_cube_id`, `visible`, `order`, `modified_user_id`, `modified`, `created_user_id`, `created`) VALUES
(1, 'Education System', 'EducationSystem', 'CensusStudent', 'array(\n	''type'' => ''INNER'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStudent.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''institution_site_programmes'',\n	''alias'' => ''InstitutionSiteProgramme'',\n	''conditions'' => array(''InstitutionSite.id = InstitutionSiteProgramme.institution_site_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_programmes'',\n	''alias'' => ''EducationProgramme'',\n	''conditions'' => array(''EducationProgramme.id = InstitutionSiteProgramme.education_programme_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_cycles'',\n	''alias'' => ''EducationCycle'',\n	''conditions'' => array(''EducationCycle.id = EducationProgramme.education_cycle_id'', ''EducationCycle.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_levels'',\n	''alias'' => ''EducationLevel'',\n	''conditions'' => array(''EducationLevel.id = EducationCycle.education_level_id'', ''EducationLevel.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_systems'',\n	''alias'' => ''EducationSystem'',\n	''conditions'' => array(''EducationSystem.id = EducationLevel.education_system_id'')\n)', 'EducationSystem.name', 'EducationSystem.id', 0, 'EducationSystem.id', 1, 1, 1, NULL, NULL, 1, '2014-03-28 00:00:00'),
(2, 'Institution Provider', 'InstitutionProvider', 'CensusStudent', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStudent.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''field_option_values'',\n	''alias'' => ''InstitutionProvider'',\n	''conditions'' => array(''InstitutionSite.institution_site_provider_id = InstitutionProvider.id'')\n)', 'InstitutionProvider.name', 'InstitutionProvider.id', 0, 'InstitutionProvider.id', 1, 1, 2, NULL, NULL, 1, '2014-04-03 00:00:00'),
(3, 'Institution Site', 'InstitutionSite', 'CensusStudent', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStudent.institution_site_id = InstitutionSite.id'')\n)', 'CONCAT(InstitutionSite.code, '' - '', InstitutionSite.name)', 'InstitutionSite.id', 0, 'InstitutionSite.id', 1, 1, 3, NULL, NULL, 1, '2014-04-03 00:00:00'),
(4, 'Institution Site Type', 'InstitutionSiteType', 'CensusStudent', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStudent.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_types'',\n	''alias'' => ''InstitutionSiteType'',\n	''conditions'' => array(''InstitutionSite.institution_site_type_id = InstitutionSiteType.id'')\n)', 'InstitutionSiteType.name', 'InstitutionSiteType.id', 0, 'InstitutionSiteType.id', 1, 1, 4, NULL, NULL, 1, '2014-04-03 00:00:00'),
(5, 'Year', 'SchoolYear', 'CensusStudent', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_classes'',\n	''alias'' => ''InstitutionSiteClass'',\n	''conditions'' => array(''CensusStudent.institution_site_id  = InstitutionSiteClass.institution_site_id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''school_years'',\n	''alias'' => ''SchoolYear'',\n	''conditions'' => array(''SchoolYear.id = InstitutionSiteClass.school_year_id'')\n)', 'SchoolYear.name', 'SchoolYear.id', 0, 'SchoolYear.id', 1, 1, 5, NULL, NULL, 1, '2014-04-03 00:00:00'),
(6, 'Category', 'StudentCategory', 'CensusStudent', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''student_categories'',\n	''alias'' => ''StudentCategory'',\n	''conditions'' => array(''StudentCategory.id = CensusStudent.student_category_id'')\n)', 'StudentCategory.name', 'StudentCategory.id', 0, 'StudentCategory.id', 1, 1, 6, NULL, NULL, 1, '2014-04-03 00:00:00'),
(7, 'Gender', 'CensusStudent', 'CensusStudent', NULL, '''Male'',''Female''', 'CensusStudent.male,CensusStudent.female', 1, '', 1, 1, 7, NULL, NULL, 1, '2014-04-03 00:00:00'),
(8, 'Age', 'CensusStudent', 'CensusStudent', NULL, 'CensusStudent.age', 'CensusStudent.male+CensusStudent.female', 1, 'CensusStudent.age', 1, 1, 8, NULL, NULL, 1, '2014-04-03 00:00:00'),
(9, 'Education System', 'EducationSystem', 'CensusStaff', 'array(\n	''type'' => ''INNER'',\n	''table'' => ''institution_site_programmes'',\n	''alias'' => ''InstitutionSiteProgramme'',\n	''conditions'' => array(''CensusStaff.institution_site_id = InstitutionSiteProgramme.institution_site_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_programmes'',\n	''alias'' => ''EducationProgramme'',\n	''conditions'' => array(''EducationProgramme.id = InstitutionSiteProgramme.education_programme_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_cycles'',\n	''alias'' => ''EducationCycle'',\n	''conditions'' => array(''EducationCycle.id = EducationProgramme.education_cycle_id'', ''EducationCycle.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_levels'',\n	''alias'' => ''EducationLevel'',\n	''conditions'' => array(''EducationLevel.id = EducationCycle.education_level_id'', ''EducationLevel.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_systems'',\n	''alias'' => ''EducationSystem'',\n	''conditions'' => array(''EducationSystem.id = EducationLevel.education_system_id'')\n)', 'EducationSystem.name', 'EducationSystem.id', 0, 'EducationSystem.id', 2, 1, 1, NULL, NULL, 1, '2014-04-03 00:00:00'),
(10, 'Institution Provider', 'InstitutionProvider', 'CensusStaff', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStaff.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''field_option_values'',\n	''alias'' => ''InstitutionProvider'',\n	''conditions'' => array(''InstitutionSite.institution_site_provider_id = InstitutionProvider.id'')\n)', 'InstitutionProvider.name', 'InstitutionProvider.id', 0, 'InstitutionProvider.id', 2, 1, 2, NULL, NULL, 1, '2014-04-03 00:00:00'),
(11, 'Institution Site', 'InstitutionSite', 'CensusStaff', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStaff.institution_site_id = InstitutionSite.id'')\n)', 'CONCAT(InstitutionSite.code, '' - '', InstitutionSite.name)', 'InstitutionSite.id', 0, 'InstitutionSite.id', 2, 1, 3, NULL, NULL, 1, '2014-04-03 00:00:00'),
(12, 'Institution Site Type', 'InstitutionSiteType', 'CensusStaff', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusStaff.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_types'',\n	''alias'' => ''InstitutionSiteType'',\n	''conditions'' => array(''InstitutionSite.institution_site_type_id = InstitutionSiteType.id'')\n)', 'InstitutionSiteType.name', 'InstitutionSiteType.id', 0, 'InstitutionSiteType.id', 2, 1, 4, NULL, NULL, 1, '2014-04-03 00:00:00'),
(13, 'Year', 'SchoolYear', 'CensusStaff', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''school_years'',\n	''alias'' => ''SchoolYear'',\n	''conditions'' => array(''SchoolYear.id = CensusStaff.school_year_id'')\n)', 'SchoolYear.name', 'SchoolYear.id', 0, 'SchoolYear.id', 2, 1, 5, NULL, NULL, 1, '2014-04-03 00:00:00'),
(14, 'Category', 'StaffCategory', 'CensusStaff', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_staff'',\n	''alias'' => ''InstitutionSiteStaff'',\n	''conditions'' => array(''InstitutionSiteStaff.institution_site_id = CensusStaff.institution_site_id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''staff_categories'',\n	''alias'' => ''StaffCategory'',\n	''conditions'' => array(''StaffCategory.id = InstitutionSiteStaff.staff_category_id'')\n)', 'StaffCategory.name', 'StaffCategory.id', 0, 'StaffCategory.id', 2, 1, 6, NULL, NULL, 1, '2014-04-04 00:00:00'),
(15, 'Gender', 'CensusStaff', 'CensusStaff', NULL, '''Male'',''Female''', 'CensusStaff.male,CensusStaff.female', 1, '', 2, 1, 7, NULL, NULL, 1, '2014-04-03 00:00:00'),
(16, 'Education System', 'EducationSystem', 'CensusClass', 'array(\n	''type'' => ''INNER'',\n	''table'' => ''institution_site_programmes'',\n	''alias'' => ''InstitutionSiteProgramme'',\n	''conditions'' => array(''CensusClass.institution_site_id = InstitutionSiteProgramme.institution_site_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_programmes'',\n	''alias'' => ''EducationProgramme'',\n	''conditions'' => array(''EducationProgramme.id = InstitutionSiteProgramme.education_programme_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_cycles'',\n	''alias'' => ''EducationCycle'',\n	''conditions'' => array(''EducationCycle.id = EducationProgramme.education_cycle_id'', ''EducationCycle.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_levels'',\n	''alias'' => ''EducationLevel'',\n	''conditions'' => array(''EducationLevel.id = EducationCycle.education_level_id'', ''EducationLevel.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_systems'',\n	''alias'' => ''EducationSystem'',\n	''conditions'' => array(''EducationSystem.id = EducationLevel.education_system_id'')\n)', 'EducationSystem.name', 'EducationSystem.id', 0, 'EducationSystem.id', 3, 1, 1, NULL, NULL, 1, '2014-04-03 00:00:00'),
(17, 'Institution Provider', 'InstitutionProvider', 'CensusClass', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusClass.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''field_option_values'',\n	''alias'' => ''InstitutionProvider'',\n	''conditions'' => array(''InstitutionSite.institution_site_provider_id = InstitutionProvider.id'')\n)', 'InstitutionProvider.name', 'InstitutionProvider.id', 0, 'InstitutionProvider.id', 3, 1, 2, NULL, NULL, 1, '2014-04-03 00:00:00'),
(18, 'Institution Site', 'InstitutionSite', 'CensusClass', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusClass.institution_site_id = InstitutionSite.id'')\n)', 'CONCAT(InstitutionSite.code, '' - '', InstitutionSite.name)', 'InstitutionSite.id', 0, 'InstitutionSite.id', 3, 1, 3, NULL, NULL, 1, '2014-04-03 00:00:00'),
(19, 'Institution Site Type', 'InstitutionSiteType', 'CensusClass', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusClass.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_types'',\n	''alias'' => ''InstitutionSiteType'',\n	''conditions'' => array(''InstitutionSite.institution_site_type_id = InstitutionSiteType.id'')\n)', 'InstitutionSiteType.name', 'InstitutionSiteType.id', 0, 'InstitutionSiteType.id', 3, 1, 4, NULL, NULL, 1, '2014-04-03 00:00:00'),
(20, 'Year', 'SchoolYear', 'CensusClass', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''school_years'',\n	''alias'' => ''SchoolYear'',\n	''conditions'' => array(''SchoolYear.id = CensusClass.school_year_id'')\n)', 'SchoolYear.name', 'SchoolYear.id', 0, 'SchoolYear.id', 3, 1, 5, NULL, NULL, 1, '2014-04-03 00:00:00'),
(21, 'Seats', 'CensusClass', 'CensusClass', NULL, 'CensusClass.seats', 'CensusClass.seats', 1, 'CensusClass.id', 3, 1, 6, NULL, NULL, 1, '2014-04-03 00:00:00'),
(22, 'Multi-Grade', 'EducationGrade', 'CensusClass', 'array(\n	''type'' => ''INNER'',\n	''table'' => ''census_class_grades'',\n	''alias'' => ''CensusClassGrade'',\n	''conditions'' => array(''CensusClass.id = CensusClassGrade.census_class_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_grades'',\n	''alias'' => ''EducationGrade'',\n	''conditions'' => array(''EducationGrade.id = CensusClassGrade.education_grade_id'')\n)', 'EducationGrade.name', 'EducationGrade.id', 0, 'EducationGrade.id', 3, 1, 7, NULL, NULL, 1, '2014-04-03 00:00:00'),
(23, 'Education System', 'EducationSystem', 'CensusTextBook', 'array(\n	''type'' => ''INNER'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusTextbook.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''institution_site_programmes'',\n	''alias'' => ''InstitutionSiteProgramme'',\n	''conditions'' => array(''InstitutionSite.id = InstitutionSiteProgramme.institution_site_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_programmes'',\n	''alias'' => ''EducationProgramme'',\n	''conditions'' => array(''EducationProgramme.id = InstitutionSiteProgramme.education_programme_id'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_cycles'',\n	''alias'' => ''EducationCycle'',\n	''conditions'' => array(''EducationCycle.id = EducationProgramme.education_cycle_id'', ''EducationCycle.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_levels'',\n	''alias'' => ''EducationLevel'',\n	''conditions'' => array(''EducationLevel.id = EducationCycle.education_level_id'', ''EducationLevel.visible = 1'')\n),\narray(\n	''type'' => ''INNER'',\n	''table'' => ''education_systems'',\n	''alias'' => ''EducationSystem'',\n	''conditions'' => array(''EducationSystem.id = EducationLevel.education_system_id'')\n)', 'EducationSystem.name', 'EducationSystem.id', 0, 'EducationSystem.id', 4, 1, 1, NULL, NULL, 1, '2014-04-03 00:00:00'),
(24, 'InstitutionProvider', 'InstitutionProvider', 'CensusTextBook', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusTextbook.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''field_option_values'',\n	''alias'' => ''InstitutionProvider'',\n	''conditions'' => array(''InstitutionSite.institution_site_provider_id = InstitutionProvider.id'')\n)', 'InstitutionProvider.name', 'InstitutionProvider.id', 0, 'InstitutionProvider.id', 4, 1, 2, NULL, NULL, 1, '2014-04-04 00:00:00'),
(25, 'Institution Site Type', 'InstitutionSiteType', 'CensusTextBook', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusTextbook.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_types'',\n	''alias'' => ''InstitutionSiteType'',\n	''conditions'' => array(''InstitutionSite.institution_site_type_id = InstitutionSiteType.id'')\n)', 'InstitutionSiteType.name', 'InstitutionSiteType.id', 0, 'InstitutionSiteType.id', 4, 1, 3, NULL, NULL, 1, '2014-04-03 00:00:00'),
(26, 'Subjects', 'EducationGradeSubject', 'CensusTextBook', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''education_grade_subjects'',\n	''alias'' => ''EducationGradeSubject'',\n	''conditions'' => array(''CensusTextbook.education_grade_subject_id = EducationGradeSubject.id'')\n),', 'EducationGradeSubject.name', 'EducationGradeSubject.id', 0, 'EducationGradeSubject.id', 4, 1, 4, NULL, NULL, 1, '2014-04-03 00:00:00'),
(27, 'Education System', 'EducationSystem', 'CensusBuilding', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_programmes'',\n	''alias'' => ''InstitutionSiteProgramme'',\n	''conditions'' => array(''CensusBuilding.institution_site_id = InstitutionSiteProgramme.institution_site_id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''education_programmes'',\n	''alias'' => ''EducationProgramme'',\n	''conditions'' => array(''EducationProgramme.id = InstitutionSiteProgramme.education_programme_id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''education_cycles'',\n	''alias'' => ''EducationCycle'',\n	''conditions'' => array(''EducationCycle.id = EducationProgramme.education_cycle_id'', ''EducationCycle.visible = 1'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''education_levels'',\n	''alias'' => ''EducationLevel'',\n	''conditions'' => array(''EducationLevel.id = EducationCycle.education_level_id'', ''EducationLevel.visible = 1'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''education_systems'',\n	''alias'' => ''EducationSystem'',\n	''conditions'' => array(''EducationSystem.id = EducationLevel.education_system_id'')\n)', 'EducationSystem.name', 'EducationSystem.id', 0, 'EducationSystem.id', 5, 1, 1, NULL, NULL, 1, '2014-04-03 00:00:00'),
(28, 'Institution Provider', 'InstitutionProvider', 'CensusBuilding', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusBuilding.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''field_option_values'',\n	''alias'' => ''InstitutionProvider'',\n	''conditions'' => array(''InstitutionSite.institution_site_provider_id = InstitutionProvider.id'')\n)', 'InstitutionProvider.name', 'InstitutionProvider.id', 0, 'InstitutionProvider.id', 5, 1, 2, NULL, NULL, 1, '2014-04-03 00:00:00'),
(29, 'Institution Site', 'InstitutionSite', 'CensusBuilding', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusBuilding.institution_site_id = InstitutionSite.id'')\n)', 'CONCAT(InstitutionSite.code, '' - '', InstitutionSite.name)', 'InstitutionSite.id', 0, 'InstitutionSite.id', 5, 1, 3, NULL, NULL, 1, '2014-04-03 00:00:00'),
(30, 'Institution Site Type', 'InstitutionSiteType', 'CensusBuilding', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_sites'',\n	''alias'' => ''InstitutionSite'',\n	''conditions'' => array(''CensusBuilding.institution_site_id = InstitutionSite.id'')\n),\narray(\n	''type'' => ''LEFT'',\n	''table'' => ''institution_site_types'',\n	''alias'' => ''InstitutionSiteType'',\n	''conditions'' => array(''InstitutionSite.institution_site_type_id = InstitutionSiteType.id'')\n)', 'InstitutionSiteType.name', 'InstitutionSiteType.id', 0, 'InstitutionSiteType.id', 5, 1, 4, NULL, NULL, 1, '2014-04-03 00:00:00'),
(31, 'Year', 'SchoolYear', 'CensusBuilding', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''school_years'',\n	''alias'' => ''SchoolYear'',\n	''conditions'' => array(''SchoolYear.id = CensusBuilding.school_year_id'')\n)', 'SchoolYear.name', 'SchoolYear.id', 0, 'SchoolYear.id', 5, 1, 5, NULL, NULL, 1, '2014-04-03 00:00:00'),
(32, 'Category', 'InfrastructureBuilding', 'CensusBuilding', 'array(\n	''type'' => ''LEFT'',\n	''table'' => ''infrastructure_buildings'',\n	''alias'' => ''InfrastructureBuilding'',\n	''conditions'' => array(''InfrastructureBuilding.id = CensusBuilding.infrastructure_building_id'')\n)', 'InfrastructureBuilding.name', 'InfrastructureBuilding.id', 0, 'InfrastructureBuilding.id', 5, 1, 6, NULL, NULL, 1, '2014-04-03 00:00:00');
