<?php

namespace App\Repositories;

use App\Http\Controllers\Controller;
use App\Models\AcademicPeriod;
use App\Models\ConfigItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use JWTAuth;
use Illuminate\Support\Facades\DB;

class DirectoryRepository extends Controller
{

    //For POCOR-8104 Start...
    public function getUserTypeList($params)
    {
        try {
            $userTypes = config('constantvalues.userTypes');
            $list = [];
            $c = 0;
            foreach ($userTypes as $k => $uT) {
                $list[$c]['id'] = $k;
                $list[$c]['name'] = $uT;

                $c++;
            }
            
            return $list;
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Type List Not Found');
        }
    }


    public function getUniqueOpenemisId($params)
    {
        try {
            $openEmisNo = getNewOpenemisNo();

            $resp['openemis_no'] = $openEmisNo;
            return $resp;
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Openemis Id.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Openemis Id.');
        }
    }


    public function getAutoGeneratedPassword($params)
    {
        try {
            $configItemTable = new ConfigItem();

            $configItem = $configItemTable->where('code', '=', 'password_min_length')->first();

            $passwordLength = intval($configItem->value) > 3 ? intval($configItem->value) : 4;

            $numberOfGroup = 4;
            $sumTo = $passwordLength;

            $groups = [];

            while (count($groups) != 4) {
                $group = 0;
                $groups = [];
                while (array_sum($groups) != $sumTo) {
                    $groups[$group] = mt_rand(1, $sumTo / mt_rand(1, $numberOfGroup));
                    if (++$group == $numberOfGroup) {
                        $group = 0;
                    }
                }
            }

            $upperCaseData = $configItemTable->where('code', '=', 'password_has_uppercase')->first();

            $upperCase = intval($upperCaseData->value) ? $groups[1] : 0;

            $numericalData = $configItemTable->where('code', '=', 'password_has_number')->first();
            $numerical = intval($numericalData->value) ? $groups[2] : 0;


            $specialCharacter = $configItemTable->where('code', '=', 'password_has_non_alpha')->first();
            $specialCharacter = intval($specialCharacter->value) ? $groups[3] : 0;

            $password = $this->generatePassword($passwordLength, $upperCase, $numerical, $specialCharacter);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Password.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Password.');
        }
    }

    //For POCOR-8104 End...

}


        
