<?php

namespace App\Repositories;

use App\Http\Controllers\Controller;
use App\Models\AcademicPeriod;
use App\Models\ConfigItem;
use App\Models\ContactType;
use App\Models\StaffCustomFormField;
use App\Models\FieldOption;
use App\Models\UserIdentities;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use JWTAuth;
use Illuminate\Support\Facades\DB;

class DirectoryRepository extends Controller
{

    //For POCOR-8104 Start...
    public function getUserTypeList($params)
    {
        try {
            $userTypes = config('constantvalues.userTypes');
            $list = [];
            $c = 0;
            foreach ($userTypes as $k => $uT) {
                $list[$c]['id'] = $k;
                $list[$c]['name'] = $uT;

                $c++;
            }
            
            return $list;
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Type List Not Found');
        }
    }


    public function getUniqueOpenemisId($params)
    {
        try {
            $openEmisNo = getNewOpenemisNo();

            $resp['openemis_no'] = $openEmisNo;
            return $resp;
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Openemis Id.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Openemis Id.');
        }
    }


    public function getAutoGeneratedPassword($params)
    {
        try {
            $resp = [];
            $configItemTable = new ConfigItem();

            $configItem = $configItemTable->where('code', '=', 'password_min_length')->first();

            $passwordLength = intval($configItem->value) > 3 ? intval($configItem->value) : 4;

            $numberOfGroup = 4;
            $sumTo = $passwordLength;

            $groups = [];

            while (count($groups) != 4) {
                $group = 0;
                $groups = [];
                while (array_sum($groups) != $sumTo) {
                    $groups[$group] = mt_rand(1, $sumTo / mt_rand(1, $numberOfGroup));
                    if (++$group == $numberOfGroup) {
                        $group = 0;
                    }
                }
            }

            $upperCaseData = $configItemTable->where('code', '=', 'password_has_uppercase')->first();

            $upperCase = intval($upperCaseData->value) ? $groups[1] : 0;

            $numericalData = $configItemTable->where('code', '=', 'password_has_number')->first();
            $numerical = intval($numericalData->value) ? $groups[2] : 0;


            $specialCharacter = $configItemTable->where('code', '=', 'password_has_non_alpha')->first();
            $specialCharacter = intval($specialCharacter->value) ? $groups[3] : 0;

            //$password = generatePassword($passwordLength, $upperCase, $numerical, $specialCharacter);

            $l = $passwordLength;
            $c = $upperCase;
            $n = $numerical;
            $s = $specialCharacter;

            $out = '';
            // get count of all required minimum special chars
            $count = $c + $n + $s;


            // sanitize inputs; should be self-explanatory
            if (!is_int($l) || !is_int($c) || !is_int($n) || !is_int($s)) {
                return 1;
            } elseif ($l < 0 || $c < 0 || $n < 0 || $s < 0) {
                return 2;
            } elseif ($c > $l) {
                return 3;
            } elseif ($n > $l) {
                return 4;
            } elseif ($s > $l) {
                return 5;
            } elseif ($count > $l) {
                return 6;
            }


            // change these strings if you want to include or exclude possible password characters
            $chars = "abcdefghijklmnopqrstuvwxyz";
            $caps = strtoupper($chars);
            $nums = "0123456789";
            $syms = "!@#$%^&*()-+?";


            // build the base password of all lower-case letters
            for ($i = 0; $i < $l; $i++) {
                $out .= substr($chars, mt_rand(0, strlen($chars) - 1), 1);
            }

            // create arrays if special character(s) required
            if ($count) {
                // split base password to array; create special chars array
                $tmp1 = str_split($out);
                $tmp2 = array();

                // Do not change implementation to using mt_rand to rand unless in PHP 7 as rand will have predicable pattern
                // add required special character(s) to second array
                for ($i = 0; $i < $c; $i++) {
                    array_push($tmp2, substr($caps, mt_rand(0, strlen($caps) - 1), 1));
                }
                for ($i = 0; $i < $n; $i++) {
                    array_push($tmp2, substr($nums, mt_rand(0, strlen($nums) - 1), 1));
                }
                for ($i = 0; $i < $s; $i++) {
                    array_push($tmp2, substr($syms, mt_rand(0, strlen($syms) - 1), 1));
                }
                // hack off a chunk of the base password array that's as big as the special chars array
                $tmp1 = array_slice($tmp1, 0, $l - $count);
                // merge special character(s) array with base password array
                $tmp1 = array_merge($tmp1, $tmp2);
                // mix the characters up
                shuffle($tmp1);
                // convert to string for output
                $out = implode('', $tmp1);
            }

            $resp['password'] = $out;

            return $resp;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Password.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Password.');
        }
    }



    public function getContactTypes($params)
    {
        try {
            $contactTypes = ContactType::select('id', 'name')->get();

            $list = [];
            foreach ($contactTypes as $key => $contactType) {
                $list[$key]['id'] = $contactType['id'];
                $list[$key]['name'] = $contactType['name'];
            }
            return $list;
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Contact Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Contact Type List Not Found');
        }
    }



    public function getStaffCustomFields($params)
    {
        try {
            $customFields = StaffCustomFormField::with([
                    'staffCustomField',
                    'staffCustomField.staffCustomFieldOption:id as option_id,name as option_name,is_default,visible,order as option_order,staff_custom_field_id'
                ])
                ->whereHas('staffCustomField')
                ->where('staff_custom_form_id', 1)
                ->orderBy('order', 'ASC')
                ->get()
                ->toArray();

            return $customFields;
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Staff Custom Fields List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Staff Custom Fields List Not Found');
        }
    }


    public function getFieldOptions($params)
    {
        try {
            $list = FieldOption::get()->toArray();

            $total = count($list);

            $resp['list'] = $list;
            $resp['total'] = $total;
            
            return $resp;
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Field Options List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Field Options List Not Found');
        }
    }


    public function getFieldOptionData($params, $fieldOptionId)
    {
        try {
            $data = FieldOption::where('id', $fieldOptionId)->first();
            $resp = [];

            if($data){
                $resp['data'] = $data;
            }
            

            return $resp;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Field Option Data from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Field Option Data Not Found');
        }
    }



    public function getUserByIdentityNumber($params, $identityTypeId, $identityNumber)
    {
        try {
            $resp = [];
            $user_id = $params['user_id'] ?? null;
            $nationality_id = $params['nationality_id'] ?? null;

            $checkUser = UserIdentities::where('identity_type_id', $identityTypeId)->where('number', 'LIKE', '%'.$identityNumber.'%');

            if($user_id){
                $checkUser = $checkUser->where('security_user_id', $user_id);
            }

            if($nationality_id){
                $checkUser = $checkUser->where('nationality_id', $nationality_id);
            }

            $checkUser = $checkUser->first();
            
            if($checkUser){
                $checkUser = $checkUser->toArray();
                $resp['user_exist'] = 1;
                $resp['data'] = $checkUser;
            } else {
                $resp['user_exist'] = 0;
                $resp['data'] = $checkUser;
            }
            return $resp;
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Data from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Data Not Found');
        }
    }


    public function getUserByBasicInfo($params)
    {
        try {
            dd("getUserByBasicInfo");
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Data from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Data Not Found');
        }
    }
    //For POCOR-8104 End...

}


        
