<?php
namespace Report\Model\Table;

use ArrayObject;
use Cake\ORM\Entity;
use Cake\ORM\Query;
use Cake\Event\Event;
use Cake\Network\Request;
use App\Model\Table\AppTable;
use Cake\ORM\TableRegistry;

class StudentsRiskAssessmentTable extends AppTable  {
	public function initialize(array $config) {
		$this->table('institution_students');
		parent::initialize($config);
        $this->addBehavior('Report.ReportList');
        $this->addBehavior('StudentsRiskAssessmentExcel', [
            'pages' => false
        ]);

    }

    public function onExcelBeforeStart (Event $event, ArrayObject $settings, ArrayObject $sheets)
    {
        $sheets[] = [
            'name' => $this->alias(),
            'table' => $this,
            'query' => $this->find(),
            'orientation' => 'landscape'
        ];
    }

    public function onExcelBeforeQuery(Event $event, ArrayObject $settings, Query $query) {
        
  }

public function onExcelUpdateFields(Event $event, ArrayObject $settings, $fields)
{
    $cloneFields = $fields->getArrayCopy();

    $extraFields[] = [
        'key' => 'Institutions.code',
        'field' => 'institution_code',
        'type' => 'string',
        'label' => __('Code')
    ];

    $extraFields[] = [
        'key' => 'Institutions.name',
        'field' => 'institution_name',
        'type' => 'string',
        'label' => __('Name')
    ];

    $extraFields[] = [
        'key' => 'AcademicPeriods.name',
        'field' => 'academic_period_name',
        'type' => 'string',
        'label' => __('Academic Period')
    ];

    $extraFields[] = [
        'key' => 'Risks.first_name',
        'field' => 'risk_type',
        'type' => 'string',
        'label' => __('Risk Type')
    ];

    $extraFields[] = [
        'key' => 'Users.openemis_no',
        'field' => 'student_openemis_no',
        'type' => 'string',
        'label' => __('OpenEMIS ID')
    ];

    $extraFields[] = [
        'key' => 'Users.identity_type_id',
        'field' => 'student_identity_number',
        'type' => 'string',
        'label' => __('Default Identity Type')
    ];

    $extraFields[] = [
        'key' => 'Users.identity_number',
        'field' => 'student_identity_number',
        'type' => 'string',
        'label' => __('Identity Number')
    ];

    $extraFields[] = [
        'key' => '',
        'field' => 'student_name',
        'type' => 'string',
        'label' => __('Student First Name')
    ]; 

    $extraFields[] = [
        'key' => 'InstitutionStudentRisks.total_risk',
        'field' => 'risk_index',
        'type' => 'string',
        'label' => __('Risk Index')
    ];

    $extraFields[] = [
        'key' => 'risk_criterias',
        'field' => 'risk_criterias',
        'type' => 'array',
        'label' => __('Risk Criterias')
    ];

        //POCOR-5861
        /*$extraFields[] = [
            'key' => 'Users.name',
            'field' => 'risk_generated_by',
            'type' => 'string',
            'label' => __('Risk Generated By')
        ];

        $extraFields[] = [
            'key' => 'InstitutionRisks.generated_on',
            'field' => 'risk_generated_on',
            'type' => 'string',
            'label' => __('Risk Generated On')
        ];*/


        $newFields = $extraFields;
        
        $fields->exchangeArray($newFields);
    }

}
