<?php
use Migrations\AbstractSeed;

/**
 * ConfigItems seed.
 */
class ConfigItemsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'name' => 'Database Version',
                'code' => 'db_version',
                'type' => 'System',
                'label' => 'Database Version',
                'value' => '3.10.11',
                'default_value' => '1.0',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '2',
                'name' => 'Title',
                'code' => 'adaptation',
                'type' => 'System',
                'label' => 'Title',
                'value' => 'OpenEMIS Core',
                'default_value' => 'OpenEMIS Core',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-07-04 17:52:44',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '3',
                'name' => 'Footer',
                'code' => 'footer',
                'type' => 'System',
                'label' => 'Footer',
                'value' => 'Copyright &copy; year OpenEMIS. All rights reserved.',
                'default_value' => 'Copyright &copy; 2015 OpenEMIS. All rights reserved.',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '4',
                'name' => 'Time Format',
                'code' => 'time_format',
                'type' => 'System',
                'label' => 'Time Format',
                'value' => 'H:i:s',
                'default_value' => 'H:i:s',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '5',
                'name' => 'Date Format',
                'code' => 'date_format',
                'type' => 'System',
                'label' => 'Date Format',
                'value' => 'F d, Y',
                'default_value' => 'Y-m-d',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'date_format',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:23',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '7',
                'name' => 'Image Width',
                'code' => 'dashboard_img_width',
                'type' => 'System',
                'label' => 'Image Width',
                'value' => '700',
                'default_value' => '700',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '8',
                'name' => 'Image Height',
                'code' => 'dashboard_img_height',
                'type' => 'System',
                'label' => 'Image Height',
                'value' => '320',
                'default_value' => '320',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '9',
                'name' => 'Image Default Id',
                'code' => 'dashboard_img_default',
                'type' => 'System',
                'label' => 'Image Default Id',
                'value' => '1',
                'default_value' => '1',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '10',
                'name' => 'File Size Limit',
                'code' => 'dashboard_img_size_limit',
                'type' => 'System',
                'label' => 'File Size Limit',
                'value' => '2097152',
                'default_value' => '2097152',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '11',
                'name' => 'Telephone',
                'code' => 'support_phone',
                'type' => 'Help',
                'label' => 'Telephone',
                'value' => '+65 6659 6068',
                'default_value' => '+65 6659 6068',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '12',
                'name' => 'Email',
                'code' => 'support_email',
                'type' => 'Help',
                'label' => 'Email',
                'value' => 'support@openemis.org',
                'default_value' => 'support@openemis.org',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '13',
                'name' => 'Address',
                'code' => 'support_address',
                'type' => 'Help',
                'label' => 'Address',
                'value' => '18 Sin Ming Lane #06-38 Midview City Singapore 573960',
                'default_value' => '18 Sin Ming Lane #06-38 Midview City Singapore 573960',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2013-12-12 13:56:00',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '14',
                'name' => 'Currency',
                'code' => 'currency',
                'type' => 'System',
                'label' => 'Currency',
                'value' => 'PM',
                'default_value' => '$',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:23',
                'created_user_id' => '1',
                'created' => '2013-01-07 00:00:00',
            ],
            [
                'id' => '15',
                'name' => 'Lowest Year',
                'code' => 'lowest_year',
                'type' => 'System',
                'label' => 'Lowest Year',
                'value' => '1950',
                'default_value' => '1950',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2013-01-07 00:00:00',
            ],
            [
                'id' => '16',
                'name' => 'Language',
                'code' => 'language',
                'type' => 'System',
                'label' => 'Language',
                'value' => 'en',
                'default_value' => 'en',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'language',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:23',
                'created_user_id' => '1',
                'created' => '2013-01-07 00:00:00',
            ],
            [
                'id' => '17',
                'name' => 'Data Discrepancy Variation(%)',
                'code' => 'report_discrepancy_variationpercent',
                'type' => 'Data Discrepancy',
                'label' => 'Data Discrepancy',
                'value' => '12',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 13:32:48',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '18',
                'name' => 'Maximum Student Age',
                'code' => 'report_outlier_max_age',
                'type' => 'Data Outliers',
                'label' => 'Data Outliers',
                'value' => '21',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 13:43:09',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '19',
                'name' => 'Minimum Student Age',
                'code' => 'report_outlier_min_age',
                'type' => 'Data Outliers',
                'label' => 'Minimum Student Age',
                'value' => '1',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:23',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '20',
                'name' => 'Maximum Student Number',
                'code' => 'report_outlier_max_student',
                'type' => 'Data Outliers',
                'label' => 'Maximum Student Number',
                'value' => '21',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:23',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '21',
                'name' => 'Minimum Student Number',
                'code' => 'report_outlier_min_student',
                'type' => 'Data Outliers',
                'label' => 'Minimum Student Number',
                'value' => '23131230',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:24',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '35',
                'name' => 'Institution Code',
                'code' => 'institution_code',
                'type' => 'Custom Validation',
                'label' => 'Institution Code',
                'value' => '',
                'default_value' => '',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:24',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '36',
                'name' => 'Institution Telephone',
                'code' => 'institution_telephone',
                'type' => 'Custom Validation',
                'label' => 'Institution Telephone',
                'value' => '',
                'default_value' => '',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:24',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '37',
                'name' => 'Institution Fax',
                'code' => 'institution_fax',
                'type' => 'Custom Validation',
                'label' => 'Institution Fax',
                'value' => '',
                'default_value' => '',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:24',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '38',
                'name' => 'Postal Code',
                'code' => 'postal_code',
                'type' => 'Custom Validation',
                'label' => 'Postal Code',
                'value' => '',
                'default_value' => '',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:24',
                'created_user_id' => '0',
                'created' => '2016-10-14 06:16:09',
            ],
            [
                'id' => '48',
                'name' => 'Change Administrator password',
                'code' => 'change_password',
                'type' => 'System',
                'label' => 'Change Administrator password',
                'value' => '1',
                'default_value' => '1',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '49',
                'name' => 'LDAP Server',
                'code' => 'host',
                'type' => 'LDAP Configuration',
                'label' => 'LDAP Server',
                'value' => 'ldap.testathon.net',
                'default_value' => 'ldap.testathon.net',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-08-20 14:46:02',
            ],
            [
                'id' => '50',
                'name' => 'Port',
                'code' => 'port',
                'type' => 'LDAP Configuration',
                'label' => 'Port',
                'value' => '389',
                'default_value' => '389',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-08-20 14:46:02',
            ],
            [
                'id' => '51',
                'name' => 'Version',
                'code' => 'ldap_version',
                'type' => 'LDAP Configuration',
                'label' => 'Version',
                'value' => '3',
                'default_value' => '3',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-08-20 14:46:02',
            ],
            [
                'id' => '52',
                'name' => 'Base DN',
                'code' => 'base_dn',
                'type' => 'LDAP Configuration',
                'label' => 'Base DN',
                'value' => 'OU=users,DC=testathon,DC=net',
                'default_value' => 'OU=users,DC=testathon,DC=net',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-08-20 14:46:02',
            ],
            [
                'id' => '53',
                'name' => 'Test Connection',
                'code' => 'test_connection',
                'type' => 'LDAP Configuration',
                'label' => 'Test Connection',
                'value' => '',
                'default_value' => '',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-08-20 14:46:02',
            ],
            [
                'id' => '55',
                'name' => 'Title',
                'code' => 'where_is_my_school_title',
                'type' => 'Where\'s My School Config',
                'label' => 'Title',
                'value' => 'Where is My School?',
                'default_value' => '',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-10-20 17:41:38',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '56',
                'name' => 'Where is my School URL',
                'code' => 'where_is_my_school_url',
                'type' => 'Where\'s My School Config',
                'label' => 'Where is my School URL',
                'value' => 'http://www.openemis.org/demo',
                'default_value' => 'http://www.openemis.org/demo',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-10-20 17:41:57',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '57',
                'name' => 'Starting Longitude',
                'code' => 'where_is_my_school_start_long',
                'type' => 'Where\'s My School Config',
                'label' => 'Starting Longitude',
                'value' => '-88.53892',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-10-20 17:40:28',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '58',
                'name' => 'Starting Latitude',
                'code' => 'where_is_my_school_start_lat',
                'type' => 'Where\'s My School Config',
                'label' => 'Starting Latitude',
                'value' => '17.048877',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-10-20 17:40:16',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '59',
                'name' => 'Starting Range',
                'code' => 'where_is_my_school_start_range',
                'type' => 'Where\'s My School Config',
                'label' => 'Starting Range',
                'value' => '2613016',
                'default_value' => '2000000',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '60',
                'name' => 'Allow Users to change Language',
                'code' => 'language_menu',
                'type' => 'System',
                'label' => 'Allow Users to change Language',
                'value' => '1',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'yes_no',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 11:47:38',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '61',
                'name' => 'SMS Provider URL',
                'code' => 'sms_provider_url',
                'type' => 'SMS',
                'label' => 'SMS Provider URL',
                'value' => 'http://www.smsdome.com/api/http/sendsms.aspx?login=KORD&password=KT131210&responseformat=JSON',
                'default_value' => 'http://www.smsdome.com/api/http/sendsms.aspx?login=KORD&password=KT131210&responseformat=JSON',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-12-19 10:53:33',
            ],
            [
                'id' => '62',
                'name' => 'SMS Number',
                'code' => 'sms_number',
                'type' => 'SMS',
                'label' => 'SMS Number',
                'value' => 'receivers',
                'default_value' => 'receivers',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-12-19 10:53:33',
            ],
            [
                'id' => '63',
                'name' => 'SMS Content',
                'code' => 'sms_content',
                'type' => 'SMS',
                'label' => 'SMS Content',
                'value' => 'content',
                'default_value' => 'content',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-12-19 10:53:33',
            ],
            [
                'id' => '64',
                'name' => 'SMS Retry Times',
                'code' => 'sms_retry_times',
                'type' => 'SMS',
                'label' => 'SMS Retry Times',
                'value' => '10',
                'default_value' => '3',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-12-19 10:53:33',
            ],
            [
                'id' => '65',
                'name' => 'SMS Retry Delay',
                'code' => 'sms_retry_wait',
                'type' => 'SMS',
                'label' => 'SMS Retry Delay',
                'value' => '5',
                'default_value' => '5',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '1',
                'created' => '2013-12-19 10:53:33',
            ],
            [
                'id' => '66',
                'name' => 'Maximum Credits',
                'code' => 'training_credit_hour',
                'type' => 'Training',
                'label' => 'Maximum Credits',
                'value' => '2',
                'default_value' => '10',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 13:48:41',
                'created_user_id' => '0',
                'created' => '2014-02-21 00:00:00',
            ],
            [
                'id' => '69',
                'name' => 'Contacts',
                'code' => 'StudentContacts',
                'type' => 'Add New Student',
                'label' => 'Contacts',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '70',
                'name' => 'Identities',
                'code' => 'StudentIdentities',
                'type' => 'Add New Student',
                'label' => 'Identities',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '71',
                'name' => 'Nationalities',
                'code' => 'StudentNationalities',
                'type' => 'Add New Student',
                'label' => 'Nationalities',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:25',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '75',
                'name' => 'Special Needs',
                'code' => 'StudentSpecialNeeds',
                'type' => 'Add New Student',
                'label' => 'Special Needs',
                'value' => '2',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '1',
                'modified' => '2015-07-10 06:26:28',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '93',
                'name' => 'Contacts',
                'code' => 'StaffContacts',
                'type' => 'Add New Staff',
                'label' => 'Contacts',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:26',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '94',
                'name' => 'Identities',
                'code' => 'StaffIdentities',
                'type' => 'Add New Staff',
                'label' => 'Identities',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:26',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '95',
                'name' => 'Nationalities',
                'code' => 'StaffNationalities',
                'type' => 'Add New Staff',
                'label' => 'Nationalities',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:26',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '99',
                'name' => 'Special Needs',
                'code' => 'StaffSpecialNeeds',
                'type' => 'Add New Staff',
                'label' => 'Special Needs',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'wizard',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:26',
                'created_user_id' => '0',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '100',
                'name' => 'Area Education API',
                'code' => 'area_api',
                'type' => 'Administrative Boundaries',
                'label' => 'Area Education API',
                'value' => '',
                'default_value' => '',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '2',
                'modified' => '2016-11-11 15:44:18',
                'created_user_id' => '2',
                'created' => '2016-09-13 05:53:52',
            ],
            [
                'id' => '104',
                'name' => 'Display Area Level',
                'code' => 'institution_area_level_id',
                'type' => 'Institution',
                'label' => 'Display Area Level',
                'value' => '1',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'database:Area.AreaLevels',
                'modified_user_id' => '2',
                'modified' => '2017-10-27 14:32:53',
                'created_user_id' => '1',
                'created' => '2015-08-12 00:00:00',
            ],
            [
                'id' => '105',
                'name' => 'Number of Shifts',
                'code' => 'no_of_shifts',
                'type' => 'System',
                'label' => 'Number of Shifts',
                'value' => '3',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 13:46:52',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '106',
                'name' => 'Admission Age Plus',
                'code' => 'admission_age_plus',
                'type' => 'Student Admission Age',
                'label' => 'Admission Age Plus',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 13:46:27',
                'created_user_id' => '1',
                'created' => '2014-03-21 00:00:00',
            ],
            [
                'id' => '107',
                'name' => 'Admission Age Minus',
                'code' => 'admission_age_minus',
                'type' => 'Student Admission Age',
                'label' => 'Admission Age Minus',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '108',
                'modified' => '2014-04-02 16:48:26',
                'created_user_id' => '1',
                'created' => '2014-03-21 00:00:00',
            ],
            [
                'id' => '108',
                'name' => 'First Day of Week',
                'code' => 'first_day_of_week',
                'type' => 'Attendance',
                'label' => 'First Day of Week',
                'value' => '1',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'first_day_of_week',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '109',
                'name' => 'Hours per Day',
                'code' => 'hours_per_day',
                'type' => 'Attendance',
                'label' => 'Hours per Day',
                'value' => '',
                'default_value' => '6',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '110',
                'name' => 'Start Time',
                'code' => 'start_time',
                'type' => 'Attendance',
                'label' => 'Start Time',
                'value' => '',
                'default_value' => '08:00 AM',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-06-12 10:42:48',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '111',
                'name' => 'Days per Week',
                'code' => 'days_per_week',
                'type' => 'Attendance',
                'label' => 'Days per Week',
                'value' => '',
                'default_value' => '5',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '1',
                'modified' => '2014-06-12 10:34:07',
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '112',
                'name' => 'Frequency',
                'code' => 'alert_frequency',
                'type' => 'Alerts',
                'label' => 'Frequency',
                'value' => '1',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '113',
                'name' => 'Retry',
                'code' => 'alert_retry',
                'type' => 'Alerts',
                'label' => 'Retry',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '114',
                'name' => 'SMS Content Length',
                'code' => 'sms_content_length',
                'type' => 'SMS',
                'label' => 'SMS Content Length',
                'value' => '',
                'default_value' => '160',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '1970-01-01 00:00:00',
            ],
            [
                'id' => '116',
                'name' => 'Url',
                'code' => 'support_url',
                'type' => 'Help',
                'label' => 'Url',
                'value' => 'https://support.openemis.org/core/',
                'default_value' => 'https://support.openemis.org/core/',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-12-02 11:08:14',
            ],
            [
                'id' => '118',
                'name' => 'Google Map Center Longitude',
                'code' => 'google_map_center_longitude',
                'type' => 'Map',
                'label' => 'Google Map Center Longitude',
                'value' => '103.81',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '2',
                'modified' => '2016-05-05 06:15:11',
                'created_user_id' => '1',
                'created' => '2016-01-12 16:03:37',
            ],
            [
                'id' => '119',
                'name' => 'Google Map Center Latitude',
                'code' => 'google_map_center_latitude',
                'type' => 'Map',
                'label' => 'Google Map Center Latitude',
                'value' => '1.35',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => '2',
                'modified' => '2016-05-05 06:15:25',
                'created_user_id' => '1',
                'created' => '2016-01-12 16:03:37',
            ],
            [
                'id' => '120',
                'name' => 'Google Map Zoom',
                'code' => 'google_map_zoom',
                'type' => 'Map',
                'label' => 'Google Map Zoom',
                'value' => '10',
                'default_value' => '10',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-01-12 16:03:37',
            ],
            [
                'id' => '121',
                'name' => 'Minimum Length',
                'code' => 'password_min_length',
                'type' => 'Password',
                'label' => 'Min Length',
                'value' => '6',
                'default_value' => '6',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-03-10 10:30:42',
            ],
            [
                'id' => '122',
                'name' => 'Has at least 1 Uppercase Character',
                'code' => 'password_has_uppercase',
                'type' => 'Password',
                'label' => 'Has Uppercase',
                'value' => '0',
                'default_value' => '0',
                'editable' => '0',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'yes_no',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-03-10 10:30:42',
            ],
            [
                'id' => '123',
                'name' => 'Has at least 1 Lowercase Character',
                'code' => 'password_has_lowercase',
                'type' => 'Password',
                'label' => 'Has Lowercase',
                'value' => '0',
                'default_value' => '0',
                'editable' => '0',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'yes_no',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-03-10 10:30:42',
            ],
            [
                'id' => '124',
                'name' => 'Has at least 1 Number',
                'code' => 'password_has_number',
                'type' => 'Password',
                'label' => 'Has Number',
                'value' => '0',
                'default_value' => '0',
                'editable' => '0',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'yes_no',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-03-10 10:30:42',
            ],
            [
                'id' => '125',
                'name' => 'Has at least 1 Non-alphanumeric Character',
                'code' => 'password_has_non_alpha',
                'type' => 'Password',
                'label' => 'Has Non Alpha',
                'value' => '0',
                'default_value' => '0',
                'editable' => '0',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'yes_no',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-03-10 10:30:42',
            ],
            [
                'id' => '126',
                'name' => 'Validate Area Level',
                'code' => 'institution_validate_area_level_id',
                'type' => 'Institution',
                'label' => 'Validate Area Level',
                'value' => '1',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'database:Area.AreaLevels',
                'modified_user_id' => '2',
                'modified' => '2017-10-27 15:12:39',
                'created_user_id' => '1',
                'created' => '2017-03-08 00:00:00',
            ],
            [
                'id' => '127',
                'name' => 'Validate Area Administrative Level',
                'code' => 'institution_validate_area_administrative_level_id',
                'type' => 'Institution',
                'label' => 'Validate Area Administrative Level',
                'value' => '1',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'database:Area.AreaAdministrativeLevels',
                'modified_user_id' => '2',
                'modified' => '2017-03-30 15:48:01',
                'created_user_id' => '1',
                'created' => '2017-03-08 00:00:00',
            ],
            [
                'id' => '200',
                'name' => 'Version Support Emails',
                'code' => 'version_support_emails',
                'type' => 'System',
                'label' => 'Version Support Emails',
                'value' => 'support@openemis.org' ,
                'default_value' => 'support@openemis.org',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-01-03 10:12:18',
            ],
            [
                'id' => '201',
                'name' => 'Version API Domain',
                'code' => 'version_api_domain',
                'type' => 'System',
                'label' => 'Version API Domain',
                'value' => 'https://demo.openemis.org/core',
                'default_value' => 'https://demo.openemis.org/core',
                'editable' => '0',
                'visible' => '0',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-01-03 10:12:18',
            ],
            [
                'id' => '1000',
                'name' => 'Product Lists',
                'code' => 'product_lists',
                'type' => 'Product Lists',
                'label' => 'Product Lists',
                'value' => '0',
                'default_value' => '0',
                'editable' => '0',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-09-13 05:53:53',
            ],
            [
                'id' => '1001',
                'name' => 'Enable Local Login',
                'code' => 'enable_local_login',
                'type' => 'Authentication',
                'label' => 'Enable Local Login',
                'value' => '1',
                'default_value' => '1',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'yes_no',
                'modified_user_id' => '1',
                'modified' => '2014-04-24 12:58:00',
                'created_user_id' => '1',
                'created' => '2013-08-20 14:46:02',
            ],
            [
                'id' => '1002',
                'name' => 'Type',
                'code' => 'external_data_source_type',
                'type' => 'External Data Source',
                'label' => 'Type',
                'value' => 'OpenEMIS Identity',
                'default_value' => 'None',
                'editable' => '1',
                'visible' => '1',
                'field_type' => 'Dropdown',
                'option_type' => 'external_data_source_type',
                'modified_user_id' => '2',
                'modified' => '2017-09-26 10:41:01',
                'created_user_id' => '1',
                'created' => '2016-10-24 10:19:01',
            ],
            [
                'id' => '1003',
                'name' => 'OpenEMIS ID Prefix',
                'code' => 'openemis_id_prefix',
                'type' => 'Auto Generated OpenEMIS ID',
                'label' => 'OpenEMIS ID Prefix',
                'value' => ',0',
                'default_value' => ',0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-12-09 10:47:52',
            ],
            [
                'id' => '1004',
                'name' => 'Webhooks',
                'code' => 'webhooks',
                'type' => 'Webhooks',
                'label' => 'Webhooks',
                'value' => '0',
                'default_value' => '0',
                'editable' => '1',
                'visible' => '1',
                'field_type' => '',
                'option_type' => '',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-03-20 11:43:54',
            ],
        ];

        $table = $this->table('config_items');
        $table->insert($data)->save();
    }
}
