<?php
use Migrations\AbstractSeed;

/**
 * ImportMappings seed.
 */
class ImportMappingSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'model' => 'Institution.Institutions',
                'column_name' => 'name',
                'description' => NULL,
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '2',
                'model' => 'Institution.Institutions',
                'column_name' => 'alternative_name',
                'description' => NULL,
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '3',
                'model' => 'Institution.Institutions',
                'column_name' => 'code',
                'description' => NULL,
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '4',
                'model' => 'Institution.Institutions',
                'column_name' => 'address',
                'description' => NULL,
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '5',
                'model' => 'Institution.Institutions',
                'column_name' => 'postal_code',
                'description' => NULL,
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '6',
                'model' => 'Institution.Institutions',
                'column_name' => 'contact_person',
                'description' => NULL,
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '7',
                'model' => 'Institution.Institutions',
                'column_name' => 'telephone',
                'description' => NULL,
                'order' => '7',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '8',
                'model' => 'Institution.Institutions',
                'column_name' => 'fax',
                'description' => NULL,
                'order' => '8',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '9',
                'model' => 'Institution.Institutions',
                'column_name' => 'email',
                'description' => NULL,
                'order' => '9',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '10',
                'model' => 'Institution.Institutions',
                'column_name' => 'date_opened',
                'description' => '( DD/MM/YYYY )',
                'order' => '11',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '11',
                'model' => 'Institution.Institutions',
                'column_name' => 'date_closed',
                'description' => '( DD/MM/YYYY )',
                'order' => '12',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '12',
                'model' => 'Institution.Institutions',
                'column_name' => 'longitude',
                'description' => NULL,
                'order' => '13',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '13',
                'model' => 'Institution.Institutions',
                'column_name' => 'website',
                'description' => NULL,
                'order' => '10',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '14',
                'model' => 'Institution.Institutions',
                'column_name' => 'latitude',
                'description' => NULL,
                'order' => '14',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '15',
                'model' => 'Institution.Institutions',
                'column_name' => 'area_id',
                'description' => 'Education Code',
                'order' => '15',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'Areas',
                'lookup_column' => 'code',
            ],
            [
                'id' => '16',
                'model' => 'Institution.Institutions',
                'column_name' => 'area_administrative_id',
                'description' => 'Code',
                'order' => '16',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '17',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_locality_id',
                'description' => 'Code',
                'order' => '17',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'Localities',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '18',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_type_id',
                'description' => 'Code',
                'order' => '18',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'Types',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '19',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_ownership_id',
                'description' => 'Code',
                'order' => '19',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'Ownerships',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '20',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_sector_id',
                'description' => 'Code',
                'order' => '20',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'Sectors',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '21',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_provider_id',
                'description' => 'Code',
                'order' => '21',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'Providers',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '22',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_gender_id',
                'description' => 'Code',
                'order' => '22',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'Genders',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '23',
                'model' => 'Institution.Institutions',
                'column_name' => 'institution_network_connectivity_id',
                'description' => 'Code',
                'order' => '23',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'NetworkConnectivities',
                'lookup_column' => 'id',
            ],
            [
                'id' => '25',
                'model' => 'Student.Students',
                'column_name' => 'openemis_no',
                'description' => '(Leave as blank for new entries)',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '26',
                'model' => 'Student.Students',
                'column_name' => 'first_name',
                'description' => NULL,
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '27',
                'model' => 'Student.Students',
                'column_name' => 'middle_name',
                'description' => NULL,
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '28',
                'model' => 'Student.Students',
                'column_name' => 'third_name',
                'description' => NULL,
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '29',
                'model' => 'Student.Students',
                'column_name' => 'last_name',
                'description' => NULL,
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '30',
                'model' => 'Student.Students',
                'column_name' => 'preferred_name',
                'description' => NULL,
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '31',
                'model' => 'Student.Students',
                'column_name' => 'gender_id',
                'description' => 'Code (M/F)',
                'order' => '7',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'User',
                'lookup_model' => 'Genders',
                'lookup_column' => 'code',
            ],
            [
                'id' => '32',
                'model' => 'Student.Students',
                'column_name' => 'date_of_birth',
                'description' => '( DD/MM/YYYY )',
                'order' => '8',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '33',
                'model' => 'Student.Students',
                'column_name' => 'address',
                'description' => NULL,
                'order' => '9',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '34',
                'model' => 'Student.Students',
                'column_name' => 'postal_code',
                'description' => NULL,
                'order' => '10',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '35',
                'model' => 'Student.Students',
                'column_name' => 'address_area_id',
                'description' => 'Code',
                'order' => '11',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '36',
                'model' => 'Student.Students',
                'column_name' => 'birthplace_area_id',
                'description' => 'Code',
                'order' => '12',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '37',
                'model' => 'Student.Students',
                'column_name' => 'is_student',
                'description' => '(Leave this blank)',
                'order' => '13',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '38',
                'model' => 'Staff.Staff',
                'column_name' => 'openemis_no',
                'description' => '(Leave as blank for new entries)',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '39',
                'model' => 'Staff.Staff',
                'column_name' => 'first_name',
                'description' => NULL,
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '40',
                'model' => 'Staff.Staff',
                'column_name' => 'middle_name',
                'description' => NULL,
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '41',
                'model' => 'Staff.Staff',
                'column_name' => 'third_name',
                'description' => NULL,
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '42',
                'model' => 'Staff.Staff',
                'column_name' => 'last_name',
                'description' => NULL,
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '43',
                'model' => 'Staff.Staff',
                'column_name' => 'preferred_name',
                'description' => NULL,
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '44',
                'model' => 'Staff.Staff',
                'column_name' => 'gender_id',
                'description' => 'Code (M/F)',
                'order' => '7',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'User',
                'lookup_model' => 'Genders',
                'lookup_column' => 'code',
            ],
            [
                'id' => '45',
                'model' => 'Staff.Staff',
                'column_name' => 'date_of_birth',
                'description' => '( DD/MM/YYYY )',
                'order' => '8',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '46',
                'model' => 'Staff.Staff',
                'column_name' => 'address',
                'description' => NULL,
                'order' => '9',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '47',
                'model' => 'Staff.Staff',
                'column_name' => 'postal_code',
                'description' => NULL,
                'order' => '10',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '48',
                'model' => 'Staff.Staff',
                'column_name' => 'address_area_id',
                'description' => 'Code',
                'order' => '11',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '49',
                'model' => 'Staff.Staff',
                'column_name' => 'birthplace_area_id',
                'description' => 'Code',
                'order' => '12',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '50',
                'model' => 'Staff.Staff',
                'column_name' => 'is_staff',
                'description' => '(Leave this blank)',
                'order' => '13',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '51',
                'model' => 'Institution.StaffAbsences',
                'column_name' => 'start_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '52',
                'model' => 'Institution.StaffAbsences',
                'column_name' => 'end_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '53',
                'model' => 'Institution.StaffAbsences',
                'column_name' => 'comment',
                'description' => '',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '54',
                'model' => 'Institution.StaffAbsences',
                'column_name' => 'staff_id',
                'description' => 'OpenEMIS ID',
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Security',
                'lookup_model' => 'Users',
                'lookup_column' => 'openemis_no',
            ],
            [
                'id' => '55',
                'model' => 'Institution.StaffAbsences',
                'column_name' => 'staff_absence_reason_id',
                'description' => 'Code',
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'StaffAbsenceReasons',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '56',
                'model' => 'Institution.InstitutionStudentAbsences',
                'column_name' => 'start_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '57',
                'model' => 'Institution.InstitutionStudentAbsences',
                'column_name' => 'end_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '58',
                'model' => 'Institution.InstitutionStudentAbsences',
                'column_name' => 'comment',
                'description' => '',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '59',
                'model' => 'Institution.InstitutionStudentAbsences',
                'column_name' => 'student_id',
                'description' => 'OpenEMIS ID',
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Security',
                'lookup_model' => 'Users',
                'lookup_column' => 'openemis_no',
            ],
            [
                'id' => '60',
                'model' => 'Institution.InstitutionStudentAbsences',
                'column_name' => 'student_absence_reason_id',
                'description' => 'Code',
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'StudentAbsenceReasons',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '61',
                'model' => 'Institution.InstitutionSurveys',
                'column_name' => 'survey_form_id',
                'description' => '',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Survey',
                'lookup_model' => 'SurveyForms',
                'lookup_column' => 'id',
            ],
            [
                'id' => '62',
                'model' => 'Institution.Students',
                'column_name' => 'academic_period_id',
                'description' => 'Code',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'AcademicPeriod',
                'lookup_model' => 'AcademicPeriods',
                'lookup_column' => 'code',
            ],
            [
                'id' => '63',
                'model' => 'Institution.Students',
                'column_name' => 'education_grade_id',
                'description' => 'Code',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Education',
                'lookup_model' => 'EducationGrades',
                'lookup_column' => 'code',
            ],
            [
                'id' => '64',
                'model' => 'Institution.Students',
                'column_name' => 'start_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '65',
                'model' => 'Institution.Students',
                'column_name' => 'student_id',
                'description' => 'OpenEMIS ID',
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'StudentUser',
                'lookup_column' => 'openemis_no',
            ],
            [
                'id' => '66',
                'model' => 'Institution.Students',
                'column_name' => 'class',
                'description' => 'Code (Optional)',
                'order' => '5',
                'is_optional' => '1',
                'foreign_key' => '2',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'InstitutionClasses',
                'lookup_column' => 'id',
            ],
            [
                'id' => '67',
                'model' => 'User.Users',
                'column_name' => 'openemis_no',
                'description' => '(Leave as blank for new entries)',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '68',
                'model' => 'User.Users',
                'column_name' => 'first_name',
                'description' => NULL,
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '69',
                'model' => 'User.Users',
                'column_name' => 'middle_name',
                'description' => NULL,
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '70',
                'model' => 'User.Users',
                'column_name' => 'third_name',
                'description' => NULL,
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '71',
                'model' => 'User.Users',
                'column_name' => 'last_name',
                'description' => NULL,
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '72',
                'model' => 'User.Users',
                'column_name' => 'preferred_name',
                'description' => NULL,
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '73',
                'model' => 'User.Users',
                'column_name' => 'gender_id',
                'description' => 'Code (M/F)',
                'order' => '7',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'User',
                'lookup_model' => 'Genders',
                'lookup_column' => 'code',
            ],
            [
                'id' => '74',
                'model' => 'User.Users',
                'column_name' => 'date_of_birth',
                'description' => '( DD/MM/YYYY )',
                'order' => '8',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '75',
                'model' => 'User.Users',
                'column_name' => 'address',
                'description' => NULL,
                'order' => '9',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '76',
                'model' => 'User.Users',
                'column_name' => 'postal_code',
                'description' => NULL,
                'order' => '10',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '77',
                'model' => 'User.Users',
                'column_name' => 'address_area_id',
                'description' => 'Code',
                'order' => '11',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '78',
                'model' => 'User.Users',
                'column_name' => 'birthplace_area_id',
                'description' => 'Code',
                'order' => '12',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Area',
                'lookup_model' => 'AreaAdministratives',
                'lookup_column' => 'code',
            ],
            [
                'id' => '79',
                'model' => 'User.Users',
                'column_name' => 'account_type',
                'description' => 'Code',
                'order' => '13',
                'is_optional' => '0',
                'foreign_key' => '3',
                'lookup_plugin' => NULL,
                'lookup_model' => 'AccountTypes',
                'lookup_column' => 'code',
            ],
            [
                'id' => '81',
                'model' => 'Institution.Staff',
                'column_name' => 'institution_position_id',
                'description' => 'Code',
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'InstitutionPositions',
                'lookup_column' => 'position_no',
            ],
            [
                'id' => '82',
                'model' => 'Institution.Staff',
                'column_name' => 'start_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '83',
                'model' => 'Institution.Staff',
                'column_name' => 'position_type',
                'description' => 'Code',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '3',
                'lookup_plugin' => NULL,
                'lookup_model' => 'PositionTypes',
                'lookup_column' => 'id',
            ],
            [
                'id' => '84',
                'model' => 'Institution.Staff',
                'column_name' => 'FTE',
                'description' => '(Not Required if Position Type is Full Time)',
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '3',
                'lookup_plugin' => NULL,
                'lookup_model' => 'FTE',
                'lookup_column' => 'value',
            ],
            [
                'id' => '85',
                'model' => 'Institution.Staff',
                'column_name' => 'staff_type_id',
                'description' => 'Code',
                'order' => '6',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Staff',
                'lookup_model' => 'StaffTypes',
                'lookup_column' => 'code',
            ],
            [
                'id' => '86',
                'model' => 'Institution.Staff',
                'column_name' => 'staff_id',
                'description' => 'OpenEMIS ID',
                'order' => '7',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Staff',
                'lookup_model' => 'Staff',
                'lookup_column' => 'openemis_no',
            ],
            [
                'id' => '87',
                'model' => 'Institution.StaffAbsences',
                'column_name' => 'absence_type_id',
                'description' => 'Code',
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'AbsenceTypes',
                'lookup_column' => 'code',
            ],
            [
                'id' => '88',
                'model' => 'Institution.InstitutionStudentAbsences',
                'column_name' => 'absence_type_id',
                'description' => 'Code',
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Institution',
                'lookup_model' => 'AbsenceTypes',
                'lookup_column' => 'code',
            ],
            [
                'id' => '89',
                'model' => 'Institution.Staff',
                'column_name' => 'end_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '91',
                'model' => 'Examination.ExaminationItemResults',
                'column_name' => 'examination_id',
                'description' => 'Id',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Examination',
                'lookup_model' => 'Examinations',
                'lookup_column' => 'id',
            ],
            [
                'id' => '93',
                'model' => 'Examination.ExaminationItemResults',
                'column_name' => 'examination_item_id',
                'description' => 'Id',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Examination',
                'lookup_model' => 'ExaminationItems',
                'lookup_column' => 'id',
            ],
            [
                'id' => '94',
                'model' => 'Examination.ExaminationItemResults',
                'column_name' => 'student_id',
                'description' => 'OpenEMIS ID',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Security',
                'lookup_model' => 'Users',
                'lookup_column' => 'openemis_no',
            ],
            [
                'id' => '96',
                'model' => 'Examination.ExaminationItemResults',
                'column_name' => 'marks',
                'description' => '(Leave as blank for Grades type)',
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '97',
                'model' => 'Examination.ExaminationItemResults',
                'column_name' => 'examination_grading_option_id',
                'description' => 'Id (Leave as blank for Marks type)',
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Examination',
                'lookup_model' => 'ExaminationGradingOptions',
                'lookup_column' => 'id',
            ],
            [
                'id' => '98',
                'model' => 'Institution.InstitutionTextbooks',
                'column_name' => 'textbook_id',
                'description' => NULL,
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Textbook',
                'lookup_model' => 'Textbooks',
                'lookup_column' => 'id',
            ],
            [
                'id' => '99',
                'model' => 'Institution.InstitutionTextbooks',
                'column_name' => 'student_id',
                'description' => 'OpenEMIS ID',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Security',
                'lookup_model' => 'Users',
                'lookup_column' => 'openemis_no',
            ],
            [
                'id' => '100',
                'model' => 'Institution.InstitutionTextbooks',
                'column_name' => 'code',
                'description' => NULL,
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '101',
                'model' => 'Institution.InstitutionTextbooks',
                'column_name' => 'textbook_status_id',
                'description' => 'Code',
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Textbook',
                'lookup_model' => 'TextbookStatuses',
                'lookup_column' => 'code',
            ],
            [
                'id' => '102',
                'model' => 'Institution.InstitutionTextbooks',
                'column_name' => 'textbook_condition_id',
                'description' => 'Code',
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '1',
                'lookup_plugin' => 'Textbook',
                'lookup_model' => 'TextbookConditions',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '103',
                'model' => 'Institution.InstitutionTextbooks',
                'column_name' => 'comment',
                'description' => '(Optional)',
                'order' => '6',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '105',
                'model' => 'Examination.ExaminationCentreRooms',
                'column_name' => 'examination_centre_id',
                'description' => 'ID',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Examination',
                'lookup_model' => 'ExaminationCentres',
                'lookup_column' => 'id',
            ],
            [
                'id' => '106',
                'model' => 'Examination.ExaminationCentreRooms',
                'column_name' => 'name',
                'description' => '',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '107',
                'model' => 'Examination.ExaminationCentreRooms',
                'column_name' => 'size',
                'description' => '(Optional)',
                'order' => '3',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '108',
                'model' => 'Examination.ExaminationCentreRooms',
                'column_name' => 'number_of_seats',
                'description' => '(Optional)',
                'order' => '4',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '109',
                'model' => 'User.Users',
                'column_name' => 'nationality_id',
                'description' => 'Id (Optional)',
                'order' => '14',
                'is_optional' => '1',
                'foreign_key' => '2',
                'lookup_plugin' => 'FieldOption',
                'lookup_model' => 'Nationalities',
                'lookup_column' => 'id',
            ],
            [
                'id' => '110',
                'model' => 'User.Users',
                'column_name' => 'identity_type_id',
                'description' => 'Code (Optional)',
                'order' => '15',
                'is_optional' => '1',
                'foreign_key' => '1',
                'lookup_plugin' => 'FieldOption',
                'lookup_model' => 'IdentityTypes',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '111',
                'model' => 'User.Users',
                'column_name' => 'identity_number',
                'description' => '',
                'order' => '16',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '112',
                'model' => 'Staff.Salaries',
                'column_name' => 'salary_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '113',
                'model' => 'Staff.Salaries',
                'column_name' => 'comment',
                'description' => '(Optional)',
                'order' => '2',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '114',
                'model' => 'Staff.Salaries',
                'column_name' => 'gross_salary',
                'description' => NULL,
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '115',
                'model' => 'Training.TrainingSessionsTrainees',
                'column_name' => 'identity_number',
                'description' => '',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '116',
                'model' => 'Training.TrainingSessionsTrainees',
                'column_name' => 'identity_type_id',
                'description' => 'Code',
                'order' => '2',
                'is_optional' => '1',
                'foreign_key' => '1',
                'lookup_plugin' => 'FieldOption',
                'lookup_model' => 'IdentityTypes',
                'lookup_column' => 'national_code',
            ],
            [
                'id' => '117',
                'model' => 'Training.TrainingSessionsTrainees',
                'column_name' => 'openemis_no',
                'description' => NULL,
                'order' => '1',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '118',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'academic_period_id',
                'description' => 'Code',
                'order' => '1',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'AcademicPeriod',
                'lookup_model' => 'AcademicPeriods',
                'lookup_column' => 'code',
            ],
            [
                'id' => '119',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'education_grade_id',
                'description' => 'Code',
                'order' => '2',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Education',
                'lookup_model' => 'EducationGrades',
                'lookup_column' => 'code',
            ],
            [
                'id' => '120',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'education_subject_id',
                'description' => 'Code',
                'order' => '3',
                'is_optional' => '0',
                'foreign_key' => '2',
                'lookup_plugin' => 'Education',
                'lookup_model' => 'EducationSubjects',
                'lookup_column' => 'code',
            ],
            [
                'id' => '121',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'code',
                'description' => NULL,
                'order' => '4',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '122',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'title',
                'description' => NULL,
                'order' => '5',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '123',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'author',
                'description' => NULL,
                'order' => '6',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '124',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'publisher',
                'description' => NULL,
                'order' => '7',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '125',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'year_published',
                'description' => '( YYYY )',
                'order' => '8',
                'is_optional' => '0',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '126',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'ISBN',
                'description' => NULL,
                'order' => '9',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
            [
                'id' => '127',
                'model' => 'Textbook.Textbooks',
                'column_name' => 'expiry_date',
                'description' => '( DD/MM/YYYY )',
                'order' => '10',
                'is_optional' => '1',
                'foreign_key' => '0',
                'lookup_plugin' => NULL,
                'lookup_model' => NULL,
                'lookup_column' => NULL,
            ],
        ];

        $table = $this->table('import_mapping');
        $table->insert($data)->save();
    }
}
