<?php

use Cake\I18n\Date;
use Cake\ORM\TableRegistry;
use Phinx\Migration\AbstractMigration;
use Cake\Utility\Hash;

class POCOR4976 extends AbstractMigration
{
    public function up()
    {
        $this->execute('ALTER TABLE `special_need_types` ADD `type` TINYINT NOT NULL COMMENT '1- Special need type , 2- special need assessment type' AFTER `international_code`');
        // backup 
        $this->execute('CREATE TABLE `z_4976_special_need_types` LIKE `special_need_types`');
        $this->execute('INSERT INTO `z_4976_special_need_types` SELECT * FROM `special_need_types`');
		$specialNeedTypeData = [
            [
                'id' => 623,
                'name' => 'Not performing according to benchmarks for chronol',
                'order' => 1,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:35:59'
            ],
            [
                'id' => 624,
                'name' => 'Low grades across subject areas ',
                'order' => 2,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:36:29'
            ],
			[
                'id' => 625,
                'name' => 'Inappropriate behaviour',
                'order' => 3,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:36:45'
            ],
			[
                'id' => 626,
                'name' => 'Visual/hearing problems',
                'order' => 4,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:36:59'
            ],
			[
                'id' => 627,
                'name' => 'Special arrangements',
                'order' => 5,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:37:12'
            ],
			[
                'id' => 628,
                'name' => 'Not coping in school',
                'order' => 6,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:37:25'
            ],
			[
                'id' => 629,
                'name' => 'Causing danger to himself and others',
                'order' => 7,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:37:36'
            ],
			[
                'id' => 630,
                'name' => 'Disruptive behaviour ',
                'order' => 8,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:37:36'
            ],
			[
                'id' => 631,
                'name' => 'Lacks Communication',
                'order' => 9,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 1,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 08:37:36'
            ],
			[
                'id' => 632,
                'name' => 'WISC',
                'order' => 1,
				'visible' => 1,
				'editable' => 1,
				'default' => 1,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:36:56'
            ],
            [
                'id' => 633,
                'name' => 'Mico Diagnostic Test',
                'order' => 2,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:37:13'
            ],
            [
                'id' => 634,
                'name' => 'Phonic Test',
                'order' => 3,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:37:31'
            ],
            [
                'id' => 635,
                'name' => 'TONI',
                'order' => 4,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:37:38'
            ],
            [
                'id' => 636,
                'name' => 'Peabody',
                'order' => 5,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:37:46'
            ],
            [
                'id' => 637,
                'name' => 'Peabody',
                'order' => 6,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:37:53'
            ],
            [
                'id' => 638,
                'name' => 'Test of Written Spelling',
                'order' => 7,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:38:04'
            ],
            [
                'id' => 639,
                'name' => 'NaRCIE Math',
                'order' => 8,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:38:18'
            ],
            [
                'id' => 640,
                'name' => 'Test for children with developmental delay or Seve',
                'order' => 9,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:38:30'
            ],
            [
                'id' => 641,
                'name' => 'Hearing Test',
                'order' => 10,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:38:39'
            ],
            [
                'id' => 642,
                'name' => 'Vision Test',
                'order' => 11,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:38:47'
            ],
            [
                'id' => 643,
                'name' => 'Denver',
                'order' => 12,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:38:56'
            ],
            [
                'id' => 644,
                'name' => 'Informal Test',
                'order' => 13,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:39:05'
            ],
            [
                'id' => 645,
                'name' => 'Mansuiter Auditory and Visual Memory',
                'order' => 14,
				'visible' => 1,
				'editable' => 1,
				'default' => 0,
				'international_code' => '',
				'type' => 2,
				'national_code' => '',
				'modified_user_id' => null,
				'modified' => null,
				'created_user_id' => 2,
				'created' => '2019-06-18 07:39:14'
            ]
			];
			
			$this->insert('special_need_types', $specialNeedTypeData);
			
    }

    public function down()
    {
    }
}
