<?php

declare(strict_types=1);

use Migrations\AbstractMigration;

class POCOR8278 extends AbstractMigration
{
    public function up()
    {
        // Update table descriptions/comments directly
        $tableDescriptions = [
            'api_scopes' => 'Defines the scopes and permissions for API access',
            'api_securities' => 'Stores security configurations and access controls for the API',
            'assessment_item_results_archived' => 'Archives of previous student assessment item results',
            'assessment_period_excluded_security_roles' => 'Security roles excluded from certain assessment periods',
            'backup_logs' => 'Records of database backup operations and their statuses',
            'budget_types' => 'Types of budgets used for school finances',
            'case_priorities' => 'Priority levels for different cases or incidents',
            'case_types' => 'Categories of cases or incidents handled within the system',
            'class_profile_processes' => 'Processes related to class profile generation and management',
            'class_profile_templates' => 'Templates used for creating and formatting class profiles',
            'class_profiles' => 'Profiles and information about classes',
            'curricular_positions' => 'Teaching or administrative positions related to curriculum',
            'curricular_types' => 'Types of curricula',
            'data_dictionary' => 'System metadata describing database fields and their meanings',
            'data_management_connections' => 'Connection settings for data management operations',
            'data_management_copy' => 'Records of data copying operations between system components',
            'data_management_logs' => 'Logs of data management activities and operations',
            'examination_student_subjects' => 'Links between students, examinations, and subjects',
            'expenditure_types' => 'Categories of expenditures for financial reporting',
            'field_options' => 'Configurable options for various system fields',
            'food_types' => 'Types of food items used in school meal programs',
            'income_sources' => 'Sources of income for institutions',
            'income_types' => 'Categories of income for financial management purposes',
            'industries' => 'Industry sectors related to vocational education programs',
            'institution_attachment_types' => 'Types of attachments for institution records',
            'institution_budgets' => 'Budget records for institutions',
            'institution_case_comments' => 'Comments related to institution cases or incidents',
            'institution_case_links' => 'Links between institution cases and other system entities',
            'institution_committee_meeting' => 'Records of committee meetings at institutions',
            'institution_courses' => 'Courses offered by specific educational institutions',
            'institution_curricular_staff' => 'Staff assigned to curricula at specific institutions',
            'institution_curricular_students' => 'Students enrolled in curricula at specific institutions',
            'institution_curriculars' => 'Curriculum information specific to institutions',
            'institution_expenditures' => 'Expenditure records for educational institutions',
            'institution_incomes' => 'Income records for educational institutions',
            'institution_report_card_processes' => 'Processes for generating institution report cards',
            'institution_report_cards' => 'Report cards for educational institutions',
            'institution_shift_periods' => 'Time periods for different shifts at institutions',
            'institution_staff_leave_archived' => 'Archives of staff leave records at institutions',
            'institution_staff_shifts' => 'Staff shift assignments at educational institutions',
            'institution_staff_survey_answers' => 'Staff responses to surveys at institutions',
            'institution_staff_survey_table_cells' => 'Table cell data from staff surveys',
            'institution_staff_surveys' => 'Surveys questions related to staff at institutions',
            'institution_student_absence_days' => 'Records of student absences by day',
            'institution_units' => 'Consumable units within educational institutions',
            'meal_food_records' => 'Records of food items used in school meals',
            'meal_implementers' => 'Organizations/staff implementing meal programs',
            'meal_institution_programmes' => 'Meal programs specific to institutions',
            'meal_nutritions' => 'Nutritional information for school meals',
            'meal_programme_types' => 'Types of meal programs',
            'meal_ratings' => 'Quality ratings for school meals',
            'meal_status_types' => 'Status categories for meal programs',
            'meal_target_types' => 'Target groups for meal programs',
            'message_recipients' => 'Recipients of system messages and notifications',
            'messaging' => 'System messages and communications',
            'messaging_security_roles' => 'Security roles for messaging functions',
            'openemis_temps' => 'Temporary data storage for system operations',
            'phinxlog' => 'Migration tracking for Phinx database migrations',
            'profile_templates' => 'Templates for various system profiles',
            'report_card_excluded_security_roles' => 'Security roles excluded from report card access',
            'report_queries' => 'Stored queries for system reports',
            'report_student_assessment_summary' => 'Summary statistics of student assessment results for reports',
            'report_student_attendance_summary' => 'Summary statistics of student attendance for reports',
            'scholarship_financial_assistances' => 'Records of financial aid and scholarships',
            'staff_attachment_types' => 'Types of attachments for staff records',
            'staff_employment_statuses' => 'Employment status categories for staff',
            'staff_position_categories' => 'Categories of staff positions',
            'staff_profile_templates' => 'Templates for staff profiles',
            'staff_report_card_email_processes' => 'Processes for emailing staff report cards',
            'staff_report_card_processes' => 'Processes for generating staff report cards',
            'staff_report_cards' => 'Report cards for staff performance',
            'student_attachment_types' => 'Types of attachments for student records',
            'student_attendance_per_day_periods' => 'Student attendance records by day and period',
            'student_behaviour_classifications' => 'Categories for classifying student behavior',
            'student_mark_type_status_grades' => 'Grade levels for student mark status types',
            'student_mark_type_statuses' => 'Status categories for student marks',
            'student_profile_security_roles' => 'Security roles for student profile access',
            'student_profile_templates' => 'Templates for student profiles',
            'student_report_card_email_processes' => 'Processes for emailing student report cards',
            'student_report_card_processes' => 'Processes for generating student report cards',
            'student_report_cards' => 'Report cards for student academic performance',
            'summary_area_institution_grade_attendances' => 'Summary statistics of attendance by area, institution, and grade',
            'summary_area_provider_grade_subject_results' => 'Summary statistics of subject results by area, provider, and grade',
            'summary_assessment_item_results' => 'Summary statistics of assessment item results',
            'summary_grade_gender_ages' => 'Summary statistics by grade, gender, and age',
            'summary_grade_status_genders' => 'Summary statistics by grade status and gender',
            'summary_institution_grade_nationalities' => 'Summary statistics of nationalities by institution and grade',
            'summary_institution_grades' => 'Summary statistics by institution and grade',
            'summary_institution_nationalities' => 'Summary statistics of nationalities by institution',
            'summary_institution_room_types' => 'Summary statistics of room types by institution',
            'summary_institution_student_absences' => 'Summary statistics of student absences by institution',
            'summary_institution_student_subject_results' => 'Summary statistics of student subject results by institution',
            'summary_institutions' => 'Summary statistics for institutions',
            'summary_isced_sectors' => 'Summary statistics by ISCED sectors',
            'summary_programme_sector_genders' => 'Summary statistics by program sector and gender',
            'summary_programme_sector_qualification_genders' => 'Summary statistics by program sector, qualification, and gender',
            'summary_programme_sector_specialization_genders' => 'Summary statistics by program sector, specialization, and gender',
            'survey_filter_areas' => 'Area filters for system surveys',
            'survey_filter_institution_providers' => 'Institution provider filters for surveys',
            'survey_filter_institution_types' => 'Institution type filters for surveys',
            'textbook_dimensions' => 'Dimensions and properties of textbooks',
            'themes' => 'Visual and UI themes for the system',
            'training_need_competencies' => 'Competencies addressed by training programs',
            'training_need_standards' => 'Standards for assessing training needs',
            'training_need_sub_standards' => 'Sub-standards for detailed training needs assessment',
            'training_session_evaluators' => 'Evaluators assigned to training sessions',
            'transfer_logs' => 'Records of data transfers within the system',
            'user_demographics' => 'Demographic information about system users',
            'user_employments' => 'Employment information for system users'
        ];

        foreach ($tableDescriptions as $tableName => $description) {
            $result = $this->query("SHOW TABLES LIKE '$tableName'")->fetch();
            if ($result) {
                $safeDescription = addslashes($description);
                $this->execute("
                        ALTER TABLE `$tableName` 
                        COMMENT = '$safeDescription'
                    ");
            }
        }
    }

    public function down()
    {
        // List of tables to clear comments from
        $tables = [
            'api_scopes',
            'api_securities',
            'assessment_item_results_archived',
            'assessment_period_excluded_security_roles',
            'backup_logs',
            'budget_types',
            'case_priorities',
            'case_types',
            'class_profile_processes',
            'class_profile_templates',
            'class_profiles',
            'curricular_positions',
            'curricular_types',
            'data_dictionary',
            'data_management_connections',
            'data_management_copy',
            'data_management_logs',
            'examination_student_subjects',
            'expenditure_types',
            'field_options',
            'food_types',
            'income_sources',
            'income_types',
            'industries',
            'institution_attachment_types',
            'institution_budgets',
            'institution_case_comments',
            'institution_case_links',
            'institution_committee_meeting',
            'institution_courses',
            'institution_curricular_staff',
            'institution_curricular_students',
            'institution_curriculars',
            'institution_expenditures',
            'institution_incomes',
            'institution_report_card_processes',
            'institution_report_cards',
            'institution_shift_periods',
            'institution_staff_leave_archived',
            'institution_staff_shifts',
            'institution_staff_survey_answers',
            'institution_staff_survey_table_cells',
            'institution_staff_surveys',
            'institution_student_absence_days',
            'institution_units',
            'meal_food_records',
            'meal_implementers',
            'meal_institution_programmes',
            'meal_nutritions',
            'meal_programme_types',
            'meal_ratings',
            'meal_status_types',
            'meal_target_types',
            'message_recipients',
            'messaging',
            'messaging_security_roles',
            'openemis_temps',
            'phinxlog',
            'profile_templates',
            'report_card_excluded_security_roles',
            'report_queries',
            'report_student_assessment_summary',
            'report_student_attendance_summary',
            'scholarship_financial_assistances',
            'staff_attachment_types',
            'staff_employment_statuses',
            'staff_position_categories',
            'staff_profile_templates',
            'staff_report_card_email_processes',
            'staff_report_card_processes',
            'staff_report_cards',
            'student_attachment_types',
            'student_attendance_per_day_periods',
            'student_behaviour_classifications',
            'student_mark_type_status_grades',
            'student_mark_type_statuses',
            'student_profile_security_roles',
            'student_profile_templates',
            'student_report_card_email_processes',
            'student_report_card_processes',
            'student_report_cards',
            'summary_area_institution_grade_attendances',
            'summary_area_provider_grade_subject_results',
            'summary_assessment_item_results',
            'summary_grade_gender_ages',
            'summary_grade_status_genders',
            'summary_institution_grade_nationalities',
            'summary_institution_grades',
            'summary_institution_nationalities',
            'summary_institution_room_types',
            'summary_institution_student_absences',
            'summary_institution_student_subject_results',
            'summary_institutions',
            'summary_isced_sectors',
            'summary_programme_sector_genders',
            'summary_programme_sector_qualification_genders',
            'summary_programme_sector_specialization_genders',
            'survey_filter_areas',
            'survey_filter_institution_providers',
            'survey_filter_institution_types',
            'textbook_dimensions',
            'themes',
            'training_need_competencies',
            'training_need_standards',
            'training_need_sub_standards',
            'training_session_evaluators',
            'transfer_logs',
            'user_demographics',
            'user_employments'
        ];

        // Clear table comments
        foreach ($tables as $tableName) {
            $result = $this->query("SHOW TABLES LIKE '$tableName'")->fetch();
            if ($result) {
                $this->execute("ALTER TABLE `$tableName` COMMENT = ''");
            }
        }
    }
}
