<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\DirectoryService;
use Illuminate\Support\Facades\Log;

class DirectoryController extends Controller
{
    protected $directoryService;

    public function __construct(DirectoryService $directoryService) 
    {
        $this->directoryService = $directoryService;
    }


    //For POCOR-8104 Start...
    public function getUserTypeList(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getUserTypeList($params);
            return $this->sendSuccessResponse("User Type List Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Type List Not Found');
        }
    }


    public function getUniqueOpenemisId(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getUniqueOpenemisId($params);
            return $this->sendSuccessResponse("Openemis Id Generated.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Openemis Id.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Openemis Id.');
        }
    }


    public function getAutoGeneratedPassword(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getAutoGeneratedPassword($params);
            
            if(is_array($data)){
                return $this->sendSuccessResponse("Password is generated.", $data);
            }


            if($data == 1){
                return $this->sendErrorResponse('Argument(s) not an integer.');
            } else if($data == 2){
                return $this->sendErrorResponse('Argument(s) not an integer.');
            } else if($data == 3){
                return $this->sendErrorResponse('Number of password capitals required exceeds password length.');
            } else if($data == 4){
                return $this->sendErrorResponse('Number of password numerals exceeds password length.');
            } else if($data == 5){
                return $this->sendErrorResponse('Number of password capitals exceeds password length.');
            } else if($data == 6){
                return $this->sendErrorResponse('Number of password special characters exceeds specified password length.');
            }
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Password.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Password.');
        }
    }



    public function getContactTypes(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getContactTypes($params);
            return $this->sendSuccessResponse("Contact Type List Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Contact Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Contact Type List Not Found');
        }
    }



    public function getStaffCustomFields(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getStaffCustomFields($params);
            return $this->sendSuccessResponse("Staff Custom Fields List Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Staff Custom Fields List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Staff Custom Fields List Not Found');
        }
    }


    public function getPositionsType(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getPositionsType($params);
            return $this->sendSuccessResponse("Position Type List Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Position Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Position Type List Not Found');
        }
    }


    public function getFTE(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getFTE($params);
            return $this->sendSuccessResponse("FTE List Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch FTE List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('FTE List Not Found');
        }
    }



    public function getSystemConfigData(Request $request, $configId)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getSystemConfigData($params, $configId);
            return $this->sendSuccessResponse("System Configuration Data Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch System Configuration Data from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('System Configuration Data Not Found');
        }
    }

    //For POCOR-8104 End...
}
