<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\DirectoryService;
use Illuminate\Support\Facades\Log;

class DirectoryController extends Controller
{
    protected $directoryService;

    public function __construct(DirectoryService $directoryService) 
    {
        $this->directoryService = $directoryService;
    }


    //For POCOR-8104 Start...
    public function getUserTypeList(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getUserTypeList($params);
            return $this->sendSuccessResponse("User Type List Found.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Type List Not Found');
        }
    }


    public function getUniqueOpenemisId(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getUniqueOpenemisId($params);
            return $this->sendSuccessResponse("Openemis Id Generated.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Openemis Id.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Openemis Id.');
        }
    }


    public function getAutoGeneratedPassword(Request $request)
    {
        try {
            $params = $request->all();
            $data = $this->directoryService->getAutoGeneratedPassword($params);
            return $this->sendSuccessResponse("Password generated successfully.", $data);
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Password.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Password.');
        }
    }

    //For POCOR-8104 End...
}
