-- Need to update field_options and field_option_values
CREATE TABLE IF NOT EXISTS 1136_field_options LIKE field_options;
INSERT 1136_field_options SELECT * FROM field_options WHERE NOT EXISTS (SELECT * FROM 1136_field_options);
CREATE TABLE IF NOT EXISTS 1136_field_option_values LIKE field_option_values;
INSERT 1136_field_option_values SELECT * FROM field_option_values WHERE NOT EXISTS (SELECT * FROM 1136_field_option_values);



-- Updating wrong model names
UPDATE `field_options` SET `code` = 'StaffPositionTitle' WHERE `field_options`.`code` = 'PositionTitle';

UPDATE `field_options` SET `code` = 'TrainingCourseResultType' WHERE `field_options`.`code` = 'TrainingResultType';

UPDATE `field_options` SET `code` = 'StaffPositionGrade' WHERE `field_options`.`code` = 'PositionGrade';

UPDATE `field_options` SET `code` = 'StaffPositionStep' WHERE `field_options`.`code` = 'PositionStep';

UPDATE `field_options` SET `code` = 'StaffPositionTitle' WHERE `field_options`.`code` = 'PositionTitle';


-- Removing nationality from config_item
DELETE FROM config_items WHERE config_items.type = 'Nationality' limit 1;


-- FIELD OPTIONS
-- https://docs.google.com/a/kordit.com/spreadsheets/d/1X0zyO6eOwu5wccNWMgKhi34HJyIMDJ_45oLYMe9hEN8/edit#gid=548941468
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteOwnership' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteLocality' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteStatus' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'AssessmentResultType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'EmploymentType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'ExtracurricularType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'Language' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'IdentityType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'LicenseType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'SpecialNeedType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'QualityVisitType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthRelationship' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthCondition' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthImmunization' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthAllergyType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthTestType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthConsultationType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'SalaryAdditionType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'SalaryDeductionType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingCourseType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingFieldStudy' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingLevel' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingModeDelivery' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingPriority' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingProvider' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingRequirement' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingStatus' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StudentCategory' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StudentBehaviourCategory' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StaffPositionTitle' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StaffPositionGrade' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StaffPositionStep' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'QualificationSpecialisation' LIMIT 1;




-- https://docs.google.com/a/kordit.com/spreadsheets/d/1X0zyO6eOwu5wccNWMgKhi34HJyIMDJ_45oLYMe9hEN8/edit#gid=1574144139
UPDATE field_option_values SET name='Government' WHERE 'id'='1';

UPDATE field_option_values SET name='Private' WHERE 'id'='28';

UPDATE field_option_values SET name='Public' WHERE 'id'='2';
UPDATE field_option_values SET name='Private' WHERE 'id'='30';
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Early Childhood', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Primary', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Secondary', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteOwnership';INSERT INTO field_option_values (name, field_option_id) VALUES ('Leasehold (State)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteOwnership';INSERT INTO field_option_values (name, field_option_id) VALUES ('Freehold', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteOwnership';INSERT INTO field_option_values (name, field_option_id) VALUES ('Customary (Non Disputed)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteOwnership';INSERT INTO field_option_values (name, field_option_id) VALUES ('Customary (Disputed)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteLocality';INSERT INTO field_option_values (name, field_option_id) VALUES ('Urban', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteLocality';INSERT INTO field_option_values (name, field_option_id) VALUES ('Rural', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteLocality';INSERT INTO field_option_values (name, field_option_id) VALUES ('Semi-Rural', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteLocality';INSERT INTO field_option_values (name, field_option_id) VALUES ('Semi-Urban', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Operating', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Suspended', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InstitutionSiteStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Closed', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceNature';INSERT INTO field_option_values (name, field_option_id) VALUES ('Capital Income', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceNature';INSERT INTO field_option_values (name, field_option_id) VALUES ('Capital Expenditure', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceNature';INSERT INTO field_option_values (name, field_option_id) VALUES ('Recurrent Income', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceNature';INSERT INTO field_option_values (name, field_option_id) VALUES ('Recurrent Expenditure', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceNature';INSERT INTO field_option_values (name, field_option_id) VALUES ('Other', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Instructional', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Support Services', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Facilities', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Other', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Donations', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Fund Raising', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Subsidies', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('School Fees', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Scholarship', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Salaries', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceSource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Government (National)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceSource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Government (Sub National)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceSource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Politician', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceSource';INSERT INTO field_option_values (name, field_option_id) VALUES ('NGO', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FinanceSource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Others', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'AssessmentResultType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Distinction', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'AssessmentResultType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Pass', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'AssessmentResultType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Fail', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ContactType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Mobile - Personal', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ContactType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Phone - Personal', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ContactType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Phone - Office', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ContactType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Email - Personal', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ContactType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Email - Work', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Appointment', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Probation', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Extension', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Increment', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Termination', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Resignation', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Retirement', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'EmploymentType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Contract End', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ExtracurricularType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Academic Club', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ExtracurricularType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Chess Club', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ExtracurricularType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Boys Brigade', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'ExtracurricularType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Scouts', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SchoolYear';INSERT INTO field_option_values (name, field_option_id) VALUES ('2014 - From 01/01/2014 to 31/12/2014', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SchoolYear';INSERT INTO field_option_values (name, field_option_id) VALUES ('2013 - From 01/01/2013 to 31/12/2013', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SchoolYear';INSERT INTO field_option_values (name, field_option_id) VALUES ('2012 - From 01/01/2012 to 31/12/2012', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'Language';INSERT INTO field_option_values (name, field_option_id) VALUES ('English', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'Language';INSERT INTO field_option_values (name, field_option_id) VALUES ('Chinese', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'Language';INSERT INTO field_option_values (name, field_option_id) VALUES ('Arabic', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'Language';INSERT INTO field_option_values (name, field_option_id) VALUES ('French', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'Language';INSERT INTO field_option_values (name, field_option_id) VALUES ('Spanish', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'Language';INSERT INTO field_option_values (name, field_option_id) VALUES ('Russian', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'IdentityType';INSERT INTO field_option_values (name, field_option_id) VALUES ('National', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'IdentityType';INSERT INTO field_option_values (name, field_option_id) VALUES ('School', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'IdentityType';INSERT INTO field_option_values (name, field_option_id) VALUES ('UNHCR', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'IdentityType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Passport', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'LicenseType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Car License', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'LicenseType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Motorcycle License', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SpecialNeedType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Visual', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SpecialNeedType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Intellectual', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SpecialNeedType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Autism', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SpecialNeedType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Hearing', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SpecialNeedType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Multiple', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualityVisitType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Inspection', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualityVisitType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Termly Quality Assuarance', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthRelationship';INSERT INTO field_option_values (name, field_option_id) VALUES ('Mother', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthRelationship';INSERT INTO field_option_values (name, field_option_id) VALUES ('Father', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthRelationship';INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandmother', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthRelationship';INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandfather', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthRelationship';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sister', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthRelationship';INSERT INTO field_option_values (name, field_option_id) VALUES ('Brother', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthCondition';INSERT INTO field_option_values (name, field_option_id) VALUES ('Asthma Attack', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthCondition';INSERT INTO field_option_values (name, field_option_id) VALUES ('Diabetes', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthCondition';INSERT INTO field_option_values (name, field_option_id) VALUES ('Tubercolosis', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthCondition';INSERT INTO field_option_values (name, field_option_id) VALUES ('Epilepsy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthCondition';INSERT INTO field_option_values (name, field_option_id) VALUES ('Stroke', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthCondition';INSERT INTO field_option_values (name, field_option_id) VALUES ('Blood Disorder', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthImmunization';INSERT INTO field_option_values (name, field_option_id) VALUES ('Hepatitis B vaccine', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthImmunization';INSERT INTO field_option_values (name, field_option_id) VALUES ('Diptheria vaccine', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthImmunization';INSERT INTO field_option_values (name, field_option_id) VALUES ('Pneumococcal vaccine', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthImmunization';INSERT INTO field_option_values (name, field_option_id) VALUES ('Tetanus vaccine', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Milk Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Egg Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Peanut Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Shellfish Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Casein Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sulfite Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthAllergyType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Pollen Allergy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthTestType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Vision Screening', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthTestType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Growth & Development Assessment', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthTestType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Hearing Screening', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthTestType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Spinal Screening', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'HealthConsultationType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Normal Consultation', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Resources', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Furniture', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Energy', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Rooms', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Water', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureBuilding';INSERT INTO field_option_values (name, field_option_id) VALUES ('Classrooms', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureBuilding';INSERT INTO field_option_values (name, field_option_id) VALUES ('Library', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureBuilding';INSERT INTO field_option_values (name, field_option_id) VALUES ('Workshop', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureBuilding';INSERT INTO field_option_values (name, field_option_id) VALUES ('Toilet Block', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureBuilding';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff House', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureEnergy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Mains', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureEnergy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Solar', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureEnergy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Generator', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureEnergy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Hydro', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureEnergy';INSERT INTO field_option_values (name, field_option_id) VALUES ('No Power', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureEnergy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Other', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureFurniture';INSERT INTO field_option_values (name, field_option_id) VALUES ('Student Desks', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureFurniture';INSERT INTO field_option_values (name, field_option_id) VALUES ('Student Chairs', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureFurniture';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Desks', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureFurniture';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Chairs', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureResource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Vehicles', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureResource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Generators', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureResource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Library Books', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureResource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Projectors', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureResource';INSERT INTO field_option_values (name, field_option_id) VALUES ('Photocopiers', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Multipurpose', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Classroom', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Science Lab', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Computer Lab', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Room', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Office', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Storeroom', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureRoom';INSERT INTO field_option_values (name, field_option_id) VALUES ('Kitchen', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureSanitation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Flush - Mains', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureSanitation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Flush - Septic', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureSanitation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Pit', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureSanitation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Shore', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureSanitation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Other', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('Main', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('Rainwater Tanks', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('River', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('Well', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('Bore', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('Other', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureWater';INSERT INTO field_option_values (name, field_option_id) VALUES ('No Water', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureMaterial';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Permanent', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureMaterial';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Semi Permant', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureMaterial';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buldings - Traditional', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureMaterial';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Permanent', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureMaterial';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Semi Permant', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureMaterial';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Traditional', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Good', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Fair', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Buldings - Poor', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Good', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Fair', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'InfrastructureStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Poor', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SalaryAdditionType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Bonus', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SalaryAdditionType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Transport Fare', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SalaryDeductionType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Central Provident Fund Contribution (Base)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SalaryDeductionType';INSERT INTO field_option_values (name, field_option_id) VALUES ('MBMF', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'SalaryDeductionType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Tax', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingCourseType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Accredited', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingCourseType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Approved', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingFieldStudy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Administrative', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingFieldStudy';INSERT INTO field_option_values (name, field_option_id) VALUES ('Technical', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Basic', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Intermediate', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Advance', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingModeDelivery';INSERT INTO field_option_values (name, field_option_id) VALUES ('Online', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingModeDelivery';INSERT INTO field_option_values (name, field_option_id) VALUES ('Face', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingModeDelivery';INSERT INTO field_option_values (name, field_option_id) VALUES ('Practical', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingModeDelivery';INSERT INTO field_option_values (name, field_option_id) VALUES ('Mix', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingPriority';INSERT INTO field_option_values (name, field_option_id) VALUES ('Low', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingPriority';INSERT INTO field_option_values (name, field_option_id) VALUES ('Medium', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingPriority';INSERT INTO field_option_values (name, field_option_id) VALUES ('High', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingProvider';INSERT INTO field_option_values (name, field_option_id) VALUES ('Ministry of Education', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingProvider';INSERT INTO field_option_values (name, field_option_id) VALUES ('Ministry of Manpower', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingProvider';INSERT INTO field_option_values (name, field_option_id) VALUES ('Others', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingRequirement';INSERT INTO field_option_values (name, field_option_id) VALUES ('Mandatory', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingRequirement';INSERT INTO field_option_values (name, field_option_id) VALUES ('Elective', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('New', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Pending for Approval', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Active', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingStatus';INSERT INTO field_option_values (name, field_option_id) VALUES ('Inactive', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Promoted or New Enrolment', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Promoted (Transferred in)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Repeated', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Repeated (Transferred in)', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentBehaviourCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Outstanding', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentBehaviourCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Average', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StudentBehaviourCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Poor', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff I', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff II', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff III', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff IV', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff V', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Head Staff', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionTitle';INSERT INTO field_option_values (name, field_option_id) VALUES ('Principal', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionGrade';INSERT INTO field_option_values (name, field_option_id) VALUES ('A', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionGrade';INSERT INTO field_option_values (name, field_option_id) VALUES ('B', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionGrade';INSERT INTO field_option_values (name, field_option_id) VALUES ('C', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionGrade';INSERT INTO field_option_values (name, field_option_id) VALUES ('D', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionGrade';INSERT INTO field_option_values (name, field_option_id) VALUES ('E', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionStep';INSERT INTO field_option_values (name, field_option_id) VALUES ('1', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionStep';INSERT INTO field_option_values (name, field_option_id) VALUES ('2', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionStep';INSERT INTO field_option_values (name, field_option_id) VALUES ('3', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionStep';INSERT INTO field_option_values (name, field_option_id) VALUES ('4', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'PositionStep';INSERT INTO field_option_values (name, field_option_id) VALUES ('5', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StaffTrainingCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Permanent', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StaffTrainingCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Contract', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StaffTrainingCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Part time', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StaffTrainingCategory';INSERT INTO field_option_values (name, field_option_id) VALUES ('Internship', @fieldOptionId);
UPDATE field_option_values SET name='Sick' WHERE 'id'='24';
UPDATE field_option_values SET name='Sick' WHERE 'id'='33';
UPDATE field_option_values SET name='Permanent' WHERE 'id'='3';
UPDATE field_option_values SET name='Contract' WHERE 'id'='5';
UPDATE field_option_values SET name='Part time' WHERE 'id'='4';
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StaffType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Internship', @fieldOptionId);
UPDATE field_option_values SET name='Mixed' WHERE 'id'='8';
UPDATE field_option_values SET name='Male' WHERE 'id'='6';
UPDATE field_option_values SET name='Female' WHERE 'id'='7';
UPDATE field_option_values SET name='Math' WHERE 'id'='9';
UPDATE field_option_values SET name='Science' WHERE 'id'='10';
UPDATE field_option_values SET name='Arts' WHERE 'id'='11';
UPDATE field_option_values SET name='Practical' WHERE 'id'='13';
UPDATE field_option_values SET name='Attendance' WHERE 'id'='14';
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingResultType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Project', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'TrainingResultType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Visit', @fieldOptionId);
UPDATE field_option_values SET name='Final Exam' WHERE 'id'='12';
UPDATE field_option_values SET name='School Study' WHERE 'id'='17';
UPDATE field_option_values SET name='Self Study' WHERE 'id'='18';
UPDATE field_option_values SET name='Registration Fee' WHERE 'id'='53';
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FeeType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Course Fee', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'FeeType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Course Material Fee', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'StaffLeaveType';INSERT INTO field_option_values (name, field_option_id) VALUES ('Annual Leave', @fieldOptionId);
UPDATE field_option_values SET name='Sick Leave' WHERE 'id'='19';
UPDATE field_option_values SET name='Pending' WHERE 'id'='36';
UPDATE field_option_values SET name='Approved' WHERE 'id'='37';
UPDATE field_option_values SET name='Rejected' WHERE 'id'='38';
UPDATE field_option_values SET name='Cancelled' WHERE 'id'='40';
UPDATE field_option_values SET name='Male' WHERE 'id'='Male';
UPDATE field_option_values SET name='Female' WHERE 'id'='Female';
UPDATE field_option_values SET name='Mother' WHERE 'id'='35';
UPDATE field_option_values SET name='Father' WHERE 'id'='36';
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianRelation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandmother', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianRelation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandfather', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianRelation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Uncle', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianRelation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Aunt', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianEducationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('No Education', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianEducationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Primary', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianEducationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Secondary', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'GuardianEducationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Graduate', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationSpecialisation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Literature', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationSpecialisation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Science', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationSpecialisation';INSERT INTO field_option_values (name, field_option_id) VALUES ('Mathematics', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('No Education', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Primary', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Secondary', @fieldOptionId);
SELECT id INTO @fieldOptionId FROM `field_options` WHERE code = 'QualificationLevel';INSERT INTO field_option_values (name, field_option_id) VALUES ('Graduate', @fieldOptionId);


-- renaming old tables
RENAME TABLE institution_site_types to 1136_institution_site_types;
RENAME TABLE institution_site_ownership to 1136_institution_site_ownership;
RENAME TABLE institution_site_localities to 1136_institution_site_localities;
RENAME TABLE institution_site_statuses to 1136_institution_site_statuses;
RENAME TABLE assessment_result_types to 1136_assessment_result_types;
RENAME TABLE employment_types to 1136_employment_types;
RENAME TABLE extracurricular_types to 1136_extracurricular_types;
RENAME TABLE languages to 1136_languages;
RENAME TABLE identity_types to 1136_identity_types;
RENAME TABLE license_types to 1136_license_types;
RENAME TABLE special_need_types to 1136_special_need_types;
RENAME TABLE quality_visit_types to 1136_quality_visit_types;
RENAME TABLE health_relationships to 1136_health_relationships;
RENAME TABLE health_conditions to 1136_health_conditions;
RENAME TABLE health_immunizations to 1136_health_immunizations;
RENAME TABLE health_allergy_types to 1136_health_allergy_types;
RENAME TABLE health_test_types to 1136_health_test_types;
RENAME TABLE health_consultation_types to 1136_health_consultation_types;
RENAME TABLE salary_addition_types to 1136_salary_addition_types;
RENAME TABLE salary_deduction_types to 1136_salary_deduction_types;
RENAME TABLE training_course_types to 1136_training_course_types;
RENAME TABLE training_field_studies to 1136_training_field_studies;
RENAME TABLE training_levels to 1136_training_levels;
RENAME TABLE training_mode_deliveries to 1136_training_mode_deliveries;
RENAME TABLE training_priorities to 1136_training_priorities;
RENAME TABLE training_providers to 1136_training_providers;
RENAME TABLE training_requirements to 1136_training_requirements;
RENAME TABLE training_statuses to 1136_training_statuses;
RENAME TABLE student_categories to 1136_student_categories;
RENAME TABLE student_behaviour_categories to 1136_student_behaviour_categories;
RENAME TABLE staff_position_titles to 1136_staff_position_titles;
RENAME TABLE staff_position_grades to 1136_staff_position_grades;
RENAME TABLE staff_position_steps to 1136_staff_position_steps;
RENAME TABLE qualification_specialisations to 1136_qualification_specialisations;