-- Need to update field_options and field_option_values
CREATE TABLE IF NOT EXISTS 1136_field_options LIKE field_options;
INSERT 1136_field_options SELECT * FROM field_options;
CREATE TABLE IF NOT EXISTS 1136_field_option_values LIKE field_option_values;
INSERT 1136_field_option_values SELECT * FROM field_option_values;



-- Updating wrong model names
UPDATE `field_options` SET `code` = 'StaffPositionTitle' WHERE `field_options`.`code` = 'PositionTitle';

UPDATE `field_options` SET `code` = 'TrainingCourseResultType' WHERE `field_options`.`code` = 'TrainingResultType';

UPDATE `field_options` SET `code` = 'StaffPositionGrade' WHERE `field_options`.`code` = 'PositionGrade';

UPDATE `field_options` SET `code` = 'StaffPositionStep' WHERE `field_options`.`code` = 'PositionStep';

UPDATE `field_options` SET `code` = 'StaffPositionTitle' WHERE `field_options`.`code` = 'PositionTitle';


-- FIELD OPTIONS
-- https://docs.google.com/a/kordit.com/spreadsheets/d/1X0zyO6eOwu5wccNWMgKhi34HJyIMDJ_45oLYMe9hEN8/edit#gid=548941468
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteOwnership' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteLocality' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'InstitutionSiteStatus' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'AssessmentResultType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'EmploymentType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'ExtracurricularType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'Language' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'IdentityType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'LicenseType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'SpecialNeedType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'QualityVisitType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthRelationship' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthCondition' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthImmunization' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthAllergyType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthTestType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'HealthConsultationType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'SalaryAdditionType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'SalaryDeductionType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingCourseType' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingFieldStudy' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingLevel' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingModeDelivery' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingPriority' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingProvider' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingRequirement' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'TrainingStatus' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StudentCategory' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StudentBehaviourCategory' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StaffPositionTitle' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StaffPositionGrade' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'StaffPositionStep' LIMIT 1;
UPDATE field_options SET params = NULL WHERE code = 'QualificationSpecialisation' LIMIT 1;




-- https://docs.google.com/a/kordit.com/spreadsheets/d/1X0zyO6eOwu5wccNWMgKhi34HJyIMDJ_45oLYMe9hEN8/edit#gid=1574144139
UPDATE field_option_values SET name='Government' WHERE 'id'='1';
UPDATE field_option_values SET name='Private' WHERE 'id'='28';
UPDATE field_option_values SET name='Public' WHERE 'id'='2';
UPDATE field_option_values SET name='Private' WHERE 'id'='30';
INSERT INTO field_option_values (name, field_option_id) VALUES ('Early Childhood','3');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Primary','3');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Secondary','3');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Leasehold (State)','4');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Freehold','4');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Customary (Non Disputed)','4');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Customary (Disputed)','4');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Urban','5');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Rural','5');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Semi-Rural','5');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Semi-Urban','5');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Operating','6');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Suspended','6');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Closed','6');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Capital Income','11');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Capital Expenditure','11');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Recurrent Income','11');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Recurrent Expenditure','11');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Other','11');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Instructional','12');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Support Services','12');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Facilities','12');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Other','12');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Donations','13');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Fund Raising','13');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Subsidies','13');
INSERT INTO field_option_values (name, field_option_id) VALUES ('School Fees','13');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Scholarship','13');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Salaries','13');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Government (National)','14');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Government (Sub National)','14');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Politician','14');
INSERT INTO field_option_values (name, field_option_id) VALUES ('NGO','14');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Others','14');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Distinction','17');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Pass','17');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Fail','17');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Mobile - Personal','18');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Phone - Personal','18');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Phone - Office','18');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Email - Personal','18');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Email - Work','18');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Appointment','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Probation','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Extension','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Increment','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Termination','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Resignation','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Retirement','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Contract End','19');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Academic Club','20');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Chess Club','20');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Boys Brigade','20');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Scouts','20');
INSERT INTO field_option_values (name, field_option_id) VALUES ('2014 - From 01/01/2014 to 31/12/2014','21');
INSERT INTO field_option_values (name, field_option_id) VALUES ('2013 - From 01/01/2013 to 31/12/2013','21');
INSERT INTO field_option_values (name, field_option_id) VALUES ('2012 - From 01/01/2012 to 31/12/2012','21');

INSERT INTO field_option_values (name, field_option_id) VALUES ('English','23');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Chinese','23');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Arabic','23');
INSERT INTO field_option_values (name, field_option_id) VALUES ('French','23');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Spanish','23');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Russian','23');
INSERT INTO field_option_values (name, field_option_id) VALUES ('National','24');
INSERT INTO field_option_values (name, field_option_id) VALUES ('School','24');
INSERT INTO field_option_values (name, field_option_id) VALUES ('UNHCR','24');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Passport','24');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Car License','25');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Motorcycle License','25');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Visual','26');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Intellectual','26');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Autism','26');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Hearing','26');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Multiple','26');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Inspection','27');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Termly Quality Assuarance','27');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Mother','28');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Father','28');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandmother','28');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandfather','28');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sister','28');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Brother','28');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Asthma Attack','29');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Diabetes','29');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Tubercolosis','29');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Epilepsy','29');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Stroke','29');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Blood Disorder','29');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Hepatitis B vaccine','30');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Diptheria vaccine','30');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Pneumococcal vaccine','30');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Tetanus vaccine','30');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Milk Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Egg Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Peanut Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Shellfish Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Casein Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sulfite Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Pollen Allergy','31');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Vision Screening','32');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Growth & Development Assessment','32');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Hearing Screening','32');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Spinal Screening','32');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Normal Consultation','33');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Resources','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Furniture','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Energy','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Rooms','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Water','34');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Classrooms','35');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Library','35');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Workshop','35');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Toilet Block','35');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff House','35');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Mains','36');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Solar','36');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Generator','36');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Hydro','36');
INSERT INTO field_option_values (name, field_option_id) VALUES ('No Power','36');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Other','36');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Student Desks','37');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Student Chairs','37');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Desks','37');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Chairs','37');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Vehicles','38');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Generators','38');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Library Books','38');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Projectors','38');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Photocopiers','38');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Multipurpose','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Classroom','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Science Lab','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Computer Lab','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Room','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff Office','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Storeroom','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Kitchen','39');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Flush - Mains','40');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Flush - Septic','40');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Pit','40');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Shore','40');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Other','40');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Main','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Rainwater Tanks','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('River','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Well','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Bore','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Other','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('No Water','41');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Permanent','42');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Semi Permant','42');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buldings - Traditional','42');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Permanent','42');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Semi Permant','42');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Traditional','42');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Good','43');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buildings - Fair','43');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Buldings - Poor','43');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Good','43');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Fair','43');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Sanitation - Poor','43');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Bonus','44');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Transport Fare','44');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Central Provident Fund Contribution (Base)','45');
INSERT INTO field_option_values (name, field_option_id) VALUES ('MBMF','45');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Tax','45');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Accredited','46');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Approved','46');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Administrative','47');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Technical','47');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Basic','48');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Intermediate','48');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Advance','48');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Online','49');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Face','49');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Practical','49');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Mix','49');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Low','50');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Medium','50');
INSERT INTO field_option_values (name, field_option_id) VALUES ('High','50');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Ministry of Education','51');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Ministry of Manpower','51');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Others','51');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Mandatory','52');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Elective','52');
INSERT INTO field_option_values (name, field_option_id) VALUES ('New','53');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Pending for Approval','53');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Active','53');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Inactive','53');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Promoted or New Enrolment','54');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Promoted (Transferred in)','54');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Repeated','54');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Repeated (Transferred in)','54');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Outstanding','55');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Average','55');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Poor','55');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff I','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff II','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff III','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff IV','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Staff V','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Head Staff','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Principal','59');
INSERT INTO field_option_values (name, field_option_id) VALUES ('A','60');
INSERT INTO field_option_values (name, field_option_id) VALUES ('B','60');
INSERT INTO field_option_values (name, field_option_id) VALUES ('C','60');
INSERT INTO field_option_values (name, field_option_id) VALUES ('D','60');
INSERT INTO field_option_values (name, field_option_id) VALUES ('E','60');
INSERT INTO field_option_values (name, field_option_id) VALUES ('1','61');
INSERT INTO field_option_values (name, field_option_id) VALUES ('2','61');
INSERT INTO field_option_values (name, field_option_id) VALUES ('3','61');
INSERT INTO field_option_values (name, field_option_id) VALUES ('4','61');
INSERT INTO field_option_values (name, field_option_id) VALUES ('5','61');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Permanent','62');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Contract','62');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Part time','62');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Internship','62');
UPDATE field_option_values SET name='Sick' WHERE 'id'='24';
UPDATE field_option_values SET name='Sick' WHERE 'id'='33';
UPDATE field_option_values SET name='Permanent' WHERE 'id'='3';
UPDATE field_option_values SET name='Contract' WHERE 'id'='5';
UPDATE field_option_values SET name='Part time' WHERE 'id'='4';
INSERT INTO field_option_values (name, field_option_id) VALUES ('Internship','65');
UPDATE field_option_values SET name='Mixed' WHERE 'id'='8';
UPDATE field_option_values SET name='Male' WHERE 'id'='6';
UPDATE field_option_values SET name='Female' WHERE 'id'='7';
UPDATE field_option_values SET name='Math' WHERE 'id'='9';
UPDATE field_option_values SET name='Science' WHERE 'id'='10';
UPDATE field_option_values SET name='Arts' WHERE 'id'='11';
UPDATE field_option_values SET name='Practical' WHERE 'id'='13';
UPDATE field_option_values SET name='Attendance' WHERE 'id'='14';
INSERT INTO field_option_values (name, field_option_id) VALUES ('Project','68');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Visit','68');
UPDATE field_option_values SET name='Final Exam' WHERE 'id'='12';
UPDATE field_option_values SET name='School Study' WHERE 'id'='17';
UPDATE field_option_values SET name='Self Study' WHERE 'id'='18';
UPDATE field_option_values SET name='Registration Fee' WHERE 'id'='53';
INSERT INTO field_option_values (name, field_option_id) VALUES ('Course Fee','70');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Course Material Fee','70');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Annual Leave','73');
UPDATE field_option_values SET name='Sick Leave' WHERE 'id'='19';
UPDATE field_option_values SET name='Pending' WHERE 'id'='37';
UPDATE field_option_values SET name='Approved' WHERE 'id'='38';
UPDATE field_option_values SET name='Rejected' WHERE 'id'='40';
UPDATE field_option_values SET name='Cancelled' WHERE 'id'='40';
INSERT INTO field_option_values (name, field_option_id) VALUES ('Male','76');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Female','76');
UPDATE field_option_values SET name='Mother' WHERE 'id'='35';
UPDATE field_option_values SET name='Father' WHERE 'id'='36';
INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandmother','77');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Grandfather','77');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Uncle','77');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Aunt','77');
INSERT INTO field_option_values (name, field_option_id) VALUES ('No Education','78');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Primary','78');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Secondary','78');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Graduate','78');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Literature','79');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Science','79');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Mathematics','79');
INSERT INTO field_option_values (name, field_option_id) VALUES ('No Education','87');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Primary','87');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Secondary','87');
INSERT INTO field_option_values (name, field_option_id) VALUES ('Graduate','87');