ALTER TABLE `translations`
DROP PRIMARY KEY,
CHANGE COLUMN `en` `eng` TEXT NOT NULL,
CHANGE COLUMN `ar` `ara` TEXT NULL DEFAULT NULL,
CHANGE COLUMN `zh` `chi` TEXT NULL DEFAULT NULL,
CHANGE COLUMN `es` `spa` TEXT NULL DEFAULT NULL,
CHANGE COLUMN `fr` `fre` TEXT NULL DEFAULT NULL,
CHANGE COLUMN `ru` `rus` TEXT NULL DEFAULT NULL;