<?php
/**
 * ConfigAutoGeneratedCandidateNumberTable
 *
 * This class manages the configuration logic for the "Auto Generated Candidate Number" feature
 * in the Configuration module. It extends the ControllerActionTable, and is responsible for:
 *
 * - Initializing the table and setting the required behaviors.
 * - Defining custom validation rules for configuration fields.
 * - Hiding or customizing specific fields during index, view, add, and edit actions.
 * - Dynamically rendering placeholders and criteria keywords for candidate number generation format.
 * - Handling the setup and display of remarks and custom UI elements for configuration.
 * - Retrieving and modifying configuration item values based on system-defined placeholders.
 *
 * Placeholders supported in this config:
 * - ${area_code}
 * - ${institution_code}
 * - ${academic_period_code}
 * - ${4} (represents digit length for the candidate number like 0001, 0002...)
 *
 * This class is used to support dynamic and configurable candidate number generation rules
 * used across institutions and academic periods in the system.
 *
 * @package Configuration\Model\Table
 * @author Ehteram Ahmad
 */
namespace Configuration\Model\Table;

use ArrayObject;
use Cake\Event\EventInterface;
use Cake\ORM\Entity;
use Cake\Http\ServerRequest;
use App\Model\Table\ControllerActionTable;
use Cake\ORM\TableRegistry;
use Cake\Utility\Inflector;
use Cake\Utility\Security;
use Cake\Core\Configure;
use Cake\Validation\Validator;

class ConfigAutoGeneratedCandidateNumberTable extends ControllerActionTable
{
    public $id;
    public $authenticationType;

    protected $_defaultConfig = [
        'feature' => 'auto_generated_candidate_number',
        'name' => 'Auto Generated Candidate Number',
        'placeholder' => [
            '${area_code}' => 'Area Code for the Institution.',
            '${institution_code}'=>'Code for Institution.',
            '${academic_period_code}'=>'Academic Period Code when the candidate first enrolled in the Institution.',
            '${4}'=>'Number of digits the Candidate Number will have (e.g. 4 digit = 0001, 0002, 0003...).',
        ]
       
     ];

    public function initialize(array $config): void
    {
        $this->setTable('config_items');
        parent::initialize($config);
        $this->addBehavior('Configuration.ConfigItems');
        $this->toggle('remove', false);

        $autoGeneratedCandidateNumber = $this
            ->find()
            ->where([$this->aliasField('type') => 'Auto Generated Candidate Number'])
            ->first();
        $id = $autoGeneratedCandidateNumber->id;
        $this->id = $id;
    }

    public function validationDefault(Validator $validator): Validator
    {
        $validator = parent::validationDefault($validator);
        //POCOR-6930 Starts
        $validator->setProvider('custom', $this);
        return $validator
                ->requirePresence('value_selection');
    }

    public function beforeAction(EventInterface $event, ArrayObject $extra)
    {
        $this->field('visible', ['visible' => false]);
        $this->field('editable', ['visible' => false]);
        $this->field('field_type', ['visible' => false]);
        $this->field('option_type', ['visible' => false]);
        $this->field('code', ['visible' => false]);
        $this->field('name', ['visible' => ['index'=>true]]);
        $this->field('default_value', ['visible' => ['view'=>true]]);
        $this->field('type', ['visible' => ['view'=>true, 'edit'=>true], 'type' => 'readonly']);
        $this->field('label', ['visible' => ['view'=>true, 'edit'=>true], 'type' => 'readonly']);

        if ($this->action == 'index') {
            $url = $this->url('edit');
            $url[1] = $this->paramsEncode(['id' => $this->id]);
            $this->controller->redirect($url);
        } elseif ($this->action == 'view') {
            $this->controller->redirect('/Configurations');
        }
    }

    public function viewAfterAction(EventInterface $event, Entity $entity, ArrayObject $extra)
    {
        $this->field('value', ['visible' => true]);
        if ($entity->value != 'None') {
            $this->field('attributes', ['type' => 'custom_external_source']);
        }
        $this->field('value_selection', ['type' => 'hidden']);//POCOR-7533
    }

    public function addEditAfterAction(EventInterface $event, Entity $entity, ArrayObject $extra)
    {
        $this->setupFields($event, $entity);
    }

    public function setupFields(EventInterface $event, Entity $entity)
    {
        $this->field('remarks', ['type' => 'custom_criterias', 'after' => 'value_selection']);
    }

    public function onGetCustomCriteriasElement(EventInterface $event, $action, $entity, $attr, $options=[])
    {
        if ($action == 'add' || $action == 'edit') {
            $tableHeaders =[__('Keywords'), __('Remarks')];
            $tableCells = [];
            $fieldKey = 'remarks';

            if (!empty($entity->code)) {
                $featureKey = $entity->code;
                $placeholder = $this->_defaultConfig['placeholder'] ?? [];

                if (!empty($placeholder)) {
                    foreach ($placeholder as $placeholderKey => $placeholderObj) {
                        $rowData = [];
                        $rowData[] = __($placeholderKey);
                        $rowData[] = __($placeholderObj);

                        $tableCells[] = $rowData;
                    }
                }

                $attr['tableHeaders'] = $tableHeaders;
                $attr['tableCells'] = $tableCells;
            }

            return $event->getSubject()->renderElement('Remarks/' . $fieldKey, ['attr' => $attr]);
        }
    }

    public function onUpdateFieldValue(EventInterface $event, array $attr, $action, ServerRequest $request)
    {
        if (in_array($action, ['edit', 'add'])) {
            $id = $this->id;
            if (!empty($id)) {
                $entity = $this->get($id);
                $value = $entity->value;
                if (isset($request->getData()[$this->getAlias()]['value'])) {
                    $value = $request->getData()[$this->getAlias()]['value'];
                }
                if ($entity->field_type == 'Dropdown') {
                    $optionTable = TableRegistry::getTableLocator()->get('Configuration.ConfigItemOptions');
                    $options = $optionTable->find('list', ['keyField' => 'value', 'valueField' => 'option'])
                        ->where([
                            'ConfigItemOptions.option_type' => $entity->option_type,
                            'ConfigItemOptions.visible' => 1
                        ])
                        ->toArray();
                    $attr['options'] = $options;
                    $attr['onChangeReload'] = true;
                }
            }
        }
        return $attr;
    }

    

    public function editAfterAction(EventInterface $event, Entity $entity, ArrayObject $extra)
    {
        $value = $entity->value;
        $this->field('value', ['visible' => true]);
    }

    public function onGetFieldLabel(EventInterface $event, $module, $field, $language, $autoHumanize = true)
    {
        switch ($field) {
            case 'value':
                return __('Enabled');
            case 'value_selection':
                return __('Prefix Value');

            default:
                return parent::onGetFieldLabel($event, $module, $field, $language, $autoHumanize);
        }
    }
}
