DROP TABLE IF EXISTS `institutions`;

ALTER TABLE `institution_sites` DROP `institution_id`;
ALTER TABLE `institution_site_attachments` DROP `visible`;
ALTER TABLE `institution_site_attachments` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL ;


-- May 27th 1142hrs
-- For field options to work with plural alias
update field_options set code = 'InstitutionSiteGenders' where code = 'InstitutionSiteGender' limit 1;
update field_options set code = 'InstitutionSiteLocalities' where code = 'InstitutionSiteLocality' limit 1;
update field_options set code = 'InstitutionSiteOwnerships' where code = 'InstitutionSiteOwnership' limit 1;
update field_options set code = 'InstitutionSiteProviders' where code = 'InstitutionSiteProvider' limit 1;
update field_options set code = 'InstitutionSiteSectors' where code = 'InstitutionSiteSector' limit 1;
update field_options set code = 'InstitutionSiteStatuses' where code = 'InstitutionSiteStatus' limit 1;
update field_options set code = 'InstitutionSiteTypes' where code = 'InstitutionSiteType' limit 1;
update field_options set code = 'InstitutionSiteCustomFields' where code = 'InstitutionSiteCustomField' limit 1;
update field_options set code = 'CensusCustomFieldOptions' where code = 'CensusCustomFieldOption' limit 1;
update field_options set code = 'CensusCustomFields' where code = 'CensusCustomField' limit 1;
update field_options set code = 'CensusGrids' where code = 'CensusGrid' limit 1;
update field_options set code = 'StudentAbsenceReasons' where code = 'StudentAbsenceReason' limit 1;
update field_options set code = 'StudentBehaviourCategories' where code = 'StudentBehaviourCategory' limit 1;
update field_options set code = 'StudentCategories' where code = 'StudentCategory' limit 1;
update field_options set code = 'Genders' where code = 'Gender' limit 1;
update field_options set code = 'StudentStatuses' where code = 'StudentStatus' limit 1;
update field_options set code = 'StudentCustomFields' where code = 'StudentCustomField' limit 1;
update field_options set code = 'StaffAbsenceReasons' where code = 'StaffAbsenceReason' limit 1;
update field_options set code = 'StaffBehaviourCategories' where code = 'StaffBehaviourCategory' limit 1;
update field_options set code = 'LeaveStatuses' where code = 'LeaveStatus' limit 1;
update field_options set code = 'StaffLeaveTypes' where code = 'StaffLeaveType' limit 1;
update field_options set code = 'StaffTypes' where code = 'StaffType' limit 1;
update field_options set code = 'StaffStatuses' where code = 'StaffStatus' limit 1;
update field_options set code = 'StaffTrainingCategories' where code = 'StaffTrainingCategory' limit 1;
update field_options set code = 'StaffCustomFields' where code = 'StaffCustomField' limit 1;
update field_options set code = 'AsssesmentResultTypes' where code = 'AssessmentResultType' limit 1;
update field_options set code = 'Banks' where code = 'Bank' limit 1;
update field_options set code = 'BankBranches' where code = 'BankBranch' limit 1;
update field_options set code = 'FinanceNatures' where code = 'FinanceNature' limit 1;
update field_options set code = 'FinanceTypes' where code = 'FinanceType' limit 1;
update field_options set code = 'FinanceCategories' where code = 'FinanceCategory' limit 1;
update field_options set code = 'FinanceSources' where code = 'FinanceSource' limit 1;
update field_options set code = 'FeeTypes' where code = 'FeeType' limit 1;
update field_options set code = 'GuardianEducationLevels' where code = 'GuardianEducationLevel' limit 1;
update field_options set code = 'GuardianRelations' where code = 'GuardianRelation' limit 1;
update field_options set code = 'HealthAllergyTypes' where code = 'HealthAllergyType' limit 1;
update field_options set code = 'HealthConditions' where code = 'HealthCondition' limit 1;
update field_options set code = 'HealthConsultationTypes' where code = 'HealthConsultationType' limit 1;
update field_options set code = 'HealthImmunizations' where code = 'HealthImmunization' limit 1;
update field_options set code = 'HealthRelationships' where code = 'HealthRelationship' limit 1;
update field_options set code = 'HealthTestTypes' where code = 'HealthTestType' limit 1;
update field_options set code = 'InfrastructureBuildings' where code = 'InfrastructureBuilding' limit 1;
update field_options set code = 'InfrastructureCategories' where code = 'InfrastructureCategory' limit 1;
update field_options set code = 'InfrastructureEnergies' where code = 'InfrastructureEnergy' limit 1;
update field_options set code = 'InfrastructureFurnitures' where code = 'InfrastructureFurniture' limit 1;
update field_options set code = 'InfrastructureMaterials' where code = 'InfrastructureMaterial' limit 1;
update field_options set code = 'InfrastructureResources' where code = 'InfrastructureResource' limit 1;
update field_options set code = 'InfrastructureRooms' where code = 'InfrastructureRoom' limit 1;
update field_options set code = 'InfrastructureSanitations' where code = 'InfrastructureSanitation' limit 1;
update field_options set code = 'SanitationGenders' where code = 'SanitationGender' limit 1;
update field_options set code = 'InfrastructureStatuses' where code = 'InfrastructureStatus' limit 1;
update field_options set code = 'InfrastructureWaters' where code = 'InfrastructureWater' limit 1;
update field_options set code = 'StaffPositionGrades' where code = 'StaffPositionGrade' limit 1;
update field_options set code = 'StaffPositionSteps' where code = 'StaffPositionStep' limit 1;
update field_options set code = 'StaffPositionTitles' where code = 'StaffPositionTitle' limit 1;
update field_options set code = 'QualificationLevels' where code = 'QualificationLevel' limit 1;
update field_options set code = 'QualificationSpecialisations' where code = 'QualificationSpecialisation' limit 1;
update field_options set code = 'QualityVisitTypes' where code = 'QualityVisitType' limit 1;
update field_options set code = 'SalaryAdditionTypes' where code = 'SalaryAdditionType' limit 1;
update field_options set code = 'SalaryDeductionTypes' where code = 'SalaryDeductionType' limit 1;
update field_options set code = 'TrainingAchievementTypes' where code = 'TrainingAchievementType' limit 1;
update field_options set code = 'TrainingCourseTypes' where code = 'TrainingCourseType' limit 1;
update field_options set code = 'TrainingFieldStudies' where code = 'TrainingFieldStudy' limit 1;
update field_options set code = 'TrainingLevels' where code = 'TrainingLevel' limit 1;
update field_options set code = 'TrainingModeDeliveries' where code = 'TrainingModeDelivery' limit 1;
update field_options set code = 'TrainingNeedCategories' where code = 'TrainingNeedCategory' limit 1;
update field_options set code = 'TrainingPriorities' where code = 'TrainingPriority' limit 1;
update field_options set code = 'TrainingProviders' where code = 'TrainingProvider' limit 1;
update field_options set code = 'TrainingRequirements' where code = 'TrainingRequirement' limit 1;
update field_options set code = 'TrainingResultTypes' where code = 'TrainingResultType' limit 1;
update field_options set code = 'TrainingStatuses' where code = 'TrainingStatus' limit 1;
update field_options set code = 'ContactTypes' where code = 'ContactType' limit 1;
update field_options set code = 'EmploymentTypes' where code = 'EmploymentType' limit 1;
update field_options set code = 'ExtracurricularTypes' where code = 'ExtracurricularType' limit 1;
update field_options set code = 'IdentityTypes' where code = 'IdentityType' limit 1;
update field_options set code = 'Languages' where code = 'Language' limit 1;
update field_options set code = 'LicenseTypes' where code = 'LicenseType' limit 1;
update field_options set code = 'SpecialNeedTypes' where code = 'SpecialNeedType' limit 1;
update field_options set code = 'InfrastructureOwnerships' where code = 'InfrastructureOwnership' limit 1;
update field_options set code = 'InfrastructureConditions' where code = 'InfrastructureCondition' limit 1;
update field_options set code = 'Countries' where code = 'Country' limit 1;