<?php

namespace App\Services;

use App\Http\Controllers\Controller;
use App\Repositories\DirectoryRepository;
use JWTAuth;
use Illuminate\Support\Facades\Log;

class DirectoryService extends Controller
{

    protected $directoryRepository;

    public function __construct(DirectoryRepository $directoryRepository) 
    {
        $this->directoryRepository = $directoryRepository;
    }

    //For POCOR-8104 Start...
    public function getUserTypeList($params)
    {
        try {
            $data = $this->directoryRepository->getUserTypeList($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch User Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('User Type List Not Found');
        }
    }


    public function getUniqueOpenemisId($params)
    {
        try {
            $data = $this->directoryRepository->getUniqueOpenemisId($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Openemis Id.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Openemis Id.');
        }
    }


    public function getAutoGeneratedPassword($params)
    {
        try {
            $data = $this->directoryRepository->getAutoGeneratedPassword($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to generate Password.',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Failed to generate Password.');
        }
    }


    public function getContactTypes($params)
    {
        try {
            $data = $this->directoryRepository->getContactTypes($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Contact Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Contact Type List Not Found');
        }
    }


    public function getStaffCustomFields($params)
    {
        try {
            $data = $this->directoryRepository->getStaffCustomFields($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Staff Custom Fields List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Staff Custom Fields List Not Found');
        }
    }


    public function getPositionsType($params)
    {
        try {
            $data = $this->directoryRepository->getPositionsType($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch Position Type List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('Position Type List Not Found');
        }
    }


    public function getFTE($params)
    {
        try {
            $data = $this->directoryRepository->getFTE($params);
            return $data;
            
        } catch (\Exception $e) {
            Log::error(
                'Failed to fetch FTE List from DB',
                ['message'=> $e->getMessage(), 'trace' => $e->getTraceAsString()]
            );
            return $this->sendErrorResponse('FTE List Not Found');
        }
    }

    //For POCOR-8104 End...

}