<?php
    $tableClass = 'table-in-view';
    $tableHeaders = isset($attr['tableHeaders']) ? $attr['tableHeaders'] : [];
    $tableCells = isset($attr['tableCells']) ? $attr['tableCells'] : [];
    // $this->Form->unlockField('name');
    // $this->Form->unlockField('institution_committee_type_id');
    // $this->Form->unlockField('institution_id');
    // $this->Form->unlockField('comment');
    // $this->Form->unlockField('academic_period_id');

    
?>

<?php if ($ControllerAction['action'] == 'edit' || $ControllerAction['action'] == 'add') : 
?>
    <?php $tableClass = 'table-responsive'; ?>
    <div class="clearfix"></div>
    <?php
        echo $this->Form->input('<i class="fa fa-plus"></i> <span>'.__('Add Meeting').'</span>', [
            'label' => __('Action'),
            'type' => 'button',
            'class' => 'btn btn-default',
            'aria-expanded' => 'true',
            'onclick' => "$('#reload').val('addTextbooksStudents').click();"
        ]);
    ?>
    <div class="clearfix"></div>
    <hr>
<?php endif ?>
<div class="table-responsive" autocomplete-ref="trainer_id">
    <table class="table">
        <thead>
        <tr>
        <th>Date of Meeting
        <div class="tooltip-desc" style="display: inline-block;">
            <i class="fa fa-info-circle fa-lg table-tooltip icon-blue" tooltip-placement="top" uib-tooltip="Textbook ID is unique to each book within the school, Leave empty for autogenerated code." tooltip-append-to-body="true" tooltip-class="tooltip-blue" data-original-title="" title=""></i>
        </div></th> <th>Start Time
        <div class="tooltip-desc" style="display: inline-block;">
            <i class="fa fa-info-circle fa-lg table-tooltip icon-blue" tooltip-placement="top" uib-tooltip="Available means physically book exists while Not Available means it is missing." tooltip-append-to-body="true" tooltip-class="tooltip-blue" data-original-title="" title=""></i>
        </div></th> <th>End Time
        <div class="tooltip-desc" style="display: inline-block;">
            <i class="fa fa-info-circle fa-lg table-tooltip icon-blue" tooltip-placement="top" uib-tooltip="Condition of each available book." tooltip-append-to-body="true" tooltip-class="tooltip-blue" data-original-title="" title=""></i>
        </div></th> 
        <th>Comment
        <div class="tooltip-desc" style="display: inline-block;">
            <i class="fa fa-info-circle fa-lg table-tooltip icon-blue" tooltip-placement="top" uib-tooltip="Comments about each book regardless of availability." tooltip-append-to-body="true" tooltip-class="tooltip-blue" data-original-title="" title=""></i>
        </div></th>
        <th></th> <th></th></tr></thead>
        <tbody><tr></tr></tbody>
    </table>
</div>

