<?= $this->Html->script('app/components/alert/alert.svc', ['block' => true]); ?>
<?= $this->Html->script('Directory.angular/directoryadd/directory.directoryadd.svc', ['block' => true]); ?>
<?= $this->Html->script('Institution.angular/staff/institutions.staff.svc', ['block' => true]); ?>
<?= $this->Html->script('Institution.angular/staff/institutions.staff.ctrl', ['block' => true]); ?>
<?= $this->Html->css('ControllerAction.../plugins/chosen/css/chosen.min.css', ['block' => true]); ?>
<?= $this->Html->css('ControllerAction.../plugins/datepicker/css/bootstrap-datepicker.min', ['block' => true]); ?>
<?= $this->Html->script('ControllerAction.../plugins/datepicker/js/bootstrap-datepicker.min', ['block' => true]); ?>
<?= $this->Html->script('ControllerAction.../plugins/chosen/js/chosen.jquery.min.js', ['block' => true]); ?>
<?= $this->Html->script('ControllerAction.../plugins/chosen/js/angular-chosen.min', ['block' => true]); ?>

<!--<script data-require="jquery@1.11.3" data-semver="1.11.3" src="//code.jquery.com/jquery-1.11.3.min.js"></script>-->
<!--<link data-require="bootstrap@3.3.2" data-semver="3.3.2" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />-->
<!--<script data-require="bootstrap@3.3.2" data-semver="3.3.2" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>-->
<!--<script data-require="angularjs@1.4.9" data-semver="1.4.9" src="https://code.angularjs.org/1.4.9/angular.min.js"></script>-->
<!--<script data-require="ui-bootstrap@*" data-semver="1.3.2" src="https://cdn.rawgit.com/angular-ui/bootstrap/gh-pages/ui-bootstrap-tpls-1.3.2.js"></script>-->

<?php
$this->extend('OpenEmis./Layout/Panel');
$this->start('panelBody');
$tooltipMessage = __('The password is automatically generated by the system');
?>
<style>.chosen-choices .search-field .default{width:90px !important;}</style>

<script>
    if(localStorage.getItem('institution_id')){
        localStorage.removeItem("institution_id");
    }
    localStorage.setItem('institution_id', '<?php echo $institutionId;?>');
</script>

<div class="pd-10">
    <div class="alert {{messageClass}}" ng-if="message">
        <a class="close" aria-hidden="true" href="#" data-dismiss="alert">×</a>{{message}}
    </div>
    <div class="stepper-content-wrapper">
        <div class="steps-container">
            <ul class="steps" style="margin-left: 0">
                <li ng-class="{'active': step === 'user_details'}">
                    <div class="stepper-steps-wrapper">
                        <?= __('User Details') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': step === 'internal_search'}">
                    <div class="stepper-steps-wrapper">
                        <?= __('Internal Search') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-if="isExternalSearchEnable" ng-class="{'active': step === 'external_search'}">
                    <div class="stepper-steps-wrapper">
                        <?= __('External Search') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': step === 'confirmation'}">
                    <div class="stepper-steps-wrapper">
                        <?= __('Confirmation') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': step === 'add_staff'}">
                    <div class="stepper-steps-wrapper">
                        <?= __('Add Staff') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': step === 'summary'}">
                    <div class="stepper-steps-wrapper">
                        <?= __('Summary') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
                <li ng-class="{'active': step === 'transfer_staff'}"
                    ng-if="selectedUserData.is_diff_school > 0">
                    <div class="stepper-steps-wrapper">
                        <?= __('Staff Transfer') ?>
                        <span class="chevron"></span>
                    </div>
                </li>
            </ul>
        </div>
        <div class="actions top">
            <button ng-if="(step=='user_details')"
                    type="button"
                    class="btn close-btn"
                    ng-click="cancelProcess()"
                    style="font-size: 12px;"><?= __('Cancel') ?></button>
            <button ng-if="(step!=='user_details' && step!=='summary' && step!=='transfer_staff')"
                    type="button"
                    class="btn btn-prev close-btn"
                    ng-click="goToPrevStep()" style="font-size: 12px;">
                <?= __('Back') ?></button>
            <button ng-if="(step=='add_staff' && step!=='summary')"
                    type="button"
                    class="btn btn-default"
                    ng-click="validateDetails()"
                    ng-disabled="(error | json) != '{}'"
                    style="font-size: 12px;"><?= __('Confirm') ?></button>
            <button ng-if="(step=='summary') && step==='transfer_staff'"
                    type="button"
                    class="btn close-btn"
                    ng-click="cancelProcess()"
                    style="font-size: 12px;"><?= __('Close') ?></button>
            <button ng-disabled="(error | json) != '{}' || isNextButtonShouldDisable()"
                    type="button"
                    class="btn btn-default btn-next"
                    ng-if="step!=='add_staff' && step!=='summary' && step!=='transfer_staff'"
                    ng-click="goToNextStep()"
                    style="font-size: 12px;"><?= __('Next') ?></button>
            <button type="button" class="btn btn-default btn-next"
                    ng-if="step==='summary' && selectedUserData.is_diff_school > 0"
                    ng-click="transferStaffNextStep()"
                    ng-disabled="(error | json) != '{}'"
                    style="font-size: 12px;"><?= __('Transfer Staff') ?></button>
            <button type="button" class="btn btn-default btn-next"
                    ng-if="step === 'transfer_staff'"
                    ng-disabled="(error | json) != '{}'"
                    ng-click="saveStaffDetails()"
                    style="font-size: 12px;"><?= __('Save') ?></button>
        </div>
        <div class="step-content">
            <div class="step-pane sample-pane" ng-show="step === 'user_details'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <?= $this->element('Directory.user_details_openemis_no') ?>
                    <?= $this->element('Directory.user_details_identity') ?>
                    <?= $this->element('Directory.user_details_basic_information') ?>
                </form>
            </div>
            <div class="step-pane sample-pane" ng-if="step === 'internal_search'">
                <div class="table-wrapper">
                    <div>
                        <div class="scrolltabs">
                            <div id="institution-student-table" class="table-wrapper">
                                <div ng-if="internalGridOptions" kd-ag-grid="internalGridOptions" ag-selection-type="radio" class="ag-height-fixed"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="step-pane sample-pane" ng-if="step === 'external_search'">
                <div class="table-wrapper">
                    <div>
                        <div class="scrolltabs sticky-content">
                            <div id="institution-student-table" class="table-wrapper">
                                <div ng-if="externalGridOptions" kd-ag-grid="externalGridOptions" ag-selection-type="radio" class="ag-height-fixed"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="step-pane sample-pane" ng-show="step === 'confirmation'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <?= $this->element('Directory.confirmation_photo_content') ?>
                    <?= $this->element('Directory.confirmation_basic_user_fields') ?>
                    <?= $this->element('Directory.confirmation_address_fields') ?>
                    <?= $this->element('Directory.confirmation_directory_additional') ?>
                    <?= $this->element('Directory.confirmation_username_password') ?>
                    <?= $this->element('Directory.confirmation_custom_fields') ?>
                </form>
            </div>
            <div class="step-pane sample-pane" ng-show="step === 'add_staff'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <div class="input string required">
                        <?php $dynamicOpenemisNoHeader = (isset($dynamicOpenemisNoHeader) && !empty($dynamicOpenemisNoHeader)) ? h($dynamicOpenemisNoHeader) : __('OpenEMIS ID'); ?>

                        <label><?= $dynamicOpenemisNoHeader ?></label>
                        <input ng-model="selectedUserData.openemis_no" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Staff') ?></label>
                        <input ng-model="selectedUserData.name" type="string" ng-disabled="true">
                    </div>
                    <div class="input string">
                        <label><?= __('Identity Number') ?></label>
                        <input ng-model="selectedUserData.identity_number" type="string" ng-disabled="true">
                    </div>
                    <div class="input date">
                        <label for="Student_date_of_birth"><?= __('Date Of Birth') ?></label>
                        <div class="input-group date" id="Student_date_of_birth">
                            <input type="text" class="form-control" name="Student[date_of_birth]" ng-model="selectedUserData.date_of_birth" ng-disabled="true">
                        </div>
                    </div>
                    <div class="input select">
                        <label><?= __('Gender') ?></label>
                        <input ng-model="selectedUserData.gender.name" ng-disabled="true">
                    </div>
                    <div class="input string required">
                        <label><?= __('Staff Status') ?></label>
                        <input ng-model="staffStatus" ng-disabled="true">
                    </div>

                    <div class="input date required">
                        <label for="Staff_start_date"><?= __('Start Date') ?></label>
                        <div class="input-group date" id="Staff_start_date">
                            <input type="text" class="form-control"
                                   name="Staff[start_date]"
                                   ng-model="selectedUserData.startDate"
                                   ng-change="unsetError('start_date'); changeFte()">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                        </div>
                        <div ng-if="error.start_date" class="error-message">
                            <p>{{ error.start_date }}</p>
                        </div>
                    </div>
                    <div class="input date">
                        <label for="Staff_end_date"><?= __('End Date') ?></label>
                        <div class="input-group date" id="Staff_end_date">
                            <input type="text" class="form-control"
                                   name="Staff[end_date]"
                                   ng-model="selectedUserData.endDate"
                                   ng-change="changeFte()">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Position Type') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[position_type_id]" id="staff-position_type_id"
                                    ng-options="option.id as option.name for option in positionTypeOptions"
                                    ng-model="selectedUserData.position_type_id"
                                    ng-change="unsetError('position_type_id'); changePositionType()"
                                    ng-disabled="!selectedUserData.startDate">
                                <option value="">-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="error.position_type_id" class="error-message">
                            <p>{{ error.position_type_id }}</p>
                        </div>
                        <div ng-if="!selectedUserData.startDate" class="error-message">
                            <p>Please select a start date first.</p>
                        </div>
                    </div>
                    <div class="input select required error" ng-if="selectedUserData.position_type_id === 'Part-Time'">
                        <label><?= __('FTE') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[fte_id]" id="staff-fte_id"
                                    ng-options="option.id as option.name for option in fteOptions"
                                    ng-model="selectedUserData.fte_id"
                                    ng-change="unsetError('fte_id'); changeFte()"
                                    ng-disabled="!selectedUserData.position_type_id">
                                <option value="">-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="error.fte_id" class="error-message">
                            <p>{{ error.fte_id }}</p>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Position') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[institution_position_id]" id="staff-institution-position-id"
                                    ng-model="institutionPositionOptions.selectedOption"
                                    ng-options="option.name group by option.group disable when option.disabled for option in institutionPositionOptions.availableOptions track by option.value"
                                    ng-change="unsetError('institution_position_id'); changePosition()"
                                    ng-init="institutionPositionOptions.selectedOption = '';"
                                    ng-disabled="!selectedUserData.position_type_id">
                                <option value="">-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="error.institution_position_id" class="error-message">
                            <p>{{ error.institution_position_id }}</p>
                        </div>
                        <div ng-if="!selectedUserData.position_type_id" class="error-message">
                            <p>Please select a position type first.</p>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Is Homeroom') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[is_homeroom]" id="staff-is_homeroom"
                                    ng-model="selectedUserData.is_homeroom"
                                    ng-change="unsetError('is_homeroom')"
                                    ng-disabled="!selectedUserData.institution_position_id">
                                <option value="">-- <?= __('Select') ?> --</option>
                                <option value="0"><?= __('No') ?></option>
                                <option value="1"><?= __('Yes') ?></option>
                            </select>
                        </div>
                        <div ng-if="error.is_homeroom" class="error-message">
                            <p>{{ error.is_homeroom }}</p>
                        </div>
                        <div ng-if="!selectedUserData.institution_position_id" class="error-message">
                            <p>Please select a position first.</p>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Position Grade') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[staff_position_grade_id]" id="staff-staff_position_grade_id"
                                    ng-options="option.id as option.name for option in staffGradePositionOptions"
                                    ng-model="selectedUserData.staff_position_grade_id"
                                    ng-change="unsetError('staff_position_grade_id'); changeStaffGradePosition()"
                                    ng-disabled="!selectedUserData.institution_position_id">
                                <option value="">-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="error.staff_position_grade_id" class="error-message">
                            <p>{{ error.staff_position_grade_id }}</p>
                        </div>
                        <div ng-if="!selectedUserData.institution_position_id" class="error-message">
                            <p>Please select a position first.</p>
                        </div>
                    </div>
                    <div class="input select required error">
                        <label><?= __('Staff Type') ?></label>
                        <div class="input-select-wrapper">
                            <select name="Staff[staff_type_id]" id="staff-staff_type_id"
                                    ng-options="option.id as option.name for option in staffTypeOptions"
                                    ng-model="selectedUserData.staff_type_id"
                                    ng-change="unsetError('staff_type_id'); changeStaffType()"
                                    ng-disabled="!selectedUserData.institution_position_id">
                                <option value="">-- <?= __('Select') ?> --</option>
                            </select>
                        </div>
                        <div ng-if="error.staff_type_id" class="error-message">
                            <p>{{ error.staff_type_id }}</p>
                        </div>
                        <div ng-if="!selectedUserData.institution_position_id" class="error-message">
                            <p>Please select a position first.</p>
                        </div>
                    </div>
                </form>
            </div>

            <div class="step-pane sample-pane active" ng-if="step === 'summary'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post" style="margin: 0;">
                    <?= $this->element('Directory.summary_form') ?>
                </form>
            </div>
            <div class="step-pane sample-pane active" ng-if="step === 'transfer_staff'">
                <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                    <div class="wrapper">
                        <div class="wrapper-child">
                            <div class="panel">
                                <div class="panel-body">
                                    <div class="input string">
                                        <label><?= $dynamicOpenemisNoHeader ?></label>
                                        <input ng-model="selectedUserData.openemis_no" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Staff') ?></label>
                                        <input ng-model="selectedUserData.name" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Currently Assigned To') ?></label>
                                        <input ng-model="staffData.currentlyAssignedTo" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Requested By') ?></label>
                                        <input ng-model="staffData.requestedBy" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Position') ?></label>
                                        <input ng-model="institutionPositionOptions.selectedOption.name" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Staff Type') ?></label>
                                        <input ng-model="selectedUserData.staff_type_name" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('FTE') ?></label>
                                        <input ng-model="selectedUserData.fte_name" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Start Date') ?></label>
                                        <input ng-model="selectedUserData.startDate" type="string" ng-disabled="true">
                                    </div>
                                    <div class="input string">
                                        <label><?= __('Comment') ?></label>
                                        <textarea ng-model="selectedUserData.comment" type="string"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="actions bottom"></div>
    </div>
</div>

<script>
$(function () {
var datepicker0 = $('#Staff_start_date').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'});
var datepicker1 = $('#Staff_end_date').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'});
// var datepicker2 = $('#User_date_of_birth').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?php echo $dateLanguage; ?>'}); POCOR-8613

$( document ).on('DOMMouseScroll mousewheel scroll', function(){
    window.clearTimeout( t );
    t = window.setTimeout( function(){
        datepicker0.datepicker('place');
        datepicker1.datepicker('place');
        // datepicker2.datepicker('place'); POCOR-8613
    });
});
});

//]]>
</script>

<style>
    .pd-10 {
        padding: 10px;
    }
    .close-btn {
        border: 1px solid #000;
    }
    .header-space-lg{
        margin-bottom: 20px !important
    }
    .mb-16{
        margin-bottom: 16px;
    }
    .font-italic{
        font-style: italic;
    }
    .mb-0{
        margin-bottom: 0;
    }
    .d-flex{
        display: flex;
    }
    .position-relative{
        position: relative;
    }
    .fontSize-16{
        font-size: 16px !important;
    }
    .input-hidden{
        opacity: 0;
        position: absolute;
        width: 100% !important;
        height: 100% !important;
        left: 0;
        top: 0;
    }
    .row-content{
        margin-bottom: 16px;
    }
    .vertical-align-top {
        vertical-align: top !important;
    }
    /* stepper container wrapper */
    .stepper-content-wrapper {
        border: 1px solid #d4d4d4;
        border-radius: 4px;
        box-shadow: 0 1px 4px rgb(0 0 0 / 7%);
        background-color: #f9f9f9;
        position: relative;
        min-height: 560px;
    }
    .stepper-content-wrapper{
        -webkit-box-shadow: none!important;
        box-shadow: none!important;
        border: 0;
        background-color: #FFF;
        margin-bottom: 10px;
    }
    .stepper-content-wrapper:before,
    .stepper-content-wrapper:after {
        display: table;
        content: "";
        line-height: 0;
    }
    /* steps container */
    .stepper-content-wrapper .steps-container {
        border-radius: 4px 4px 0 0;
        overflow: hidden;
        border: 1px solid #DDD;
        height: 48px;
        border-bottom: none;
    }
    /* steps */

    .stepper-content-wrapper > ul.steps li,
    .stepper-content-wrapper > .steps-container > ul.steps li {
        float: left;
        margin: 0;
        padding: 0 20px 0 30px;
        height: 46px;
        line-height: 46px;
        position: relative;
        background: #ededed;
        color: #999999;
        font-size: 16px;
        cursor: not-allowed;
    }
    .stepper-content-wrapper > ul.steps li,
    .stepper-content-wrapper > .steps-container > ul.steps li {
        float: left;
        margin: 0;
        padding: 8px 20px 0 30px;
        height: 48px;
        line-height: 32px;
        position: relative;
        background: #ededed;
        color: #999;
        font-size: 12px;
        cursor: not-allowed;
        border-bottom: none;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background: #f1f6fc;
        color: #3a87ad;
        cursor: default;
    }
    .stepper-content-wrapper > ul.steps li:first-child,
    .stepper-content-wrapper > .steps-container > ul.steps li:first-child {
        border-radius: 4px 0 0 4px;
        padding-left: 20px;
    }
    .stepper-content-wrapper > ul.steps li:first-child,
    .stepper-content-wrapper > .steps-container > ul.steps li:first-child {
        -webkit-border-radius: 4px 0 0 0;
        border-radius: 4px 0 0 0;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        line-height: 30px;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background-color: #999;
        color: #FFF;
        cursor: default;
        border-bottom: none;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background-color: #69C;
    }
    .stepper-content-wrapper > ul.steps li.active,
    .stepper-content-wrapper > .steps-container > ul.steps li.active {
        background-color: #6699CC;
    }
    .stepper-content-wrapper .steps {
        margin-left: 0!important;
    }
    .stepper-content-wrapper > ul.steps,
    .stepper-content-wrapper > .steps-container > ul.steps {
        list-style: none outside none;
        padding: 0;
        margin: 0;
        width: 999999px;
    }
    /* step wrapper */
    .stepper-steps-wrapper {
        overflow: hidden;
        width: 100%;
        text-overflow: ellipsis;
        white-space: nowrap;
        text-align: center;
    }
    /* chevron */
    .stepper-content-wrapper > ul.steps li .chevron,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron {
        border: 24px solid transparent;
        border-left: 14px solid #d4d4d4;
        border-right: 0;
        display: block;
        position: absolute;
        right: -14px;
        top: 0;
        z-index: 1;
    }
    .stepper-content-wrapper > ul.steps li .chevron,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron {
        border: 24px solid transparent;
        border-left: 14px solid #d4d4d4;
        border-right: 0;
        display: block;
        position: absolute;
        right: -15px;
        top: -5px;
        z-index: 1;
        margin-top: 5px;
        transform: scale(1.1,1.1);
        -ms-transform: scale(1.1,1.1);
        -webkit-transform: scale(1.1,1.1);
    }
    /* chevron before */
    .stepper-content-wrapper > ul.steps li .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron:before {
        border: 24px solid transparent;
        border-left: 14px solid #ededed;
        border-right: 0;
        content: "";
        display: block;
        position: absolute;
        right: 1px;
        top: -24px;
    }
    .stepper-content-wrapper > ul.steps li .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li .chevron:before {
        border: 24px solid transparent;
        border-left: 14px solid #ededed;
        border-right: 0;
        content: "";
        display: block;
        position: absolute;
        right: 1px;
        top: -24px;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron:before {
        border-left: 14px solid #f1f6fc;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron:before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron:before {
        border-left: 14px solid #999;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron::before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron::before {
        border-left-color: #69C;
    }
    .stepper-content-wrapper > ul.steps li.active .chevron::before,
    .stepper-content-wrapper > .steps-container > ul.steps li.active .chevron::before {
        border-left-color: #6699CC;
    }
    /* action buttons */
    .stepper-content-wrapper > .actions {
        z-index: 1000;
        position: absolute;
        right: 0;
        top: 0;
        line-height: 46px;
        float: right;
        padding-left: 15px;
        padding-right: 15px;
        vertical-align: middle;
        background-color: #e5e5e5;
        border-left: 1px solid #d4d4d4;
        border-radius: 0 4px 0 0;
    }
    .stepper-content-wrapper > .actions {
        background-color: #f9f9f9;
        border-left: 1px solid #d4d4d4;
        border-radius: 0 4px 0 0;
        float: right;
        line-height: 47px;
        padding-left: 15px;
        padding-right: 15px;
        position: absolute;
        right: 1px;
        top: 1px;
        vertical-align: middle;
        z-index: 500;
    }
    /* step content */
    .stepper-content-wrapper .step-content {
        border-top: 1px solid #D4D4D4;
        padding: 10px;
        float: left;
        width: 100%;
    }
    .stepper-content-wrapper .step-content {
        border-top: 1px solid #DDD;
        border-right: 1px solid #DDD;
        border-left: 1px solid #DDD;
        border-bottom: 1px solid #DDD;
        border-radius: 0 0 4px 4px;
        float: left;
        width: 100%;
    }
    @media (min-width: 800px) {
        .row-content{
            display: flex;
            align-items: flex-start;
        }
    }
    @media only screen and (max-width: 800px){
        .stepper-content-wrapper .actions.top {
        position: fixed!important;
        bottom: 35px!important;
        top: auto!important;
        height: 50px;
        left: 0!important;
        right: 0!important;
        border-top: 1px solid #DDD;
        border-left-color: transparent;
        -webkit-border-radius: 0!important;
        border-radius: 0!important;
        }
        .stepper-content-wrapper .btn-prev,
        .stepper-content-wrapper .btn-next {
            position: relative;
        }
        .stepper-content-wrapper .btn-next {
            text-align: left;
            padding-right: 20px;
        }
        .stepper-content-wrapper .actions.top .btn-next,
        .stepper-content-wrapper .actions.top .btn-prev {
            position: absolute;
            top: 10px;
        }
        .stepper-content-wrapper .actions.top .btn-next {
            right: 10px;
        }
    }

    .uib-title {
        background-color: #fff !important;
        color: #333 !important;
        margin-top: -22px;
        border-color: #fff !important;
    }

    .uib-title:hover {
        background-color: #eee !important;
        color: #000 !important;
    }

    .uib-left, .uib-right {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #fff !important;
    }

    .uib-left:hover {
        background-color: #eee !important;
        color: #000 !important;
    }

    .uib-right:hover {
        background-color: #eee !important;
        color: #000 !important;
    }

    .uib-day .btn-sm {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #fff !important;
    }

    .uib-day .btn-sm:hover {
        background-color: #eee !important;
        color: #000 !important;
    }

    .uib-month .btn-default {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #fff !important;
    }

    .uib-month .btn-default:hover {
        background-color: #eee !important;
        color: #000 !important;
    }

    .uib-years .btn-default {
        background-color: #fff !important;
        color: #333 !important;
        border-color: #fff !important;
    }

    .uib-years .btn-default:hover {
        background-color: #eee !important;
        color: #000 !important;
    }

    .uib-datepicker-popup {
        padding: 5px 10px;
    }

    .uib-close {
        display: none !important;
    }

    .uib-datepicker-current {
        width: 230% !important;
        border-radius: 3px !important;
        border-color: #fff !important;
        color: #000 !important;
        background: #fff !important;
    }

    .uib-datepicker-current:hover {
        background: #eee !important;
    }

    .uib-clear {
        border-color: #fff !important;
        border-radius: 3px !important;
        color: #000 !important;
        background: #fff !important;
    }

    .uib-clear:hover {
        background: #eee !important;
    }

    .time {
        margin-top: -15px !important;
        margin-bottom: 5px !important;
    }

    .hours {
        vertical-align: middle !important;
    }

    .minutes {
        vertical-align: middle !important;
    }

    .check_box {
        margin-top: 2px !important;
        display: inline-flex !important;
    }

    .file-input {
        width: 200% !important;
        border: 0px !important;
        font-size: 14px !important;
        height: 40px !important;
        padding-left: 0px !important;
    }
</style>


<?php
$this->end();
?>
