<?= $this->Html->script('app/components/alert/alert.svc', ['block' => true]); ?>
<?= $this->Html->script('Directory.angular/directoryadd/directory.directoryadd.svc', ['block' => true]); ?>
<?= $this->Html->script('Institution.angular/students/institutions.students.svc', ['block' => true]); ?>
<?= $this->Html->script('Institution.angular/students/institutions.students.ctrl', ['block' => true]); ?>
<?= $this->Html->css('ControllerAction.../plugins/datepicker/css/bootstrap-datepicker.min', ['block' => true]); ?>
<?= $this->Html->script('ControllerAction.../plugins/datepicker/js/bootstrap-datepicker.min', ['block' => true]); ?>
<!--    <script data-require="jquery@1.11.3" data-semver="1.11.3" src="//code.jquery.com/jquery-1.11.3.min.js"></script>-->
<!--    <link data-require="bootstrap@3.3.2" data-semver="3.3.2" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />-->
<!--    <script data-require="bootstrap@3.3.2" data-semver="3.3.2" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>-->
<!--    <script data-require="angularjs@1.4.9" data-semver="1.4.9" src="https://code.angularjs.org/1.4.9/angular.min.js"></script>-->
<!--    <script data-require="ui-bootstrap@*" data-semver="1.3.2" src="https://cdn.rawgit.com/angular-ui/bootstrap/gh-pages/ui-bootstrap-tpls-1.3.2.js"></script>-->

<?php
$this->extend('OpenEmis./Layout/Panel');
$this->start('panelBody');

$tooltipMessage = __('The password is automatically generated by the system');
?>

    <script>
        if(localStorage.getItem('institution_id')){
            localStorage.removeItem("institution_id");
        }
        localStorage.setItem('institution_id', '<?= $institutionId; ?>');
        localStorage.setItem('institution_name', '<?= h($institutionName); ?>');
        localStorage.setItem('login_user_id', '<?= $loginUserId; ?>');
    </script>

    <div class="pd-10">
        <div class="alert {{messageClass}}" ng-if="message">
            <a class="close" aria-hidden="true" href="#" data-dismiss="alert">×</a>{{message}}
        </div>
        <div class="stepper-content-wrapper">
            <div class="steps-container">
                <ul class="steps" style="margin-left: 0">
                    <li ng-class="{'active': step === 'user_details'}">
                        <div class="stepper-steps-wrapper">
                            <?= __('Student Details') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                    <li ng-class="{'active': step === 'internal_search'}">
                        <div class="stepper-steps-wrapper">
                            <?= __('Internal Search') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                    <li ng-if="isExternalSearchEnable" ng-class="{'active': step === 'external_search'}">
                        <div class="stepper-steps-wrapper">
                            <?= __('External Search') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                    <li ng-class="{'active': step === 'confirmation'}">
                        <div class="stepper-steps-wrapper">
                            <?= __('Confirmation') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                    <li ng-class="{'active': step === 'add_student'}">
                        <div class="stepper-steps-wrapper">
                            <?= __('Add Student') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                    <li ng-class="{'active': step === 'summary'}">
                        <div class="stepper-steps-wrapper">
                            <?= __('Summary') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                    <li ng-class="{'active': step === 'transfer_student'}" ng-if="isDiffSchool">
                        <div class="stepper-steps-wrapper">
                            <?= __('Transfer Student') ?>
                            <span class="chevron"></span>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="actions top">
                <button
                    ng-if="step=='user_details'"
                    type="button"
                    class="btn close-btn"
                    ng-click="cancelProcess()"
                    style="font-size: 12px;">
                    <?= __('Cancel') ?>
                </button>
                <button
                    ng-if="step!=='user_details' && step!=='summary' && step!=='transfer_student'"
                    type="button" class="btn btn-prev close-btn" ng-click="goToPrevStep()" style="font-size: 12px;">
                    <?= __('Back') ?>
                </button>
                <button
                    ng-if="step=='add_student'
                    && step!=='summary'"
                    type="button" class="btn btn-default"
                    ng-disabled="(error | json) != '{}'"
                    ng-click="confirmUser()" style="font-size: 12px;">
                    <?= __('Confirm') ?>
                </button>
                <button
                    ng-if="step=='summary' && step==='transfer_student'"
                    type="button" class="btn close-btn"
                    ng-click="cancelProcess()"
                    style="font-size: 12px;">
                    <?= __('Close') ?>
                </button>
                <button ng-disabled="(error | json) != '{}' || isNextButtonShouldDisable()"
                        type="button" class="btn btn-default btn-next"
                        ng-if="step!=='add_student' && step!=='summary' && step!=='transfer_student'"
                        ng-click="goToNextStep()"
                        style="font-size: 12px;">
                    <?= __('Next') ?>
                </button>
                <button type="button" class="btn btn-default btn-next"
                        ng-if="step==='summary' && isDiffSchool"
                        ng-disabled="(error | json) != '{}'"
                        ng-click="transferStudentNextStep()"
                        style="font-size: 12px;">
                    <?= __('Transfer Student') ?>
                </button>
                <button type="button" class="btn btn-default btn-next"
                        ng-if="step==='transfer_student' && notSaved"
                        ng-click="transferStudent()"
                        ng-disabled="(error | json) != '{}'"
                        style="font-size: 12px;">
                    <?= __('Transfer') ?>
                </button>
                <button type="button" class="btn btn-default btn-next"
                        ng-if="step==='summary' && redirectToGuardian"
                        ng-click="addGuardian()" style="font-size: 12px;">
                    <?= __('Add Guardian') ?>
                </button>
            </div>
            <div class="step-content">
                <div class="step-pane sample-pane" ng-show="step === 'user_details'">
                    <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                        <?= $this->element('Directory.user_details_openemis_no') ?>
                        <?= $this->element('Directory.user_details_identity') ?>
                        <?= $this->element('Directory.user_details_basic_information') ?>
                    </form>
                </div>
                <div class="step-pane sample-pane" ng-if="step === 'internal_search'">
                    <div class="table-wrapper">
                        <div>
                            <div class="scrolltabs">
                                <div id="institution-student-table" class="table-wrapper">
                                    <div ng-if="internalGridOptions" kd-ag-grid="internalGridOptions" ag-selection-type="radio" class="ag-height-fixed"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="step-pane sample-pane" ng-if="step === 'external_search'">
                    <div class="table-wrapper">
                        <div>
                            <div class="scrolltabs sticky-content">
                                <div id="institution-student-table" class="table-wrapper">
                                    <div ng-if="externalGridOptions" kd-ag-grid="externalGridOptions" ag-selection-type="radio" class="ag-height-fixed"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="step-pane sample-pane" ng-show="step === 'confirmation'">
                    <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                        <?= $this->element('Directory.confirmation_photo_content') ?>
                        <?= $this->element('Directory.confirmation_basic_user_fields') ?>
                        <?= $this->element('Directory.confirmation_address_fields') ?>
                        <?= $this->element('Directory.confirmation_directory_additional') ?>
                        <?= $this->element('Directory.confirmation_username_password') ?>
                        <?= $this->element('Directory.confirmation_custom_fields') ?>
                    </form>
                </div>
                <div class="step-pane sample-pane" ng-show="step === 'add_student'">
                    <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                        <div class="row section-header header-space-lg"><?= __('Informations') ?></div>
                        <div class="input string">
                            <?php $dynamicOpenemisNoHeader = (isset($dynamicOpenemisNoHeader) && !empty($dynamicOpenemisNoHeader)) ? h($dynamicOpenemisNoHeader) : __('OpenEMIS ID'); ?>
                            <label><?= $dynamicOpenemisNoHeader ?></label>
                            <input ng-model="selectedUserData.openemis_no" type="string" ng-disabled="true">
                        </div>
                        <div class="input string">
                            <label><?= __('Student') ?></label>
                            <input ng-model="selectedUserData.name" type="string" ng-disabled="true">
                        </div>
                        <div class="input string">
                            <label><?= __('Identity Number') ?></label>
                            <input ng-model="selectedUserData.identity_number" type="string" ng-disabled="true">
                        </div>
                        <div class="input date">
                            <label for="Student_date_of_birth"><?= __('Date Of Birth') ?></label>
                            <div class="input-group date" id="Student_date_of_birth">
                                <input type="text" class="form-control" name="Student[date_of_birth]" ng-model="selectedUserData.date_of_birth" ng-disabled="true">
                            </div>
                            <div ng-if="error.date_of_birth" class="error-message">
                                <p>{{ error.date_of_birth }}</p>
                            </div>
                        </div>
                        <div class="input select">
                            <label><?= __('Gender') ?></label>
                            <input ng-model="selectedUserData.gender.name" ng-disabled="true">
                        </div>
                        <?= $this->element('Directory.confirmation_username_password') ?>
                        <!-- POCOR-8434 starts -->
                        <div class="input string">
                            <label><?= __('Student Admission Status') ?></label>
                            <input ng-model="studentAdmissionStatus" type="string" ng-disabled="true">
                        </div>
                        <!-- POCOR-8434 ends -->
                        <div class="input select required error">
                            <label><?= __('Academic Period') ?></label>
                            <div class="input-select-wrapper">
                                <select name="Student[academic_period_id]" id="student-academic_period_id"
                                        ng-options="option.id as option.name for option in academicPeriodOptions"
                                        ng-model="selectedUserData.academic_period_id"
                                        ng-change="changeAcademicPeriod()">
                                    <option value="" >-- <?= __('Select') ?> --</option>
                                </select>
                            </div>
                            <div ng-if="error.academic_period_id" class="error-message">
                                <p>{{ error.academic_period_id }}</p>
                            </div>
                        </div>
                        <div class="input select required error">
                            <label><?= __('Education Grade') ?></label>
                            <div class="input-select-wrapper">
                                <select name="Student[education_grade_id]" id="student-education_grade_id"
                                        ng-options="option.education_grade_id as option.name for option in educationGradeOptions"
                                        ng-model="selectedUserData.education_grade_id"
                                        ng-change="changeEducationGrade()">
                                    <option value="" >-- <?= __('Select') ?> --</option>
                                </select>
                            </div>
                            <div ng-if="error.education_grade_id" class="error-message">
                                <p>{{ error.education_grade_id }}</p>
                            </div>
                        </div>
                        <div class="input select">
                            <label><?= __('Class') ?></label>
                            <div class="input-select-wrapper">
                                <select name="Student[class_id]" id="student-class_id"
                                        ng-options="option.id as option.name for option in classOptions"
                                        ng-model="selectedUserData.class_id"
                                        ng-change="changeClass()">
                                    <option value="" >-- <?= __('Select') ?> --</option>
                                </select>
                            </div>
                            <div ng-if="postResponse.error.class_id" class="error-message">
                                <p ng-repeat="error in postResponse.error.class_id">{{ error }}</p>
                            </div>
                        </div>
                        <div class="input date required">
                            <label for="Students_start_date"><?= __('Start Date') ?></label>
                            <div class="input-group date" id="Student_start_date">
                                <input type="text" class="form-control"
                                       name="Student[start_date]"
                                       ng-model="selectedUserData.startDate"
                                       ng-change="changeStartDate()"
                                >
                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            </div>
                            <div ng-if="error.startDate" class="error-message">
                                <p>{{ error.startDate }}</p>
                            </div>
                        </div>
                        <div class="input date required">
                            <label for="Students_end_date"><?= __('End Date') ?></label>
                            <div class="input-group date" id="Students_end_date">
                                <input type="text" class="form-control" name="Student[endDate]" ng-model="selectedUserData.endDate" ng-disabled="true">
                            </div>
                        </div>
                        <div ng-repeat="customField in customFieldsArray">
                            <div class="row section-header header-space-lg">{{customField.sectionName}}</div>
                            <div ng-repeat="field in customField.data">
                                <div class="input string" ng-class="{'required': field.is_mandatory !== 0}" ng-if="field.field_type === 'TEXT' || field.field_type === 'TEXTAREA' || field.field_type === 'NOTE' || field.field_type === 'NUMBER' || field.field_type === 'DECIMAL'">
                                    <label>{{field.name}}</label>
                                    <input ng-if="field.field_type === 'TEXT'" ng-model="field.answer" type="text" ng-required="field.is_mandatory !== 0">
                                    <textarea ng-if="field.field_type === 'TEXTAREA' || field.field_type === 'NOTE'" ng-model="field.answer" type="text" ng-required="field.is_mandatory !== 0"></textarea>
                                    <input ng-if="field.field_type === 'NUMBER'" ng-model="field.answer" type="number" ng-required="field.is_mandatory !== 0">
                                    <input ng-if="field.field_type === 'DECIMAL'" ng-model="field.answer" type="number" step="0.01" onKeyPress="if(this.value.length === 10) return false;"
                                           ng-change="onDecimalNumberChange(field)"
                                           ng-required="field.is_mandatory !== 0">
                                    <div ng-if="field.errorMessage" class="error-message">
                                        <p>{{ field.errorMessage }}</p>
                                    </div>
                                </div>
                                <div class="input select" ng-class="{'required': field.is_mandatory !== 0}" ng-if="field.field_type === 'DROPDOWN'">
                                    <label>{{field.name}}</label>
                                    <div class="input-select-wrapper">
                                        <select name="Student[option_id]" id={{field.student_custom_field_id}}
                                                ng-options="option.option_id as option.option_name for option in field.option"
                                                ng-model="field.answer"
                                                ng-change="changeOption(field,field.answer)" ng-required="field.is_mandatory !== 0">
                                            <option value="" >-- <?= __('Select') ?> --</option>
                                        </select>
                                    </div>
                                    <div ng-if="field.errorMessage" class="error-message">
                                        <p>{{ field.errorMessage }}</p>
                                    </div>
                                </div>
                                <div class="input date" ng-class="{'required': field.is_mandatory !== 0}" ng-if="field.field_type === 'DATE'">
                                    <label for={{field.student_custom_field_id}}>{{field.name}}</label>
                                    <div class="input-group date" id={{field.student_custom_field_id}} datepicker="" ng-model="field.answer" ng-click="[field.isDatepickerOpen = !field.isDatepickerOpen]" ng-init="field.isDatepickerOpen = false">
                                        <input type="text" class="form-control" ng-model="field.answer" uib-datepicker-popup="dd-MM-yyyy" is-open="field.isDatepickerOpen" datepicker-options="datepickerOptions" close-text="Close" alt-input-formats="altInputFormats" style="width: calc(100% - 52px) !important" ng-change="field.isDatepickerOpen = false" ng-required="field.is_mandatory !== 0">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                    </div>
                                    <div ng-if="field.errorMessage" class="error-message">
                                        <p>{{ field.errorMessage }}</p>
                                    </div>
                                </div>
                                <div class="input date" ng-class="{'required': field.is_mandatory !== 0}" ng-if="field.field_type === 'TIME'">
                                    <label for={{field.student_custom_field_id}}>{{field.name}}</label>
                                    <div class="input-group time" uib-timepicker ng-model="field.answer" hour-step="field.hourStep" minute-step="field.minuteStep" show-meridian="field.isMeridian"></div>
                                    <div ng-if="field.errorMessage" class="error-message" style="margin-left: 150px;">
                                        <p>{{ field.errorMessage }}</p>
                                    </div>
                                </div>
                                <div class="input date" ng-class="{'required': field.is_mandatory !== 0}" ng-if="field.field_type === 'CHECKBOX'">
                                    <label for={{field.student_custom_field_id}}>{{field.name}}</label>
                                    <div class="input-group check_box">
                                        <div ng-repeat="option in field.option">
                                            <input type="checkbox" id={{option.option_id}} name={{option.option_name}} value={{option.option_id}} ng-model="option.selected" ng-change="selectOption(field)" ng-required="field.is_mandatory !== 0">
                                            <label for={{option.option_id}}> {{option.option_name}}</label>
                                        </div>
                                        <div ng-if="field.errorMessage" class="error-message">
                                            <p>{{ field.errorMessage }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="step-pane sample-pane" ng-show="isDiffSchool > 0 && step === 'transfer_student'">
                    <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post">
                        <div class="input string">
                            <label><?= $dynamicOpenemisNoHeader ?></label>
                            <input ng-model="selectedUserData.openemis_no" type="string" ng-disabled="true">
                        </div>
                        <div class="input string">
                            <label><?= __('Student') ?></label>
                            <input ng-model="selectedUserData.name" type="string" ng-disabled="true">
                        </div>
                        <div class="input string">
                            <label><?= __('Currently Allocated To') ?></label>
                            <input ng-model="selectedUserData.currentlyAllocatedTo" type="string" ng-disabled="true">
                        </div>
                        <div class="input select required error">
                            <label><?= __('Academic Period') ?></label>
                            <input ng-model="currentYear" type="string" ng-disabled="true">
                        </div>
                        <div class="input select required error">
                            <label><?= __('Education Grade') ?></label>
                            <div class="input-select-wrapper">
                                <select name="Student[education_grade_id]" id="student-education_grade_id"
                                        ng-options="option.education_grade_id as option.name for option in educationGradeOptions"
                                        ng-model="selectedUserData.education_grade_id"
                                        ng-change="changeEducationGrade()">
                                    <option value="" >-- <?= __('Select') ?> --</option>
                                </select>
                            </div>
                            <div ng-if="error.education_grade_id" class="error-message">
                                <p>{{ error.education_grade_id }}</p>
                            </div>
                        </div>
                        <div class="input select">
                            <label><?= __('Class') ?></label>
                            <div class="input-select-wrapper">
                                <select name="Student[class_id]" id="student-class_id"
                                        ng-options="option.id as option.name for option in classOptions"
                                        ng-model="selectedUserData.class_id"
                                        ng-change="changeClass()">
                                    <option value="" >-- <?= __('Select') ?> --</option>
                                </select>
                            </div>
                            <div ng-if="postResponse.error.class_id" class="error-message">
                                <p ng-repeat="error in postResponse.error.class_id">{{ error }}</p>
                            </div>
                        </div>
                        <div class="input string">
                            <label><?= __('Student Transfer Status') ?></label><!-- POCOR-8434 change lable -->
                            <input ng-model="studentStatus" type="string" ng-disabled="true">
                        </div>
                        <div class="input date required">
                            <label for="Student_transfer_start_date"><?= __('Start Date') ?></label>
                            <div class="input-group date" id="Student_transfer_start_date">
                                <input type="text" class="form-control" name="Student[transfer_start_date]"
                                       ng-change="changeTransferStartDate()"
                                       ng-model="selectedUserData.transferStartDate"
                                >
                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            </div>
                            <div ng-if="error.transferStartDate" class="error-message">
                                <p>{{ error.transferStartDate }}</p>
                            </div>
                        </div>
                        <div class="input date required">
                            <label for="Students_end_date"><?= __('End Date') ?></label>
                            <div class="input-group date" id="Students_end_date">
                                <input type="text" class="form-control" name="Student[endDate]" ng-model="selectedUserData.endDate" ng-disabled="true">
                            </div>
                        </div>
                        <div class="input select required error">
                            <label><?= __('Student Transfer Reason') ?></label>
                            <div class="input-select-wrapper">
                                <select name="Student[transfer_reason_id]" id="student-transfer_reason_id"
                                        ng-options="option.id as option.name for option in transferReasonsOptions"
                                        ng-model="selectedUserData.transfer_reason_id"
                                        ng-change="changeTransferReason()">
                                    <option value="" >-- <?= __('Select') ?> --</option>
                                </select>
                            </div>
                            <div ng-if="error.transfer_reason_id" class="error-message">
                                <p>{{ error.transfer_reason_id }}</p>
                            </div>
                        </div>
                        <div class="input string">
                            <label for="Students_transfer_comment"><?= __('Comment') ?></label>
                            <textarea type="text" class="form-control" name="Student[transfer_comment]" ng-model="selectedUserData.transferComment"></textarea>
                        </div>
                    </form>
                </div>
                <div class="step-pane sample-pane active" ng-if="step === 'summary'">
                    <form class="form-horizontal ng-pristine ng-valid" accept-charset="utf-8" method="post" style="margin: 0;">
                        <div class="wrapper">
                            <div class="wrapper-child">
                                <div class="panel">
                                    <div class="panel-body">
                                        <div class="row section-header"><?= __('Information') ?></div>
                                        <div class="row hidden"></div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Photo Content') ?></div>
                                            <div class="form-input">
                                                <div class="table-thumb">
                                                    <div class="profile-image-thumbnail">
                                                        <i class="kd-staff"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= $dynamicOpenemisNoHeader ?></div>
                                            <div class="form-input">{{selectedUserData.openemis_no}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('First Name') ?></div>
                                            <div class="form-input">{{selectedUserData.first_name}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Middle Name') ?></div>
                                            <div class="form-input">{{selectedUserData.middle_name}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Third Name') ?></div>
                                            <div class="form-input">{{selectedUserData.third_name}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Last Name') ?></div>
                                            <div class="form-input">{{selectedUserData.last_name}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Preferred Name') ?></div>
                                            <div class="form-input">{{selectedUserData.preferred_name}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Gender') ?></div>
                                            <div class="form-input">{{selectedUserData.gender.name}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Date of Birth') ?></div>
                                            <div class="form-input">{{selectedUserData.date_of_birth}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Email') ?></div>
                                            <div class="form-input">{{selectedUserData.email}}</div>
                                        </div>
                                        <div class="row section-header"><?= __('Identities / Nationalities') ?></div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Details') ?></div>
                                            <div class="form-input" ng-if="selectedUserData.identity_type_name || selectedUserData.identity_number || selectedUserData.nationality_name">
                                                <div class="form-input table-full-width">
                                                    <div class="table-wrapper">
                                                        <div class="table-in-view">
                                                            <table class="table" style="margin-bottom: 0px !important;">
                                                                <thead>
                                                                <tr>
                                                                    <th><?= __('Identity Type') ?></th>
                                                                    <th><?= __('Identity Number') ?></th>
                                                                    <th><?= __('Nationality') ?></th>
                                                                    <th><?= __('Preferred') ?></th>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="vertical-align-top">{{selectedUserData.identity_type_name}}</td>
                                                                    <td class="vertical-align-top">{{selectedUserData.identity_number}}</td>
                                                                    <td class="vertical-align-top">{{selectedUserData.nationality_name}}</td>
                                                                    <td class="vertical-align-top"><?= __('No') ?></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row section-header"><?= __('Location') ?></div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Address') ?></div>
                                            <div class="form-input">{{selectedUserData.address}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Postal Code') ?></div>
                                            <div class="form-input">{{selectedUserData.postalCode}}</div>
                                        </div>
                                        <div class="row section-header"><?= __('Address Area') ?></div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Address Area') ?></div>
                                            <div class="form-input">{{selectedUserData.addressArea.name}}</div>
                                        </div>
                                        <div class="row section-header"><?= __('Birthplace Area') ?></div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Birthplace Area') ?></div>
                                            <div class="form-input">{{selectedUserData.birthplaceArea.name}}</div>
                                        </div>
                                        <div class="row section-header"><?= __('Other Information') ?></div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Modified By') ?></div>
                                            <div class="form-input"><?= __('System Administrator') ?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Modified On') ?></div>
                                            <div class="form-input">{{todayDate}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Created By') ?></div>
                                            <div class="form-input"><?= __('System Administrator') ?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6 col-md-3 form-label"><?= __('Created On') ?></div>
                                            <div class="form-input">{{todayDate}}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="actions bottom"></div>
        </div>
    </div>

    <script>
        $(function () {
            var datepicker0 = $('#Student_start_date').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?= $dateLanguage ?>'});
            var datepicker1 = $('#student-date_of_birth').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?= $dateLanguage ?>'});// POCOR-8434 change datepicker id #User_date_of_birth to #student-date_of_birth
            // var datepicker1 = $('#User_date_of_birth').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?= $dateLanguage ?>'});POCOR-8613
            var datepicker2 = $('#Student_transfer_start_date').datepicker({"format":"dd-mm-yyyy","todayBtn":"linked","orientation":"auto","autoclose":true, language: '<?= $dateLanguage ?>'});
            $( document ).on('DOMMouseScroll mousewheel scroll', function(){
                window.clearTimeout( t );
                t = window.setTimeout( function(){
                    datepicker0.datepicker('place');
                    // datepicker1.datepicker('place');POCOR-8613
                    datepicker2.datepicker('place');
                });
            });
        });
    </script>

    <style>
        .pd-10 {
            padding: 10px;
        }
        .close-btn {
            border: 1px solid #000;
        }
        .header-space-lg {
            margin-bottom: 20px !important;
        }
        .mb-16 {
            margin-bottom: 16px;
        }
        .font-italic {
            font-style: italic;
        }
        .mb-0 {
            margin-bottom: 0;
        }
        .d-flex {
            display: flex;
        }
        .position-relative {
            position: relative;
        }
        .fontSize-16 {
            font-size: 16px !important;
        }
        .input-hidden {
            opacity: 0;
            position: absolute;
            width: 100% !important;
            height: 100% !important;
            left: 0;
            top: 0;
        }
        .row-content {
            margin-bottom: 16px;
        }
        .vertical-align-top {
            vertical-align: top !important;
        }
        .stepper-content-wrapper {
            border: 1px solid #d4d4d4;
            border-radius: 4px;
            box-shadow: 0 1px 4px rgb(0 0 0 / 7%);
            background-color: #f9f9f9;
            position: relative;
            min-height: 560px;
        }
        .stepper-content-wrapper {
            -webkit-box-shadow: none !important;
            box-shadow: none !important;
            border: 0;
            background-color: #FFF;
            margin-bottom: 10px;
        }
        .stepper-content-wrapper:before,
        .stepper-content-wrapper:after {
            display: table;
            content: "";
            line-height: 0;
        }
        .steps-container {
            border-radius: 4px 4px 0 0;
            overflow: hidden;
            border: 1px solid #DDD;
            height: 48px;
            border-bottom: none;
        }
        .steps-container .steps li {
            float: left;
            margin: 0;
            padding: 8px 20px 0 30px;
            height: 48px;
            line-height: 32px;
            position: relative;
            background: #ededed;
            color: #999;
            font-size: 12px;
            cursor: not-allowed;
            border-bottom: none;
        }
        .steps-container .steps li.active {
            background: #f1f6fc;
            color: #3a87ad;
            cursor: default;
        }
        .steps-container .steps li:first-child {
            -webkit-border-radius: 4px 0 0 0;
            border-radius: 4px 0 0 0;
        }
        .steps-container .steps li.active {
            background-color: #999;
            color: #FFF;
            cursor: default;
            border-bottom: none;
        }
        .steps-container .steps li.active {
            background-color: #69C;
        }
        .steps-container .steps li.active {
            background-color: #6699CC;
        }
        .steps {
            margin-left: 0 !important;
        }
        .steps-container .steps {
            list-style: none outside none;
            padding: 0;
            margin: 0;
            width: 999999px;
        }
        .stepper-steps-wrapper {
            overflow: hidden;
            width: 100%;
            text-overflow: ellipsis;
            white-space: nowrap;
            text-align: center;
        }
        .steps-container .steps li .chevron {
            border: 24px solid transparent;
            border-left: 14px solid #d4d4d4;
            border-right: 0;
            display: block;
            position: absolute;
            right: -15px;
            top: -5px;
            z-index: 1;
            margin-top: 5px;
            transform: scale(1.1, 1.1);
            -ms-transform: scale(1.1, 1.1);
            -webkit-transform: scale(1.1, 1.1);
        }
        .steps-container .steps li .chevron:before {
            border: 24px solid transparent;
            border-left: 14px solid #ededed;
            border-right: 0;
            content: "";
            display: block;
            position: absolute;
            right: 1px;
            top: -24px;
        }
        .steps-container .steps li.active .chevron:before {
            border-left: 14px solid #999;
        }
        .steps-container .steps li.active .chevron::before {
            border-left-color: #69C;
        }
        .steps-container .steps li.active .chevron::before {
            border-left-color: #6699CC;
        }
        .actions {
            z-index: 1000;
            position: absolute;
            right: 0;
            top: 0;
            line-height: 46px;
            float: right;
            padding-left: 15px;
            padding-right: 15px;
            vertical-align: middle;
            background-color: #e5e5e5;
            border-left: 1px solid #d4d4d4;
            border-radius: 0 4px 0 0;
        }
        .actions {
            background-color: #f9f9f9;
            border-left: 1px solid #d4d4d4;
            border-radius: 0 4px 0 0;
            float: right;
            line-height: 47px;
            padding-left: 15px;
            padding-right: 15px;
            position: absolute;
            right: 1px;
            top: 1px;
            vertical-align: middle;
            z-index: 500;
        }
        .step-content {
            border-top: 1px solid #DDD;
            border-right: 1px solid #DDD;
            border-left: 1px solid #DDD;
            border-bottom: 1px solid #DDD;
            border-radius: 0 0 4px 4px;
            float: left;
            width: 100%;
        }
        @media (min-width: 800px) {
            .row-content {
                display: flex;
                align-items: flex-start;
            }
        }
        @media only screen and (max-width: 800px) {
            .actions.top {
                position: fixed !important;
                bottom: 35px !important;
                top: auto !important;
                height: 50px;
                left: 0 !important;
                right: 0 !important;
                border-top: 1px solid #DDD;
                border-left-color: transparent;
                -webkit-border-radius: 0 !important;
                border-radius: 0 !important;
            }
            .btn-prev, .btn-next {
                position: relative;
            }
            .btn-next {
                text-align: left;
                padding-right: 20px;
            }
            .actions.top .btn-next, .actions.top .btn-prev {
                position: absolute;
                top: 10px;
            }
            .actions.top .btn-next {
                right: 10px;
            }
        }
        .uib-title {
            background-color: #fff !important;
            color: #333 !important;
            margin-top: -22px;
            border-color: #fff !important;
        }
        .uib-title:hover {
            background-color: #eee !important;
            color: #000 !important;
        }
        .uib-left, .uib-right {
            background-color: #fff !important;
            color: #333 !important;
            border-color: #fff !important;
        }
        .uib-left:hover {
            background-color: #eee !important;
            color: #000 !important;
        }
        .uib-right:hover {
            background-color: #eee !important;
            color: #000 !important;
        }
        .uib-day .btn-sm {
            background-color: #fff !important;
            color: #333 !important;
            border-color: #fff !important;
        }
        .uib-day .btn-sm:hover {
            background-color: #eee !important;
            color: #000 !important;
        }
        .uib-month .btn-default {
            background-color: #fff !important;
            color: #333 !important;
            border-color: #fff !important;
        }
        .uib-month .btn-default:hover {
            background-color: #eee !important;
            color: #000 !important;
        }
        .uib-years .btn-default {
            background-color: #fff !important;
            color: #333 !important;
            border-color: #fff !important;
        }
        .uib-years .btn-default:hover {
            background-color: #eee !important;
            color: #000 !important;
        }
        .uib-datepicker-popup {
            padding: 5px 10px;
        }
        .uib-close {
            display: none !important;
        }
        .uib-datepicker-current {
            width: 230% !important;
            border-radius: 3px !important;
            border-color: #fff !important;
            color: #000 !important;
            background: #fff !important;
        }
        .uib-datepicker-current:hover {
            background: #eee !important;
        }
        .uib-clear {
            border-color: #fff !important;
            border-radius: 3px !important;
            color: #000 !important;
            background: #fff !important;
        }
        .uib-clear:hover {
            background: #eee !important;
        }
        .time {
            margin-top: -15px !important;
            margin-bottom: 5px !important;
        }
        .hours {
            vertical-align: middle !important;
        }
        .minutes {
            vertical-align: middle !important;
        }
        .check_box {
            margin-top: 2px !important;
            display: inline-flex !important;
        }
        .file-input {
            width: 200% !important;
            border: 0px !important;
            font-size: 14px !important;
            height: 40px !important;
            padding-left: 0px !important;
        }
    </style>

<?php
$this->end();
?>
